---
title: FSC Europe 20m Daily V2
collection: 2bb9974a-0eb8-484d-adf1-20cc307021b6
---
## About
[Official documentation](https://land.copernicus.eu/en/products/snow/fractional-snow-cover)

The Fractional Snow Cover (FSC) product provides the fraction of the surface covered by snow at the top of canopy (FSC-TOC) and on ground (FSC-OG) per pixel as a percentage (0% – 100%). It is generated in near real-time at European scale based on optical satellite data from the Sentinel-2 constellation, with a spatial resolution of 20 m x 20 m. It is available for the period from 2016 to the present. More information here.

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_WSI_FRACTIONAL-SNOW-COVER_EUROPE_UTM_20M_DAILY_V2&clmsSelectedPath=Snow%20Cover%20Extent&clmsSelectedCollection=COPERNICUS_CLMS_WSI_FRACTIONAL-SNOW-COVER_EUROPE_UTM_20M_DAILY_V2) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

`2bb9974a-0eb8-484d-adf1-20cc307021b6`

## Date range

2016 - present

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|FSCOG|Snow fraction on-ground (%)|Fractional snow cover on ground (%): 0-100=snow fraction; 205=cloud or cloud shadow; 210=inland water|UINT8|0.0-100.0|1|0|
|FSCOG_QA|Quality layer for the on-ground snow fraction (FSC OG) layer|Quality assessment for FSCOG: 0=high quality; 1=medium quality; 2=low quality; 3=minimal quality; 205=cloud or cloud shadow; 210=inland water|UINT8|0.0-3.0|1|0|
|FSCTOC|Snow fraction on top of canopy (%)|Fractional snow cover top of canopy (%): 0-100=snow fraction; 205=cloud or cloud shadow; 210=inland water|UINT8|0.0-100.0|1|0|
|FSCTOC_QA|Quality layer for the Top-of-canopy snow fraction (FSC TOC) layer|Quality assessment for FSCTOC: 0=high quality; 1=medium quality; 2=low quality; 3=minimal quality; 205=cloud or cloud shadow; 210=inland water|UINT8|0.0-3.0|1|0|
|QAFLAGS|Quality flags|Bitmask with pixel quality flags.|UINT8|---|1|0|
|CLD|Cloud and cloud shadow mask|Bitmask with cloud and cloud shadow masks derived from MAJA Sentinel-2 Level-2A product.|UINT8|---|1|0|
|NDSI|Normalised Difference Snow Index (%) of detected snow areas|Normalised Difference Snow Index (%): 0-100=NDSI values for snow-covered pixels; 205=cloud or cloud shadow; 210=inland water|UINT8|0.0-100.0|1|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/bio-geophysical-parameters/snow/snow-cover-extent/clms_wsi_fractional-snow-cover_europe_utm_20m_daily_v2)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/Batch.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
