---
title: GFSC Europe 60m Daily V1
collection: 0b5265f5-3664-44c2-96ab-e91aba67b0c3
---
## About
[Official documentation](https://land.copernicus.eu/en/products/snow/high-resolution-gap-filled-fractional-snow-cover)

The daily cumulative Gap-filled Fractional Snow Cover (GFSC) product provides pixel-wise snow cover extent as a percentage (0% – 100%) with a spatial resolution of 60 m x 60 m. It is generated on a daily basis at European scale based on synthetic aperture radar (SAR) data from the Sentinel-1 constellation and optical imagery from the Sentinel-2 constellation. The product is generated by merging all available Sentinel-1 and Sentinel-2 observations acquired over the previous seven days to produce a spatially complete composite of snow conditions, thereby reducing data gaps caused by cloud cover and sensor coverage limitations. Snow information derived from Sentinel-1 is focused on the detection of wet snow in high-mountain areas. It is available for the period from 2016 to the present. More information here.

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_WSI_GAP-FILLED-FRACTIONAL-SNOW-COVER_EUROPE_UTM_60M_DAILY_V1&clmsSelectedPath=Snow%20Cover%20Extent&clmsSelectedCollection=COPERNICUS_CLMS_WSI_GAP-FILLED-FRACTIONAL-SNOW-COVER_EUROPE_UTM_60M_DAILY_V1) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

`0b5265f5-3664-44c2-96ab-e91aba67b0c3`

## Date range

2016 - present

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|GF|Snow fraction (%)|Snow fraction (%): 0-100=snow fraction; 205=cloud or cloud shadow; 210=inland water|UINT8|0.0-100.0|1|0|
|GF_QA|Quality layer for the snow fraction (GF) layer|Quality assessment for GF: 0=high quality; 1=medium quality; 2=low quality; 3=minimal quality; 205=cloud or cloud shadow; 210=inland water|UINT8|0.0-3.0|1|0|
|QAFLAGS|Quality flags|Bitmask with pixel quality flags|UINT8|---|1|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/bio-geophysical-parameters/snow/snow-cover-extent/clms_wsi_gap-filled-fractional-snow-cover_europe_utm_60m_daily_v1)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/BatchV2.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
