---
title: SCE Dec 2025-present (raster 1km), global, daily – version 1
---
## About
[Official documentation](https://land.copernicus.eu/en/products/snow?tab=snow_cover_extent)

The SCE product provides daily information on fractional snow cover (0-100%) per pixel for Global Land Areas with about 1km pixel size. The product is based on medium resolution optical satellite data (VIIRS and SLSTR). In forested areas, the product provides information on snow on ground.

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=&clmsSelectedPath=Snow%20Cover%20Extent&clmsSelectedCollection=) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

`84c1669b-a51f-4193-bf9d-e470e46efea8`

## Date range

Dec 2025-present

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|SCE|Daily global snow cover extent at 1km resolution from VIIRS and SLSTR sensors.|Surface snow area fraction - percent (0-100% snow, flags: 0=Outside_AOI, 20=Water, 23=Salt_Lake, 30=Cloud, 70=Antarctica, 251=Polar_Night, 254=Input_Data_Error)|INT16|0.0-254.0|1|0|
|UNC|Unbiased Root Mean Square Error for Snow Cover Extent at 1km resolution.|Unbiased Root Mean Square Error - percent (flags: 0=Outside_AOI, 20=Water, 23=Salt_Lake, 30=Cloud, 70=Antarctica, 251=Polar_Night, 254=Input_Data_Error)|INT16|0.0-254.0|1|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/bio-geophysical-parameters/snow/snow-cover-extent/sce_global_1km_daily_v1)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/Batch.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
