---
title: LST TCI 3km 10-daily V3
collection: 21ee9e5d-bfca-4553-98d8-62f9fa07eedf
---
## About
[Official documentation](https://land.copernicus.eu/en/products/temperature-and-reflectance/10daily-land-surface-temperature-synthesis-global-v3-0-3km)

Provides Land Surface Temperature estimates at global scale, at a spatial resolution of ~3 km. More information here.

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_LST-TCI_GLOBAL_3KM_10DAILY_V3&clmsSelectedPath=Land%20Surface%20Temperature&clmsSelectedCollection=COPERNICUS_CLMS_LST-TCI_GLOBAL_3KM_10DAILY_V3) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

```default
21ee9e5d-bfca-4553-98d8-62f9fa07eedf
```

## Date range

2018 - present

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|MEDIAN|Median of Land Surface Temperature observed during the 10-days period, regardless the time of the day.|[K]|INT16|-203.15-353.15|1/100|273.15|
|TCI|Thermal Condition Index for the compositing period.||INT16|0.0-1.0|1/10000|0|
|FOBS|Fraction of valid observations.||INT16|0.0-1.0|1/100|0|
|MIN|Minimum of Land Surface Temperature observed during the 10-days period, regardless the time of the day.|[K]|INT16|-203.15-353.15|1/100|273.15|
|MAX|Maximum of Land Surface Temperature observed during the 10-days period, regardless the time of the day.|[K]|INT16|-203.15-353.15|1/100|273.15|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/bio-geophysical-parameters/temperature-and-reflectance/land-surface-temperature/lst-tci_global_3km_10daily_v3)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/BatchV2.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
