---
title: "Copernicus Emergency Management Service (CEMS)"
aliases: 
  - /Data/CEMS.html
  - /Data/ComplementaryData/CEMS.html
format:
  html:
    code-fold: true
execute:
  echo: false
  output: asis
jupyter: python3
image: https://eu-copernicus.github.io/copernicus-component-library/ccl-assets/images/ccl-icon-emergency.svg
---

```{python}
#| tags: [parameters]

constellation = "CEMS"

```

The **Copernicus Emergency Management Service** (Copernicus EMS, CEMS) provides all actors involved in the management of natural disasters, man-made emergency situations, and humanitarian crises with timely and accurate geo-spatial information derived from satellite remote sensing and completed by available in situ or open data sources.

The service is provided free of charge to all users either in rush mode, for emergency management activities which require immediate response and/or non-rush mode, to support emergency disaster management activities not related to immediate response, analysing pre-disaster risk assessment and population and asset vulnerability or post-disaster recovery and reconstruction. It can be activated only by designated authorised users.

More information on the service is available on the [Copernicus EMS – Mapping Portal](https://emergency.copernicus.eu/). The public portal of the Copernicus Emergency Management Service allows to download all the maps and products delivered by this service. A User Guide for the EMS Service has been produced and is available [here](https://www.copernicus.eu/en/new-copernicus-emergency-management-user-guide).

## Service components

CEMS consists of two main components: a mapping component and an early warning component.

The **mapping component** (Copernicus EMS – Mapping) has worldwide coverage and provides the above-mentioned actors (mainly Civil Protection Authorities and Humanitarian Aid Agencies) with maps based on satellite imagery. The service has been fully operational since 1 April 2012, and is implemented by the European Commission DG Joint Research Centre (JRC).

Products can be used as supplied (e.g. as digital or printed map outputs), or combined with other data sources as digital feature sets in a geographic information system (GIS) to support geospatial analysis and decision-making. Copernicus EMS – Mapping supports all phases of the emergency management cycle:

* preparedness
* prevention
* disaster risk reduction
* emergency response and recovery.

The **early warning component** of the Copernicus EMS consists of three different systems dedicated monitoring systems, each complemented by a global-level extension:

* [**European Flood Awareness System(EFAS)**](https://www.copernicus.eu/en/european-flood-awareness-system) - provides overviews on ongoing and forecasted floods across Europe up to 10 days in advance. Extended globally by the [**Global Flood Awareness System (GloFAS)**](https://global-flood.emergency.copernicus.eu/react/). 
* [**European Forest Fire Information System (EFFIS)**](https://www.copernicus.eu/en/european-forest-fire-information-system) - provides near real-time and historical information on forest fires and forest fire regimes in the European, Middle Eastern, and North African regions. Extended globally by the [**Global Wildfire Information System (GWIS)**](https://gwis.jrc.ec.europa.eu/). 
* [**European Drought Observatory (EDO)**](https://www.copernicus.eu/en/european-drought-observatory) - provides drought-relevant information and early-warnings for Europe. Extended globally by the [**Global Drought Observatory (GDO)**](https://drought.emergency.copernicus.eu/tumbo/gdo/map/?id=2001). 

{{< include ../_render_collections.qmd >}}

