# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: check-toml
  - repo: https://github.com/gdubicki/pre-commit-pngquant
    # For pngquant see: https://pngquant.org
    rev: 9010345cf034fe1097b3b7bb9ecd5ea92dcf85dc # Use the sha / tag you want to point at
    hooks:
      - id: pngquant
        args: [--speed=1]
