---
title: "APIs"
listing: 
  - id: CatalogAPIs
    contents:
        - APIs/STAC.qmd
        - APIs/OData.qmd
        - APIs/OpenSearch.qmd
    type: grid
    fields: [title, description]
  - id: StreamlinedDataAccess
    contents: 
        - APIs/SentinelHub.qmd
        - APIs/openEO/openEO.qmd
    type: grid
    fields: [title, description]
  - id: AdditionalAPIs
    contents: 
        - APIs/S3.qmd
        - APIs/Traceability.qmd
        - APIs/On-Demand%20Production%20API.qmd
    type: grid
    fields: [title, description]
---


This section gives an overview on the APIs provided by Copernicus Data Space Ecosystem.

::: {#Sentinelhub_data}
:::

## Catalog APIs
There are various interfaces providing capability to search the catalog, to serve various users'
needs and to ensure continuity over the existing Copernicus Hubs. All interfaces are connected to
the same database to guarantee consistency.

::: {#CatalogAPIs}
:::

##### Catalog APIs news
This section provides detailed information about upcoming changes and the changelog of the implemented updates. The releases include all Catalog APIs interfaces. To avoid disruption to your scripts or apps, we recommend reviewing the upcoming changes and the latest release notes described below:

###### 1.[ Upcoming Changes ](APIs/Others/UpcomingChanges.qmd)
We've put together a list of potential updates related to Catalog APIs as of September 2023. You can find a detailed comparison of these changes [here](APIs/Others/UpcomingChanges.qmd).

###### 2. [Release notes](APIs/Others/ReleaseNotes.qmd)
The [release notes document](APIs/Others/ReleaseNotes.qmd) provides you with a comprehensive list of modifications made to the Catalog APIs for every release.

## Streamlined data access

The Streamlined Data Access APIs (SDA) enables users to access and retrieve Earth observation (EO) data from the Copernicus Data Space Ecosystem catalogue. These APIs also provide you with a set of tools and services to support data processing and analysiss. 

::: {#StreamlinedDataAccess}
:::


## Additionally 

Additional in Copernicus Data Space Ecosystem, we provide you with the S3 API, Traceability API and On-Demand Production API.
The S3 API is one of the main access methods for EO data. Whereas, the Traceability API allows you to verify and register traces for user level data available in the Copernicus Data Space. Similarly, the On-Demand Production API provides you with on-demand processing capability for CARD-BS, CARD-COH6/12.

::: {#AdditionalAPIs}
:::

