---
title: "Data"
---

This section provides an overview of the EO data available from Copernicus Data Space Ecosystem.

The data offer will gradually extend starting from January 2023 

For the latest information about available satellite data, users and stakeholders can follow them in [Copernicus Sentinel Operations Dashboard](Data/Dashboard.qmd).  

## Copernicus Sentinel Mission
### [Sentinel 1](/Data/Sentinel1.qmd)

The [Sentinel-1 radar imaging mission](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-1){target="_blank"} is composed of a constellation of two polar-orbiting satellites providing continous all-weather, day and night imagery for Land and Maritime Monitoring. C-band synthentic aperture radar imaging has the advantage of operating at wavelenghts that are not obstructed by clouds or .....[load more](/Data/Sentinel1.qmd)

### [Sentinel 2](/Data/Sentinel2.qmd) 

The [Copernicus Sentinel-2 mission](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-2){target="_blank"} comprises a land monitoring constellation of two polar-orbiting satellites placed in the same sun-synchronous orbit, phased at 180° to each other. It aims at monitoring variability in land surface conditions, and its wide swath width (290 km) and .....[load more](/Data/Sentinel2.qmd) 

### [Sentinel 3](/Data/Sentinel3.qmd)

The main objective of the[Copernicus Sentinel-3 mission](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3){target="_blank"} is to measure ocean and land surface colour, sea and land surface temperature, and sea surface topography with high accuracy and reliability to.....[load more](/Data/Sentinel3.qmd)

### [Sentinel 5P](/Data/Sentinel5P.qmd)

The [Copernicus Sentinel-5 Precursor](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-5p){target="_blank"} mission is the first Copernicus mission dedicated to monitoring our atmosphere. The main objective of the Copernicus Sentinel-5P mission is to.....[load more](/Data/Sentinel5P.qmd)

### [Sentinel 6](/Data/Sentinel6.qmd)

Copernicus [Sentinel-6](https://sentinels.copernicus.eu/ca/web/sentinel/missions/sentinel-6/overview){target="_blank"} Michael Freilich includes two satellites that will fly sequentially, launched in 2020 and 2025, carrying a state-of-the art optimised payload......[load more](/Data/Sentinel6.qmd)




## Complementary data
### [Soil Moisture and Ocean Salinity (SMOS)](/Data/SMOS.qmd)

The Soil Moisture and Ocean Salinity (SMOS) mission was launched on 2 November 2009. It is one of the European Space Agency's Earth Explorer missions, which form the science and research element of ESA’s Living Planet Programme. The SMOS payload consists of.....[load more](/Data/SMOS.qmd)

### [ENVISAT- Medium Resolution Imaging Spectrometer (MERIS)](/Data/MERIS.qmd) 

The Medium Resolution Imaging Spectrometer (MERIS) was a programmable spectrometer on board the Envisat mission, operating in the solar reflective spectral range. Although primarily dedicated to ocean colour observations, MERIS broadened its scope of objectives to atmospheric and land surface related studies. MERIS had a high spectral and radiometric resolution and a dual spatial resolution, within a global mission covering open ocean and coastal zone waters and a regional mission covering land surfaces.[Load more](/Data/MERIS.qmd)

### [Landsat-5](/Data/Landsat5.qmd)

The Landsat programme is a joint USGS and NASA-led enterprise for Earth observation that represents the world's longest running system of satellites for moderate-resolution optical remote sensing for land, coastal areas and shallow waters......[load more](/Data/Landsat5.qmd)

### [Landsat-7](/Data/Landsat7.qmd)

The Landsat programme is a joint USGS and NASA-led enterprise for Earth observation that represents the world's longest running system of satellites for moderate-resolution optical remote sensing for land, coastal areas and shallow waters. Landsat-7 has continued......[load more](/Data/Landsat7.qmd)

### [Landsat-8](/Data/Landsat8.qmd)

The Landsat programme is a joint USGS and NASA-led enterprise for Earth observation that represents the world's longest running system of satellites for moderate-resolution optical remote sensing for land, coastal areas and shallow waters. Landsat-8 carries......[load more](/Data/Landsat8.qmd)

### [Copernicus Atmosphere Monitoring Service (CAMS)](/Data/CAMS.qmd)

The Copernicus Atmosphere Monitoring Service (CAMS) is a service implemented by the European Centre for Medium-Range Weather Forecasts (ECMWF) which provides continuous, open, free, regular data and information on atmospheric composition. CAMS describes......[load more](/Data/CAMS.qmd)

### [Copernicus Emergency Management Service (CEMS)](/Data/CEMS.qmd)

The Copernicus Emergency Management Service (CEMS) provides geospatial data and images for informed decision making in order to support all involved in the management of natural or manmade disasters. CEMS constantly monitors Europe and the globe for signals of an impending disaster or evidence of one happening in real time. Products of CEMS are generated using remote sensing, satellite, in-situ (non-space) and modelled data.[Load more](/Data/CEMS.qmd)

### [Copernicus Land Monitoring Service (CLMS)](/Data/CLMS.qmd)

Copernicus program priorities are to gain from Earth Observation techniques and make research, administration, agriculture, economy, environmental protection of our lands easier, cheaper and more effective. Copernicus Land Monitoring Service (CLMS) constitute rich data hub with archival and near real......[load more](/Data/CLMS.qmd)

### [Copernicus Marine Service (CMEMS)](/Data/CMEMS.qmd)

The Copernicus Marine Environment Monitoring Service (CMEMS) provides open, free, regular and systematic reference data on the blue (physical), white (sea ice), and green (biogeochemical) state of the marine environment, as well as data on variability and dynamics across the global ocean and European seas.......[load more](/Data/CMEMS.qmd)

### [Additional Complementary Data](/Data/Additional.qmd)

Copernicus Data Space Ecosystem provides data that are not associated with any of the Copernicus Services or are generated by third parties. These datasets include Sentinel-1 related products such as RTC (Radiometrically Terrain Corrected), CARD-BS (Terrain-Corrected Backscatter), Orbits; Sentinel-2 based global mosaics; land cover.......[load more](/Data/Additional.qmd)

<!---
 ### [VHR Commercial Data](/Data/VHR.qmd)
 
Commercial data give users access to a wide range of very high-resolution satellite data. Diversified
sources of archival or new products ordered according to customer's tasks, provide the possibility
to choose an appropriate product for every project where VHR imaging is crucial. Depending on
the source, VHR imagery varies by product type - it can be optical or radar data.[Load more](/Data/VHR.qmd) 
--->
 

<!-- <span style="opacity:0.30">
Cloudless Mosaic

Copernicus Contributing Mission 

## Sentinel engineering data

Copernicus DEM 

Mapzen DEM 

SRTM GL1 


## Sentinel auxiliary data


CAMS 

CEMS

CLMS

CMEMS 


## Copernicus contributing missions
---

## Complementary Open data
---
## Commercial data -->
</style>