---
title : "Frequently Asked Questions"
---

## General

<details id="in-comparison-to-the-existing-legacy-copernicus-data-hub-what-will-be-the-free-services-other-than-stac-cog">
    <summary onclick="handleQuestionClick('in-comparison-to-the-existing-legacy-copernicus-data-hub-what-will-be-the-free-services-other-than-stac-cog')">In comparison to the existing legacy Copernicus Data Hub, what will be the free services other than stac/cog?</summary>
    <p>Compared to the previously existed Copernicus Data Hub, there will be additional APIs - OGC interfaces (WMS, WMTS, WCS), OpenEO, Sentinel Hub API, S3, and others. Please refer to the <a href="Roadmap.md">Roadmap</a> for more information on the timing of these interfaces.</p>
</details>

<details id="is-there-an-end-user-document-that-describes-specific-data-products-and-specific-services-that-are-available">
    <summary onclick="handleQuestionClick('is-there-an-end-user-document-that-describes-specific-data-products-and-specific-services-that-are-available')">Is there an end user document that describes specific data products and specific services that are available?</summary>
    <p>The user level details for every service and dataset will be provided in this documentation. In accordance with each and every service and dataset embedded into the ecosystem, this documentation will be updated.</p>
</details>

<details id="how-long-is-the-project-timescale-in-total">
    <summary onclick="handleQuestionClick('how-long-is-the-project-timescale-in-total')">How long is the project timescale in total?</summary>
    <p>The time scale of the project is 6 years starting from late 2022 (i.e. to the end of 2028) with an optional extension up to 4 years (i.e. 2032).</p>
</details>

<details id="can-anyone-outside-from-Europe-have-free-access-to-any-data">
    <summary onclick="handleQuestionClick('can-anyone-outside-from-Europe-have-free-access-to-any-data')">Can anyone outside from Europe have free access to any data?</summary>
    <p>Yes, data and services will be available to users worldwide and according to the EU Policy. You can visit <a href="https://dataspace.copernicus.eu/terms-and-conditions" target="_blank">Terms and Conditions</a> for more information.</p>
</details>

<details id="is-there-any-difference-between-EU-users-and-non-EU-users">
    <summary onclick="handleQuestionClick('is-there-any-difference-between-EU-users-and-non-EU-users')">Is there any difference between EU users and non-EU users?</summary>
    <p>There is no difference between EU users and non-EU users. That said, there will be a continuity of the accounts with higher throughput, managed by ESA (i.e. Copernicus Services, International Partners, etc.).</p>
</details>

<details id="which-users-are-qualified-for-higher-tier-accounts">
    <summary onclick="handleQuestionClick('which-users-are-qualified-for-higher-tier-accounts')">Which users are qualified for higher tier accounts?</summary>
    There are three types of higher tier accounts:
        <ul>
            <li>Copernicus Services - this account type is meant for European Union institutions and bodies. Organisations working on Copernicus Services are as well included in this tier.</li> 
            <li>Copernicus Collaborative Users - organisations from Copernicus Participating States with an agreement with ESA and European Commission.</li> 
            <li>Copernicus International Users - international partners with an agreement with ESA and European Commission.</li> 
        </ul>
    If your organisation fits the above-mentioned profile, do <a href="https://dataspace.copernicus.eu/copernicus-services-user">submit a request</a> for an account upgrade. If you are not sure about it, do <a href="https://dataspace.copernicus.eu/copernicus-services-user">submit a request</a> anyway and it will be evaluated.
    Please note that Copernicus Data Space Ecosystem monitoring requirements include reporting of aggregated consumption on account level, shared within project stakeholder group. 
    We would also suggest you check the following content:
        <ul>
            <li><a href="https://documentation.dataspace.copernicus.eu/Quotas.html">Information about quotas</a> for specific services</li> 
            <li>The <a href="https://dataspace.copernicus.eu/ecosystem/services">Ecosystem developers</a>, where users can get access to extended quotas under commercial terms.</li> 
      </ul>
</details>

## Data

<details id="what-data-will-be-offered-online-and-what-is-the-timeline-for-the-following-months">
    <summary onclick="handleQuestionClick('what-data-will-be-offered-online-and-what-is-the-timeline-for-the-following-months')">What data will be offered online and what is the timeline for the following months?</summary>
    <p>For the details on the data offer and timing, please refer to the <a href="Roadmap.md">Roadmap</a></p>
</details>

<details id="is-there-a-page-that-indicates-anomalies-with-the-datasets">
    <summary onclick="handleQuestionClick('is-there-a-page-that-indicates-anomalies-with-the-datasets')">Is there a page that indicates anomalies with the datasets?</summary>
    <p>The <a href="https://operations.dashboard.copernicus.eu/index" target="_blank">Copernicus Sentinel Operations Dashboard</a> provides details of events over the past three months that have impact on the completeness of the data production, such as planned calibration activities, manoeuvres, or anomalies. The information of which data is affected is included.</p>
</details>

<details id="with-regard-to-cloud-native-formats-interfaces-will-the-data-also-be-available-in-the-original-data-formats-e-g-for-data-downloading">
    <summary onclick="handleQuestionClick('with-regard-to-cloud-native-formats-interfaces-will-the-data-also-be-available-in-the-original-data-formats-e-g-for-data-downloading')">With regard to cloud native formats/interfaces, will the data also be available in the original data formats (e.g. for data downloading)?</summary>
    <p>Yes, data will also be available in original data formats (i.e. .SAFE).</p>
</details>

<details id="will-data-such-as-sentinel-2-be-processed-to-a-consistent-version">
    <summary onclick="handleQuestionClick('will-data-such-as-sentinel-2-be-processed-to-a-consistent-version')">Will data, such as Sentinel-2, be processed to a consistent version?</summary>
    <p>The Sentinel-2 data will be available at the latest processing baseline. And with the reprocessing of Sentinel-2 happening in parallel (out of scope of this project), these will become available on this service as well. For more information on Sentinel-2 reprocessing campaign, please follow <a href="https://sentinels.copernicus.eu/web/sentinel/technical-guides/sentinel-2-msi/copernicus-sentinel-2-collection-1-availability-status" target="_blank">Copernicus SENTINEL-2 Collection-1 Availability Status</a></p>
</details>

<details id="is-it-possible-to-download-a-subset-of-data-corresponding-to-an-AOI-instead-of-the-whole-image">
    <summary onclick="handleQuestionClick('is-it-possible-to-download-a-subset-of-data-corresponding-to-an-AOI-instead-of-the-whole-image')">Is it possible to download a subset of data corresponding to an AOI, instead of the whole image?</summary>
    <p>Yes, it is possible to download a subset of data, by using the dedicated APIs, i.e. Sentinel Hub, OpenEO.</p>
</details>

<details id="are-there-data-offered-in-the-cloud-optimized-geotiffs-cog-format">
    <summary onclick="handleQuestionClick('are-there-data-offered-in-the-cloud-optimized-geotiffs-cog-format')">Are there data offered in the Cloud Optimized Geotiffs (COG) format?</summary>
    <p>Yes, Sentinel-1 GRD Level 1 data will be available in COG format.</p>
</details>

<details id="when-online-data-is-mentioned-does-that-mean-the-data-are-not-on-tape">
    <summary onclick="handleQuestionClick('when-online-data-is-mentioned-does-that-mean-the-data-are-not-on-tape')">When Online data is mentioned, does that mean the data are not on tape?</summary>
    <p>The Online data (or Immediate Access Data (IAD)) are not on the tapes. Online data is the type of data where in its metadata it reads "Online": true. These data can be downloaded directly from the Copernicus Data Space Ecosystem. On the other hand, Offline data ("Online": false or Deferred Available Data(DAD)) first needs to be ordered via the <a href="https://dataspace.copernicus.eu/analyse/data-workspace" target="_blank">Data Workspace</a> and only after that step, it can be downloaded.</p>
</details>

<details id="can-we-download-the-data-acquired-by-all-sentinel-missions-1-2-3-5P-6-and-the-other-satellites-e-g-meteosat-via-the-new-interface-considering-some-missions-are-not-managed-by-esa-but-by-eumetsat-for-example">
    <summary onclick="handleQuestionClick('can-we-download-the-data-acquired-by-all-sentinel-missions-1-2-3-5P-6-and-the-other-satellites-e-g-meteosat-via-the-new-interface-considering-some-missions-are-not-managed-by-esa-but-by-eumetsat-for-example')">Can we download the data acquired by all Sentinel missions (1, 2, 3, 5P, 6) and the other satellites (e.g. Meteosat) via the new interface? Considering some missions are not managed by ESA, but by EUMETSAT for example.</summary>
    <p>The <a href="https://documentation.dataspace.copernicus.eu/Roadmap/DataTable.html">Data Roadmap</a> shows how the Copernicus Data Space Ecosystem will be continously enhanced in terms of available data.</p>
</details>

<details id="will-the-new-interface-offer-eo-ready-to-use-products-or-just-l0-and-l1-data">
    <summary onclick="handleQuestionClick('will-the-new-interface-offer-eo-ready-to-use-products-or-just-l0-and-l1-data')">Will the new interface offer EO ready-to-use products or just L0 and L1 data?</summary>
    <p>Up to L3 products will be available. Please see the <a href="Roadmap.md">Roadmap</a> and the <a href="Data.qmd">Data</a> section.</p>
</details>

<details id="what-is-the-highest-resolution-sar-data-available-in-copernicus-data-space-ecosystem">
    <summary onclick="handleQuestionClick('what-is-the-highest-resolution-sar-data-available-in-copernicus-data-space-ecosystem')">What is the highest resolution SAR data available in Copernicus Data Space Ecosystem?</summary>
    <p>The Sentinel-1 SAR achieves a spatial resolution of approximately 5 by 20 m. More information can be found <a href="https://sentinel.esa.int/web/sentinel/user-guides/sentinel-1-sar/resolutions" target="_blank">here</a>.</p>
</details>

<details id="is-it-possible-to-acquire-compressed-data">
    <summary onclick="handleQuestionClick('is-it-possible-to-acquire-compressed-data')">Is it possible to acquire compressed data?</summary>
    <p>Copernicus Data Space Ecosystem provides access to EO data in zip format without compression(i.e. zero compression applied).</p>
</details>

## Services

<details id="are-the-free-offering-and-commercial-offering-integrated-to-facilitate-the-transfer-of-the-users-from-free-to-commercial">
    <summary onclick="handleQuestionClick('are-the-free-offering-and-commercial-offering-integrated-to-facilitate-the-transfer-of-the-users-from-free-to-commercial')">Are the free offering and commercial offering integrated to facilitate the transfer of the users from free to commercial?</summary>
    <p>Yes, there will be a common user identity, which will allow registered users to seamlessly transfer between two mentioned systems.</p>
</details>

<details id="when-we-develop-an-eo-ready-to-use-product-could-we-integrate-it-into-the-interface-and-ask-the-payment-from-clients">
    <summary onclick="handleQuestionClick('when-we-develop-an-eo-ready-to-use-product-could-we-integrate-it-into-the-interface-and-ask-the-payment-from-clients')">When we develop an EO ready-to-use product, could we integrate it into the interface and ask the payment from clients?</summary>
    <p>Yes, commercial services can be built on top, similar to the Copernicus Open Licence.</p>
</details>

<details id="can-users-come-with-wish-list-on-services">
    <summary onclick="handleQuestionClick('can-users-come-with-wish-list-on-services')">Can users come with wish-list on services?</summary>
    <p>Yes, users can come up with suggestions to improve or expand the service portfolio. Users can post their improvement suggestions to <a href="https://forum.dataspace.copernicus.eu/">Community Forum</a> for further evaluation.</p>
</details>

<details id="is-there-any-limitation-on-the-maximum-number-of-downloads-at-a-time">
    <summary onclick="handleQuestionClick('is-there-any-limitation-on-the-maximum-number-of-downloads-at-a-time')">Is there any limitation on the maximum number of downloads at a time?</summary>
    <p>Yes, there will be quotas and limitations for different user types. For example, the number of concurrent connections limit for the Copernicus General user type is 4, whereas for the Copernicus Services type, it is 20. Please refer to the <a href="Quotas.qmd">Quotas and Limitations</a> section of our documentation for more information regarding quotas and limitations apply to the Copernicus General user type.</p>
</details>

<details id="is-it-possible-to-download-sentinel-2-data-for-a-large-area-at-a-high-resolution-in-the-copernicus-browser">
    <summary onclick="handleQuestionClick('is-it-possible-to-download-sentinel-2-data-for-a-large-area-at-a-high-resolution-in-the-copernicus-browser')">Is it possible to download Sentinel-2 data for a large area at a high resolution in the Copernicus Browser?</summary>
    <p>Depending on your use, we suggest to use the high-res print (via the high-res print tab) where you will get large areas in a high resolution (the data is though not georeferenced). If you need georeferenced data, split your area in several smaller images that you download or choose a bit lower resolution to stay within the limits of 2500px.</p>
</details>

<details id="where-can-I-find-more-information-regarding-the-quotas-and-limits-for-accessing-data-and-using-the-services-through-your-platform">
    <summary onclick="handleQuestionClick('where-can-I-find-more-information-regarding-the-quotas-and-limits-for-accessing-data-and-using-the-services-through-your-platform')">Where can I find more information regarding the quotas and limits for accessing data and using the services through your platform?</summary>
    <p>Please refer to the <a href="Quotas.qmd">Quotas and Limitations</a> section of our documentation for more information.</p>
</details>

<details id="which-entities-are-qualified-to-get-higher-quotas-in-scope-of-copernicus-services-group-and-how-can-one-ask-for-it">
    <summary onclick="handleQuestionClick('which-entities-are-qualified-to-get-higher-quotas-in-scope-of-copernicus-services-group-and-how-can-one-ask-for-it')">Which entities are qualified to get higher quotas in scope of "Copernicus Services" group and how can one ask for it?</summary>
    The following users and initiatives are qualified for the increased quota:<br>
    <ul>
        <li>Institutions and organisations developing or operating <a href="https://www.copernicus.eu/en/copernicus-services">Copernicus Services</a></li>
        <li>European institutions and Bodies set up under the EU Treaties.</li>
    </ul>
    Each institution or project can have several individuals' user accounts, which belong to the same organisation and share the account's quota (i.e. if one of the organisation users will consume full monthly project quota, the rest will not be able to use it further either). Project owners will be able to add further users to this organisation themselves.
    Organisations can choose the account type based on their preference, i.e. download-optimised or processing-optimized
      <ul>
        <li>Download</li> 
        <li>Processing - small</li> 
        <li>Processing - medium</li> 
        <li>Processing - large</li>
      </ul>
    In order to request for increased quota, <a href="https://dataspace.copernicus.eu/copernicus-services-user">fill out this form </a>and provide the following information:
      <ul>
        <li>account's e-mail (you have to <a href="https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/auth?client_id=cdse-public&response_type=code&scope=openid&redirect_uri=https%3A//dataspace.copernicus.eu/account/confirmed/1">register</a> before submitting this request, do use your organisation's e-mail domain)</li> 
        <li>organisation name (including department, if relevant)</li> 
        <li>project name (i.e. Copernicus Services contract reference, project reference, etc.)</li> 
        <li>project start date</li>
        <li>planned project end date</li>
        <li>institutional contact (i.e. contract officer at European Commission)</li>
        <li>preferred type of the account ("Download", "Processing-small”, “Processing-medium", "Processing-large")</li>
        <li>notes</li>
      </ul>
    Please note that Copernicus Data Space Ecosystem monitoring requirements include reporting of aggregated consumption on account level, shared within project stakeholder group.
</details>

## Registration and authentication

<details id="im-having-troubles-with-registering-what-can-I-do">
    <summary onclick="handleQuestionClick('im-having-troubles-with-registering-what-can-I-do')">I'm having troubles with registering, what can I do?</summary>
    <p>If you are having troubles with Recaptcha or receiving the initial confirmation email while registering, please send an e-mail to <a href="mailto:help-login@dataspace.copernicus.eu">help-login@dataspace.copernicus.eu</a> for direct support.</p>
</details>

<details id="im-having-problems-when-I-try-to-login-or-submit-a-request-in-the-help-center-how-can-I-solve-it">
    <summary onclick="handleQuestionClick('im-having-problems-when-I-try-to-login-or-submit-a-request-in-the-help-center-how-can-I-solve-it')">I'm having problems when I try to login or submit a request in the Help Center. How can I solve it?</summary>
    <p>This may be due to your browser settings. Please make sure Enhanced Tracking Protection is turned off and in the Privacy&Security section of your browser, make sure the option Standard (not Strict) is selected. If these doesn't solve your issue. please contact our support team via <a href= "https://helpcenter.dataspace.copernicus.eu/hc/en-gb/requests/new" target="_blank">Submit a request</a>.</p>
</details>

## APIs

<details id="where-can-I-find-detailed-information-regarding-the-duration-of-access-tokens-and-refresh-tokens">
    <summary onclick="handleQuestionClick('where-can-I-find-detailed-information-regarding-the-duration-of-access-tokens-and-refresh-tokens')">Where can I find detailed information regarding the duration of Access tokens and Refresh tokens?</summary>
    <p>The access token is valid for 10 minutes, after 10 minutes, it expires. When Access Token expires, it must <br>
        -either be refreshed by using the Refresh Token,<br>
        -or be re-generated.<br>
        The refresh token is valid for 60 minutes and can be used multiple times within that 60 minutes. The returned access token is again valid for 10 mins.<br>
        Please refer to the <a href="Quotas.qmd">Quotas and Limitations</a> section of our documentation for more information.<br>
        Also please refer to the  <a href="https://documentation.dataspace.copernicus.eu/APIs/OData.html">OData</a> section of our documentation for more information on Access and Refresh Tokens.<br></p>
</details>

<details id="will-long-term-zrchive-lta-process-be-discontinued-when-all-archived-data-become-online">
    <summary onclick="handleQuestionClick('will-long-term-zrchive-lta-process-be-discontinued-when-all-archived-data-become-online')">Will Long Term Archive (LTA) process be discontinued when all archived data become Online?</summary>
    <p>There will still be services available for so called “deferred data access” :  data collections that are not commonly used. That said, all of the most relevant collections will be available Online. The <a href="Roadmap.md">Roadmap</a> shows how the Copernicus Data Space Ecosystem will be continously upgraded and how more data become available.</p>
</details>

<details id="will-the-platform-use-stac-standards">
    <summary onclick="handleQuestionClick('will-the-platform-use-stac-standards')">Will the platform use STAC standards?</summary>
    <p>Yes, <a href= "https://documentation.dataspace.copernicus.eu/APIs/STAC.html" target="_blank">STAC Product Catalog</a> is already available. However there may be issues with using the current version with generic STAC libraries. Our dedicated teams are actively working on its development to ensure a seamless experience for all users. Nevertheless it already supports basic product search.</p>
</details>

<details id="any-plan-to-offer-the-pangeo-platform-for-a-pythonist">
    <summary onclick="handleQuestionClick('any-plan-to-offer-the-pangeo-platform-for-a-pythonist')">Any plan to offer the Pangeo platform for a "pythonist"?</summary>
    <p>This is currently not in the offer or roadmap.</p>
</details>

<details id="which-one-amongst-the-4-catalog-apis-odata-stac-opensearch-sentinel-hub-catalogue-is-updated-first-when-new-products-are-published">
    <summary onclick="handleQuestionClick('which-one-amongst-the-4-catalog-apis-odata-stac-opensearch-sentinel-hub-catalogue-is-updated-first-when-new-products-are-published')">Which one amongst the 4 catalog APIs (OData, STAC, OpenSearch, Sentinel Hub catalogue) is updated first when new products are published?</summary>
    <p>OpenSearch, OData and STAC catalog APIs all use the same backend database. Sentinel Hub catalog API contains a subset of the collections, hence it works only for the ones that have been imported to Sentinel Hub. Therefore there is no first updated one.</p>
</details>

<details id="what-is-the-limitation-of-the-number-of-requests-that-i-can-do-at-the-time">
    <summary onclick="handleQuestionClick('what-is-the-limitation-of-the-number-of-requests-that-i-can-do-at-the-time')">What is the limitation of the number of requests that I can do at the time?</summary>
    <p>For concurrent requests and other limitations please refer to the <a href="Quotas.qmd">Quotas and Limitations</a> section of our documentation for more information as the limits are different for each user type.</p>
</details>

<details id="do-you-have-to-authenticate-for-requesting-through-opensearch-api">
    <summary onclick="handleQuestionClick('do-you-have-to-authenticate-for-requesting-through-opensearch-api')">Do you have to authenticate for requesting through OpenSearch API?</summary>
    <p>There's no need to use any user or authentication when you want to search. User authentication is required for downloading products.</p>
</details>

<details id="can-we-use-the-sentinel-Hub-bucket-and-fetch-the-products-based-on-the-id-we-obtained-from-openSearch-api">
    <summary onclick="handleQuestionClick('can-we-use-the-sentinel-Hub-bucket-and-fetch-the-products-based-on-the-id-we-obtained-from-openSearch-api')">Can we use the Sentinel Hub bucket and fetch the products based on the id we obtained from OpenSearch API?</summary>
    <p>Yes, you can use Sentinel Hub bucket in addition to some programming tools by providing product ID obtained by using OpenSearch API or OData of the Copernicus Data Space Ecosystem.</p>
</details>


<details id="message-this-request-was-rejected-due-to-a-violation">
    <summary onclick="handleQuestionClick('message-this-request-was-rejected-due-to-a-violation')">Message:"This request was rejected due to a violation"</summary>
    <p>When implementing UDF in openEO that fetch files within it from a different source, an error is encountered.  <br>*Failed to parse API error response: [403] '{"status":"error","data":{"message":"This request was rejected due to a violation. Please consult with your administrator, and provide this reference ID: 12308030347893165864"}}'*  <br>Please contact our support team via <a href= "https://helpcenter.dataspace.copernicus.eu/hc/en-gb/requests/new" target="_blank">Submit a request</a>. Make sure to provide the reference ID from the error message.</p>
</details>

### S3 API

<details id="is-a-stac-catalog-planned-will-the-data-be-accessible-on-cloud-object-storage-s3">
    <summary onclick="handleQuestionClick('is-a-stac-catalog-planned-will-the-data-be-accessible-on-cloud-object-storage-s3')">Is a STAC catalog planned ? Will the data be accessible on cloud object storage (S3)?</summary>
    <p>STAC Catalog API is indeed planned. The data is already available over S3 as well.</p>
</details>

<details id="how-do-I-generate-s3-access-and-secret-keys">
    <summary onclick="handleQuestionClick('how-do-I-generate-s3-access-and-secret-keys')">How do I generate S3 access and secret keys?</summary>
    <p>Please refer to the <a href= "https://documentation.dataspace.copernicus.eu/APIs/S3.html" target="_blank">Access to EO Data via S3</a> page for the guidance on generating S3 access and secret keys.</p>
</details>

<details id="can-i-connect-directly-to-the-s3-bucket-using-aws-s3-commands-with-the-s3-keys-provided-or-do-i-have-to-use-s3cmd-to-download-images">
    <summary onclick="handleQuestionClick('can-i-connect-directly-to-the-s3-bucket-using-aws-s3-commands-with-the-s3-keys-provided-or-do-i-have-to-use-s3cmd-to-download-images')">Can I connect directly to the S3 bucket using AWS S3 commands with the S3 keys provided or do I have to use "s3cmd" to download images?</summary>
    <p>Yes, you can connect to S3 bucket using AWS S3 connection. However some functionality may not be supported. It is recommended to use the 's3cmd' command to download products.</p>
</details>

<details id="what-is-the-benefit-of-fetching-imagery-from-copernicus-dataspace-s3-bucket">
    <summary onclick="handleQuestionClick('what-is-the-benefit-of-fetching-imagery-from-copernicus-dataspace-s3-bucket')">What is the benefit of fetching imagery from Copernicus Data Space S3 bucket?</summary>
    <p>Downloading products via S3 is faster as it delivers products as a .zip archive, skipping the need of zipper.</p>
</details>

<details id="on-which-region-resides-the-copernicus-dataspace-s3-bucket">
    <summary onclick="handleQuestionClick('on-which-region-resides-the-copernicus-dataspace-s3-bucket')">On which region resides the Copernicus Data Space S3 bucket?</summary>
    <p>The repo is located in Warsaw/Poland.</p>
</details>

<details id="how-can-I-search-for-the-product-in-s3-bucket">
    <summary onclick="handleQuestionClick('how-can-I-search-for-the-product-in-s3-bucket')">How can I search for the product in S3 bucket?</summary>
    <p>Searching via ID or product name in the OpenSearch or OData will give the S3 path to the product in response.</p>
</details>



## Documentation

<details id="which-distribution-channels-will-be-available-for-high-throughput-data-access-does-the-public-side-have-user-tiers-or-is-high-throughput-data-transfer-such-as-eodata">
    <summary onclick="handleQuestionClick('which-distribution-channels-will-be-available-for-high-throughput-data-access-does-the-public-side-have-user-tiers-or-is-high-throughput-data-transfer-such-as-eodata')"><p>Which distribution channels will be available for high-throughput data access? Does the public side have user tiers, or is high-throughput data transfer (such as <a href="https://creodias.eu/remote-transfer-for-eodata" target="_black" >EODATA</a> ) only a paid service?</p></summary>
    <p>All distribution options (i.e. OData, S3, Sentinel Hub,..) will be constrained with user quotas, which includes both bandwidth limitation, as well as monthly data transfer limits. Please refer to the <a href="Quotas.qmd">Quotas and Limitations</a> section of our documentation for more information.</p>
</details>

<details id=where-can-I-find-more-information-regarding-the-cost-of-the-extra-services">
    <summary onclick="handleQuestionClick('where-can-I-find-more-information-regarding-the-cost-of-the-extra-services')">Where can I find more information regarding the cost of the “extra” services?</summary>
    <p>Pricing will be published soon.</p>
</details>

<details id="december-advertisement-of-the-copernicus-data-space-ecosystem">
    <summary onclick="handleQuestionClick('december-advertisement-of-the-copernicus-data-space-ecosystem')">It is indicated that “For those interested in processing, there will be scalable cloud resources available, optimized for EO tasks”. Does this refer to the current CreoDIAS resources, or something completely new that hasn’t been addressed yet?</summary>
    <p><a href="https://medium.com/sentinel-hub/new-copernicus-data-access-service-to-support-the-ecosystem-for-earth-observation-412f829355a3 " target="_blank">This December advertisement of the Copernicus Data Space Ecosystem</a> indicates that scalable cloud resources will be part of the commercial offering and can be obtained at <a href = "https://creodias.eu/">CREODIAS</a> in first instance. ICT-wise, there will be two options, including Open Telekom Cloud.</p>
</details>

<details id="are-there-tutorials-online-physical-meetings-to-use-the-new-interface">
    <summary onclick="handleQuestionClick('are-there-tutorials-online-physical-meetings-to-use-the-new-interface')">Are there tutorials (online & physical meetings) to use the new interface?</summary>
    <p>Tutorials will be added to the documentation in due time explaining the usage of the different interfaces. We will also be present on different conferences explaining the service & ecosystem.</p>
</details>

## Copernicus Browser

<details id="where-can-i-learn-more-about-the-copernicus-browser">
    <summary onclick="handleQuestionClick('where-can-i-learn-more-about-the-copernicus-browser')">Where can I learn more about the Copernicus Browser?</summary>
    <p>Visit our [documentation page](https://documentation.dataspace.copernicus.eu/Applications/Browser.html) for details about the Browser.</p>
</details>

<details id="how-can-i-find-the-exact-location-by-knowing-the-lat-lon-coordinates">
    <summary onclick="handleQuestionClick('how-can-i-find-the-exact-location-by-knowing-the-lat-lon-coordinates')">How can I find the exact location by knowing the lat/lon coordinates?</summary>
    <p>Simply write coordinates in the "Search places" tool in "lat,lon" form, e.g.:<br><br>
    46.0246,14.5367<br><br>
    And click enter.</p>
</details>

<details id="how-can-i-make-long-time-lapses">
    <summary onclick="handleQuestionClick('how-can-i-make-long-time-lapses')">How can I make long time-lapses?</summary>
    <p>As Copernicus Browser timelapse functionality has a limit of processing up to 300 images at once, we need to do some post-processing, to be able to create longer timelapses.<br><br>
    First, use command prompt to convert .gif timelapses from Copernicus Browser into .mp4 files and then merge them together. For example, if we want to create a five-years long timelapse from daily Sentinel-3 data, six timelapses, each 300 days long, are required. You should first download your smaller timelapses from [Copernicus Browser](https://browser.dataspace.copernicus.eu/).<br><br>
    After downloading the gifs from Copernicus Browser, we should transform them into .mp4 files. To do so, we first need to download and install the ffmpeg program for making videos. Follow [this tutorial to install ffmpeg](https://www.wikihow.com/Install-FFmpeg-on-Windows).<br><br>
    *To test if ffmpeg is installed, go to CMD and type: `ffmpeg -version`.*<br><br>
    To transform a gif into mp4, first navigate to the folder where your gif files are stored, then open your command prompt and write in the following code:</p>
```javascript
ffmpeg -i GIF1.gif -movflags faststart -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" GIF1vid.mp4
```
    *The only part of the code you need to change is the name of your gif at the start and the name of the output .mp4 video at the end.*<br><br>
    You need to transform all your .gif time-lapses into separate .mp4 files:
```javascript
ffmpeg -i GIF1.gif -movflags faststart -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" GIF1vid.mp4<br>
ffmpeg -i GIF2.gif -movflags faststart -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" GIF2vid.mp4<br>
ffmpeg -i GIF3.gif -movflags faststart -pix_fmt yuv420p -vf "scale=trunc(iw/2)*2:trunc(ih/2)*2" GIF3vid.mp4
```
    Finally, merge all the .mp4 files into a final .mp4 file with the following code:
```javascript
ffmpeg -i GIF1vid.mp4 -i GIF2vid.mp4 -i GIF3vid.mp4 -filter_complex "[0:0] [1:0] [2:0] concat=n=3:v=1:a=0" FinalVideo.mp4
```
    In this code, we specify the output name of the final .mp4 timelapse and list the .mp4 files we want to merge. We preface the .mp4 files with -i. Then we need to add as many arrays as there are input .mp4 videos; `[0:0]` for the first one, `[0:1]` for the second one, `[0:3]` for the third one and so on. The `n=3` indicates how many input .mp4 files there are.<br><br>
    For 6 input .mp4 files, the code would look like this:
```javascript
ffmpeg -i GIF1vid.mp4 -i GIF2vid.mp4 -i GIF3vid.mp4 -i GIF4vid.mp4 -i GIF5vid.mp4 -i GIF6vid.mp4 - filter_complex "[0:0][1:0][2:0][3:0][4:0][5:0] concat=n=6:v=1:a=0" FinalVideo.mp4
```
</details>

<details id="how-can-i-configure-my-layers-for-statistical-information-in-copernicus-browser">
    <summary onclick="handleQuestionClick('how-can-i-configure-my-layers-for-statistical-information-in-copernicus-browser')">How can I configure my layers for statistical information in Copernicus Browser?</summary>
    <p>In Copernicus Browser, you can view two kinds of statistical information for your imagery: a line chart of values through time for either a point or a polygon, and a histogram of values (see the chapter Statistical Analysis on our [Copernicus Browser page](https://documentation.dataspace.copernicus.eu/Applications/Browser.html#statistical-analysis)). To enable statistical features, an evalscript supporting statistical API should be used in your layers.<br><br>
    Because statistics operate on the indicator values themselves (and not on RGB), you must add an additional output to the evalscript, which returns the value without conversion to color. For example, statistics can be calculated for values of B04 or for an index like NDVI. Additionally, the evalscript should include dataMask to exclude no-data values from the calculation (no-data pixels often have value 0, which could skew the statistics), and it’s also recommended to check for presence of clouds, so we can exclude them as well (cloudy pixels usually have very high values, which could also skew the results). The user can exclude any pixels from the statistics, such as, for example, snow or water.<br><br>    
    The evalscript should contain the following outputs, with the exact same names:</p>

* `default`: Mandatory. A visualization output that defines what will be displayed on the map. The visualization can return anything you like, a single value grayscale, an RGB visualization, etc.
* `index`: Optional. Returning the raw values of your index, enabling the histogram functionality. Use FLOAT32 format to include decimals and negative values.
* `eobrowserStats`: Mandatory. An output containing both the index values and cloud information, used for line chart generation. Cloud information will allow us to filter the tiles by maximum cloud coverage. Use FLOAT32 format to include decimals and negative values.
* `dataMask`: Mandatory. A dataMask output to take no-data values into account.

    Here is an example evalscript for NDVI:
  
```javascript
//VERSION=3
function setup() {
   return {
       input: ["B04", "B08", "SCL","dataMask"], 
       //The four outputs should be setup here in the setup function, and defined under the evaluatePixel function. 
       output: [
         { id: "default", bands: 4 }, 
         { id: "index", bands: 1, sampleType: 'FLOAT32' },
         { id: "eobrowserStats", bands: 2, sampleType: 'FLOAT32' }, 
         { id: "dataMask", bands: 1 }
       ]
     };
}
// Optional filtering for clouds using the Sentinel-2A SCL band (values 1, 2, 7, 8, 9, 10, 11 are either clouds or snow)
function isCloud (scl) {
 if ([1, 2, 7, 8, 9, 10, 11].includes(scl))  {
   return false;
 } 
}
function evaluatePixel(samples) {
   let val = index(samples.B08, samples.B04); // NDVI calculation
   let imgVals = null; 
   const indexVal = samples.dataMask === 1 ? val : NaN; //NDVI index without no-data values
   const cloud = isCloud(samples.SCL) //calling in our cloud filtering functon as a cloud variable

   //Define the RGB NDVI visualization and write it into imgVals
   if (val<-0.5) imgVals = [0.05,0.05,0.05,samples.dataMask];
   else if (val<-0.2) imgVals = [0.75,0.75,0.75,samples.dataMask];
   else if (val<-0.1) imgVals = [0.86,0.86,0.86,samples.dataMask];
   else if (val<0) imgVals = [0.92,0.92,0.92,samples.dataMask];
   else if (val<0.025) imgVals = [1,0.98,0.8,samples.dataMask];
   else if (val<0.05) imgVals = [0.93,0.91,0.71,samples.dataMask];
   else if (val<0.075) imgVals = [0.87,0.85,0.61,samples.dataMask];
   else if (val<0.1) imgVals = [0.8,0.78,0.51,samples.dataMask];
   else if (val<0.125) imgVals = [0.74,0.72,0.42,samples.dataMask];
   else if (val<0.15) imgVals = [0.69,0.76,0.38,samples.dataMask];
   else if (val<0.175) imgVals = [0.64,0.8,0.35,samples.dataMask];
   else if (val<0.2) imgVals = [0.57,0.75,0.32,samples.dataMask];
   else if (val<0.25) imgVals = [0.5,0.7,0.28,samples.dataMask];
   else if (val<0.3) imgVals = [0.44,0.64,0.25,samples.dataMask];
   else if (val<0.35) imgVals = [0.38,0.59,0.21,samples.dataMask];
   else if (val<0.4) imgVals = [0.31,0.54,0.18,samples.dataMask];
   else if (val<0.45) imgVals = [0.25,0.49,0.14,samples.dataMask];
   else if (val<0.5) imgVals = [0.19,0.43,0.11,samples.dataMask];
   else if (val<0.55) imgVals = [0.13,0.38,0.07,samples.dataMask];
   else if (val<0.6) imgVals = [0.06,0.33,0.04,samples.dataMask];
   else imgVals = [0,0.27,0,samples.dataMask];

   // Return the 4 inputs and define content for each one
   return {
     default: imgVals,
     index: [indexVal],     
     eobrowserStats: [indexVal,cloud?1:0],
     dataMask: [samples.dataMask]
   };
}
```
    See the script in [Copernicus Browser](https://link.dataspace.copernicus.eu/nnvv).<br><br>
    The evalscript can be used directly in Copernicus Browser using the custom script function, or setup for the layer within the [Configuration Utility](https://shapps.dataspace.copernicus.eu/dashboard/#/configurations).<br><br>
    When you create a custom layer, it is possible to select the same layer in Copernicus Browser. Follow the steps below.

* Log into [Copernicus Browser](https://browser.dataspace.copernicus.eu/) and select your configuration from the dropdown menu in *Configurations* in the *Visualize* tab on the left.
* Select the desired data source (if all layers in your configuration have the same data source, only one will be available).
* Make sure to set the appropriate date and zoom in to the area where your data is available.
* If your configuration has more layers, they will be available for selection under the *Layers* in the *Visualize* tab on the left.
* When you have your layer displayed, draw a point or a polygon on the map and inspect the statistics features.
</details>
