---
format:
  html:
    toc: false
---

## Welcome to the [ Copernicus Data Space Ecosystem](https://dataspace.copernicus.eu/#/){target="_blank"} Documentation Portal

We’re delighted you signed up!

Now, let’s explore our extensive documentation to gain insights into our comprehensive Earth Observation data collection and the array of data access and data processing capabilities.

Our documentation is a living resource, continuously updated to provide you with the latest information.


**Discover within this documentation:**

* [Data:](/Data.qmd) Explore large amounts of open and free Earth Observation datasets, including Sentinel Data, Copernicus Contributing Missions, Federated Datasets, and Complementary Data, with detailed information.

* [APIs:](/APIs.md) Find the perfect interface for your needs in our suite of APIs. Whether you seek catalog access, product downloads, data visualization, or processing capabilities, our offerings encompass a range of options, including S3, STAC, openEO, and Sentinel Hub APIs.

* [Applications:](/Applications.md) Simplify your satellite data journey and engage with data using our user-friendly applications for searching, visualizing, modifying, and downloading data effortlessly.

* [Quotas and Limitations:](/Quotas.qmd) Discover the quotas and limitations in place for your account's user type and plan your data download and processing pipelines accordingly.


For quick answers to common queries, check out our [FAQ section](/FAQ.qmd). If you have any questions that remain unanswered on this portal, our [Support](/Support.md) team is here to assist you. Feel free to reach out at any time.

**Welcome aboard**

Ready to get started? Explore our documentation now and unlock the full potential of the [ Copernicus Data Space Ecosystem](https://dataspace.copernicus.eu/#/){target="_blank"}.

Let’s embark on an Earth Observation data-driven journey together!