---
title: Quotas and Limitations
---

```{=html}

Every user account is set a limited quota to guarantee fair sharing of free tier resources within all users of Copernicus Data Space Ecosystem.<br><br>

The following limitations and quotas are monthly and reset on the first day of every month:<br>
  <ul>
    <li>Requests per month</li>
    <li>Requests per minute</li>
    <li>Processing units (PU) per month</li>
    <li>Processed Products per month</li>
    <li>Credits per month</li>
  </ul>

The following limitations and quotas are applied based on a rolling window of 30 days:<br>
  <ul>
    <li>Monthly transfer limit (TB)</li>
  </ul>

The total volume of downloads from the Copernicus Data Space Ecosystem for each user account is summed up for the last 30 days. Downloaded volume is checked on an hourly basis, and if it exceeds the assigned quota, then that user will be moved to a slower interface. Such a user will still be able to access and download products but at a reduced speed.<br><br>

Once the cumulative transfer for the last 30 days falls below the limit, the transfer speed will be restored to its nominal capacity.<br><br>

In addition, the following limitations apply continuously:<br>
  <ul>
    <li>Number of concurrent connections limit</li>
    <li>Bandwidth limit per connection</li>
  </ul>

```
## Copernicus General Users

```{=html}

<div class="table-responsive">
  <table class="table-quotas">
    <thead>
      <tr>
        <th style="text-align: center; vertical-align: middle">Limitations</th>
        <th style="text-align: center; vertical-align: middle">S3, OData, STAC</th>
        <th style="text-align: center; vertical-align: middle">Data Workspace API</th>
        <th style="text-align: center; vertical-align: middle">openEO API / Algorithm plaza</th>
        <th style="text-align: center; vertical-align: middle">Sentinel Hub APIs⁸</th>
        <th style="text-align: center; vertical-align: middle">Direct HTTP access to COGs</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Requests per month</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">10 000</td>
        <td style="text-align: center; vertical-align: middle">50 000⁷ ⁹</td>
      </tr>
      <tr>
        <td>Requests per minute</td>
        <td style="text-align: center; vertical-align: middle">400</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">12¹¹ ¹³</td>
        <td style="text-align: center; vertical-align: middle">300</td>
        <td style="text-align: center; vertical-align: middle">-</td>
      </tr>
      <tr>
        <td>Processing units (PU) per month</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>        
        <td style="text-align: center; vertical-align: middle">10 000</td>
        <td style="text-align: center; vertical-align: middle">-</td>
      </tr>
      <tr>
        <td>Processing units (PU) per minute</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>        
        <td style="text-align: center; vertical-align: middle">300</td>
        <td style="text-align: center; vertical-align: middle">-</td>
      </tr>
      <tr>
        <td>Bandwidth limit per connection (MB/s) (IAD¹)</td>
        <td style="text-align: center; vertical-align: middle">20</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
      </tr>
      <tr>
        <td>Number of concurrent connections limit (IAD¹)</td>
        <td style="text-align: center; vertical-align: middle">4</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
      </tr>
      <tr>
        <td>Monthly transfer limit (TB) (IAD¹)¹⁰</td>
        <td style="text-align: center; vertical-align: middle">6</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
      </tr>
        <tr>
        <td>Number of concurrent orders limit (DAD²)</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">1</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
      </tr>
      <tr>
        <td>Monthly transfer limit (TB) (DAD²)</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">0,1</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>  
      </tr>
      <tr>
        <td>Processed Products per month</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">25</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
      </tr>
      <tr>
        <td>Concurrent Processing</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">2¹²</td>
        <td style="text-align: center; vertical-align: middle">2</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
      </tr>
      <tr>
        <td>Number of active sessions³</td>
        <td style="text-align: center; vertical-align: middle">100</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
      </tr>
      <tr>
        <td>A token stays active for⁴</td>
        <td style="text-align: center; vertical-align: middle">10 minutes</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
      </tr>
      <tr>
        <td>A token can be refreshed in⁵</td>
        <td style="text-align: center; vertical-align: middle">60 minutes</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
      </tr>
        <tr>
        <td>Number of products that be accessed with one token⁶</td>
        <td style="text-align: center; vertical-align: middle">No limits</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
      </tr>
        <tr>
        <td>Credits per month</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">4000</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
      </tr>
        <tr>
        <td>Concurrent API requests</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">2</td>
        <td style="text-align: center; vertical-align: middle">-</td>
        <td style="text-align: center; vertical-align: middle">-</td>
      </tr>
    </tbody>
  </table>
</div>

  <br>
  ¹ IAD: Immediately Available Data. 
  <br>
  ² DAD: Deferred Available Data (known as Offline data). It is not possible to order DAD by using OData,STAC or S3, Copernicus Browser or any of the Sentinel Hub APIs. DAD (Offline data) can only be ordered by using the Data Workspace. Only after ordering, it can be downloaded from the catalogue by using the download APIs.
  <br>
  ³ This includes, among others, a newly generated token and logging in to the user panel. Please refer to: <a href= "https://identity.dataspace.copernicus.eu/auth/realms/CDSE/account/#/security/device-activity" target="_blank">Device Activity</a> and see the number of signed in devices  - It is not possible to increase this number to a bigger value than 100, with a paid plan. Each session starts when the user generates a new token and use it for the downloading process. One session ends when the token reaches its expiry time (a token stays active for 10 min).
  <br>
  ⁴ After reaching this limit, the Access Token must either be refreshed by using the <a href= "https://documentation.dataspace.copernicus.eu/APIs/OData.html#product-download" target="_blank">Refresh Token</a> or be re-generated. 
  <br>
  ⁵ Anytime within 60 minutes after the access token is generated.
  <br>
  ⁶ As long as any other limit(s) are not breached.
  <br>
  ⁷ Extensions are available via CREODIAS offering (see 3.2.3, "Product Generation Service" section of the <a href= "https://documentation.dataspace.copernicus.eu/Roadmap.html" target="_blank">Service Description and Evolution Roadmap</a>).
  <br>
  ⁸ Similar principles apply for all SentinelHub APIs while the differences and details are covered in the <a href= "https://documentation.dataspace.copernicus.eu/APIs/SentinelHub/Overview/ProcessingUnit.html" target="_blank">Processing Unit</a> section of our documentation. Note that there are APIs that are not available to Copernicus General Users such as Sentinel Hub Batch Processing API.
  <br>
  ⁹ Technical limitation may be applied to maintain platform stability.
  <br>
  ¹⁰ After reaching this monthly transfer limit, the maximum bandwidth drops to 1MB/s and the number of concurrent connections drops to 1.
  <br>
  ¹¹ Only enabled for openEO synchronous execution requests (`POST /result`) and batch execution requests (`POST /{job_id}/result`).
  <br>
  ¹² The maximum number of simultaneous
production orders running in parallel, i.e. the orders in “In progress” status.
  <br>
  ¹³ 1 request per 5 seconds.
  <br>

