---
title: UA BBH 3-yearly 2021
collection: 62887e25-816e-4f4e-be0e-5e0f5a6640c9
---
## About
[Official documentation](https://land.copernicus.eu/en/products/urban-atlas)

Urban Atlas Building Block Height 2021 is a 10 m high resolution raster layer containing height information generated for selected cities and urban areas as part of the Urban atlas suite of products. Height information is based on satellite information and derived datasets like the digital surface model, the digital terrain model and the normalized digital surface model (DSM).

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_CLMS_UA_BUILDING-HEIGHT_EUROPE_10M_3YEARLY_V1_2021&clmsSelectedPath=Building%20Height&clmsSelectedCollection=COPERNICUS_CLMS_CLMS_UA_BUILDING-HEIGHT_EUROPE_10M_3YEARLY_V1_2021) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

`62887e25-816e-4f4e-be0e-5e0f5a6640c9`

## Date range

2021 - 2021

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|BBH|UA 2021 Building Height (10 m raster)|meters|UINT16|0.0-368.0|1|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/land-cover-and-use-in-priority-areas/urban-atlas/building-height/clms_ua_building-height_europe_10m_3yearly_v1)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/BatchV2.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
