---
title: DMP 1999-2020 (raster 1 km), global, 10-daily – version 2
---
## About
[Official documentation](https://land.copernicus.eu/en/products/vegetation/dry-matter-productivity-v2-0-1km)

DMP represents the overall growth rate or dry biomass increase of the vegetation and is directly related to ecosystem Net Primary Production (NPP), however with units customized for agro-statistical purposes (kg/ha/day). Every 10-days estimates are available at global scale in the spatial resolution of about 1km and with the temporal extent from 1999 to June 2020.

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_DMP_1KM_10DAILY&clmsSelectedPath=Dry%2FGross%20Dry%20Matter%20Productivity&clmsSelectedCollection=COPERNICUS_CLMS_DMP_1KM_10DAILY) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

| Version | ID |
|:---------:|----|
|None|`12a01750-273b-4ed0-bd8d-da317cdd802a`
|RT0|`431e908c-90c3-4d0f-9814-b2e2b815c6b0`
|RT1|`3f2a6a77-5065-4a3a-be79-97188adabec1`
|RT2|`ab5ef5c2-6b77-437b-9a59-a1a26e8871a7`
|RT6|`e37b5696-d158-41d9-b077-05c79768c76d`

## Date range

1999 - 2020

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|DMP|Dry Matter Productivity|kg/ha/day|INT16|0.0-327.67|1/100|0|
|QFLAG|Bitwise quality flag|-|UINT8|---|1|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/bio-geophysical-parameters/vegetation/dry-gross-dry-matter-productivity/dmp_global_1km_10daily_v2)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/Batch.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
