---
title: DMP 2014-present (raster 300 m), global, 10-daily – version 2
collection: de3e1b9c-58c4-457a-a3e7-917ec20fc29b
---
## About
[Official documentation](https://land.copernicus.eu/en/products/vegetation/dry-matter-productivity-v2-0-300m)

Provides information about the overall growth rate, or net dry biomass increase, of the vegetation. It is equivalent to Net Primary Production (NPP) but expressed in kg of dry matter per hectare and per day. Every 10-days, estimates are available at global scale, at a spatial resolution of ~300 m, from January 2014 to the present.

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_DMP_GLOBAL_300M_10DAILY_V2_RT0&clmsSelectedPath=Dry%2FGross%20Dry%20Matter%20Productivity&clmsSelectedCollection=COPERNICUS_CLMS_DMP_GLOBAL_300M_10DAILY_V2_RT0) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

| Version | ID |
|:---------:|----|
|RT0|`de3e1b9c-58c4-457a-a3e7-917ec20fc29b`
|RT1|`9d27c360-674c-44e2-b846-4be236c39c7e`
|RT2|`d8bbfd31-82da-4a02-bc1c-8f34387954f7`
|RT6|`d888548d-2c56-47ed-847c-17c654e61a03`

## Date range

2014 - present

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|DMP|Dry Matter Productivity (kg DM/ha/day)|kg/ha/day|INT16|0.0-327.67|1/100|0|
|QFLAG|Bitwise quality flag|-|UINT8|---|1|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/bio-geophysical-parameters/vegetation/dry-gross-dry-matter-productivity/dmp_global_300m_10daily_v2)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/Batch.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
