---
title: GDMP 2014-present (raster 300 m), global, 10-daily – version 1
---
## About
[Official documentation](https://land.copernicus.eu/en/products/vegetation/gross-dry-matter-productivity-v1-0-300m)

Equivalent to Gross Primary Production (GPP)

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_GDMP_300M_10DAILY_V1_RT0&clmsSelectedPath=Dry/Gross%20Dry%20Matter%20Productivity&clmsSelectedCollection=COPERNICUS_CLMS_GDMP_300M_10DAILY_V1_RT0) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

| Version | ID |
|:---------:|----|
|RT0|`75c193c0-ba47-4b2a-85dd-f67a0193623e`
|RT1|`1910292e-28de-4c51-9335-816044d3de10`
|RT2|`85e4d9de-4fc6-4a71-8f9a-1e251e4c33bf`
|RT5|`f4bcd0cb-b70d-4d92-960e-9166bc093ec8`
|RT6|`c27817e4-271a-426f-9a03-f53c051b4205`

## Date range

2014-present

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|GDMP|Gross Dry Matter Productivity|kg/ha/day|INT16|0-655.34|1/50|0|
|QFLAG|Bitwise quality flag|-|UINT8|---|1|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/bio-geophysical-parameters/vegetation/dry-gross-dry-matter-productivity/gdmp_global_300m_10daily_v1)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or “custom script”) is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/Batch.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Utilities.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
