---
title: PLOUGH 10m Yearly (2017-present)
collection: c9750aed-88a5-4a0d-907a-1cc406052886
---
## About
[Official documentation](https://land.copernicus.eu/en/products/high-resolution-layer-grasslands)

The High Resolution Layer Ploughing indicator (PLOUGH) raster product continues the 2015 and 2018 PLOUGH Layer following a rolling archive principle by adding current information and removing historic years. It indicates the number of years since the last indication of ploughing within the permanent grassland area. PLOUGH is derived by taking into account the series of binary HER layers, the BVL classifications and HR VPP PPI (Plant Phenology Index) quantiles. BVL classes 4 (crop) and 7 (overlaying layer between herbaceous and crop) indicate a ploughing event. Low HR VPP PPI quantiles indicate low vegetation at a certain time of the year. For years with missing information (2016 and earlier) the ploughing information from the historic PLOUGH product is considered which causes some issues.

This dataset is provided annually starting in 2017 with 10 meter rasters (fully conformant with the EEA reference grid) in 100 x 100 km tiles covering the EEA38 countries.

High Resolution Layer Grasslands product is part of the European Union’s Copernicus Land Monitoring Service.

This dataset includes data from the French Overseas Territories (DOMs)

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_VLCC_PLOUGHING-INDICATOR_EUROPE_10M_YEARLY_V1&clmsSelectedPath=Ploughing%20Indicator&clmsSelectedCollection=COPERNICUS_CLMS_VLCC_PLOUGHING-INDICATOR_EUROPE_10M_YEARLY_V1) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

| Collection | ID |
|:---------:|----|
|Ploughing indicator|`c9750aed-88a5-4a0d-907a-1cc406052886`|

## Date range

2017 - present

## Bands

Ploughing indicator

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|PLOUGH|Years since last ploughing (herbaceous)|Years since last indication of ploughing/Change of herbaceous cover|UINT8|0.0-100.0|1|0|


## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/land-cover-and-land-use-mapping/grasslands/grassland-and-herbaceous/ploughing-indicator/clms_vlcc_ploughing-indicator_europe_10m_yearly_v1)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/BatchV2.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.

