---
title: "EOAP CWL"
execute:
  echo: false
jupyter: python3
aliases:
  - /EOAP-CWL.html
---

With openEO, it is now possible to run CWL ([Common Workflow Language](https://www.commonwl.org/)) in the `run_udf` process. This is executed on Calrissian
On the CDSE backend, this has some extra features, which are described on this page.
More information can be found here: [udf-eoap-cwl.md](https://github.com/Open-EO/openeo-geopyspark-driver/blob/master/docs/udf-eoap-cwl.md)


## S3 access

CWL workflows running on this backend will receive short-lived S3 credentials with read-only access to the `eodata` bucket.
Those credentials can be accessed through the following environment variables:

- `AWS_ENDPOINT_URL_S3`
- `AWS_ACCESS_KEY_ID`
- `AWS_SECRET_ACCESS_KEY`

They only work inside the cluster environment, and are only temporarily valid.
You can use these instead of your own credentials. This way, your Docker images can remain public.

## Docker images

Only whitelisted Docker images can be used in the cluster. Contact us through [support](https://helpcenter.dataspace.copernicus.eu/hc/en-gb/requests/new) (You might need to create an account)
As of February 2026, only public Docker images are used.


## Memory limits

As of February 2026, the memory limit is set to 15GB.

## Debugging locally

To test your CWL workflow locally before running it on the cluster,
you can use [cwltool](https://pypi.org/project/cwltool/) locally.
You might need to provide your own S3 credentials. You can request them
here: https://documentation.dataspace.copernicus.eu/APIs/S3.html

```bash
cwltool \
  --tmpdir-prefix=$HOME/tmp/ \
  --force-docker-pull \
  --leave-container \
  --leave-tmpdir \
  --no-read-only \
  --parallel \
  --preserve-environment=AWS_ENDPOINT_URL_S3 \
  --preserve-environment=AWS_ACCESS_KEY_ID \
  --preserve-environment=AWS_SECRET_ACCESS_KEY \
  example_workflow.cwl example_parameters.json
```
