---
title: "openEO algorithm plaza"
---
The [openEO algorithm plaza](https://marketplace-portal.dataspace.copernicus.eu/){target="_blank"} will host many algorithms that are built on top of the openEO API. These can be addressed via user interfaces or via API to embed into new services or platforms. Third party services will be able to onboard their algorithms semi-automatically in the openEO plaza for further exposure. Users are granted with credits to explore the available algorithms and check if they are fit for purpose for their needs.

In this section we provide a comprehensive overview of essential links related to the openEO algorithm plaza. These links serve as valuable resources for individuals seeking to gain further knowledge about the platform. Included are references to a guide tailored for general users, a guide designed specifically for developers and service providers, as well as additional links pertaining to various services offered by openEO.


## Getting Started

Are you new to the openEO algorithm plaza? Get started by exploring the following guides:

* [openEO algorithm plaza Introduction](PlazaDetails/Introduction.qmd)

* [Guide for openEO algorithm plaza users](PlazaDetails/UserGuide.qmd)

* [Guide for third party service providers](PlazaDetails/ServiceProviderGuide.qmd)


## Popular links


* [openEO algorithm plaza overview](PlazaDetails/Overview.qmd)

* [Signing in](PlazaDetails/SignIn.qmd)

* [Manage your services](PlazaDetails/ManageService.qmd)

* [Manage your billing information](PlazaDetails/ManageBilling.qmd) 

* [Execute a service](PlazaDetails/ExecuteService.qmd)


## Support

### Executing services

If you are experiencing issues with executing your service, feel free to contact our support team by [creating a ticket](https://helpcenter.dataspace.copernicus.eu/hc/en-gb){target="_blank"}.

### Publishing services

Are you having trouble publishing your service onto the openEO algorithm plaza? Our support team is ready to assist! Feel free to [create a ticket](https://helpcenter.dataspace.copernicus.eu/hc/en-gb){target="_blank"}.
