---
title: "Copernicus Land Monitoring Service (CLMS)"
aliases: 
  - /Data/CLMS.html
format:
  html:
    code-fold: true
execute:
  echo: false
  output: asis
jupyter: python3
image: https://land.copernicus.eu/static/media/ccl-icon-land-text-2.e04af716.svg
---
<!--
```{python}
#| tags: [parameters]

constellation = "CLMS"

```
-->

The Copernicus Land Monitoring Service (CLMS) provides geographical information on land cover and land use and their changes, ground motion, vegetation state, water cycle and Earth's surface energy variables for both Europe and the entire globe.<br>

CLMS is jointly implemented by the European Environment Agency and the European Commission DG Joint Research Centre (JRC) and has been operational since 2012.<br>

CLMS consists of several components.<br>

Visit the website [land.copernicus.eu](https://land.copernicus.eu/en){target='_blank'} for further information.<br><br>

:::{.callout-important}
## Disclaimer: CLMS Product Availability on CDSE
CLMS is in the process of onboarding its products to the CDSE. The migration process is expected to last until the end of 2025. Until the process is finalized, not all CLMS products will be available on the CDSE. Onboarded products will be listed in the tables below.

For the complete CLMS data catalog, please consult [land.copernicus.eu](https://land.copernicus.eu/en){target='_blank'}.

We appreciate your understanding and patience as we work to integrate our full suite of products. For the most up-to-date information on product availability, please check back regularly or contact our support team.

Thank you for your continued support.

:::

<br><br>

# Land Cover and Land Use Mapping {#landcover-landusemapping}

Land Cover and Land Use Mapping produces land cover classifications at various level of detail, both within a pan-European and global context. At the pan-European level, these are complemented by detailed layers on land cover characteristics, such as imperviousness, forests, grassland, water and wetness and small woody features. At global level, the land cover mapping follows the FAO's modular-hierarchical Land Cover Classification System.

```{python}
#| tags: [parameters]

constellation = "CLMStoCDSE_land"

```

{{< include ../_render_collections.qmd >}}



# Priority Area Monitoring {#priority-area-monitoring}

Priority Area Monitoring aims to provide tailored and more detailed land cover and land use information on specific areas of interest, often called hot spots. Hot spots in the context of the Copernicus Land Monitoring Service are areas prone to specific environmental challenges.

```{python}
#| tags: [parameters]

constellation = "CLMStoCDSE_priority"

```

{{< include ../_render_collections.qmd >}}



# Bio-geophysical Parameters {#bio-geophysical-parameters}

The systematic monitoring of Bio-geophysical Parameters produces a series of qualified bio-geophysical products on the status and evolution of the land surface. The products are used to monitor vegetation, crops, water cycle, energy budget and terrestrial cryosphere variables.

```{python}
#| tags: [parameters]

constellation = "CLMStoCDSE_bio"

```

{{< include ../_render_collections.qmd >}}




<!--
Remove completely on request of Pierlorenzo MARASCO (JRC)
<br><br>

# CREODIAS federated CLMS products {#clms_federated}

These CREODIAS federated CLMS products are currently accessible only via the [S3 protocol](../../APIs/S3.html). The S3 Path is:

```
/eodata/CLMS-LEGACY/

```

To access data for a specific product, please use the S3 Path provided in each section below.

:::{.callout-note}
## Disclaimer: CLMS Product Availability through CREODIAS Federation
The following products are made available through the CREODIAS federation and may contain significant differences regarding completeness, timeliness, format, and content as compared to the [CLMS portfolio](#clms_portfolio). These products **will be removed** once the CLMS migration process is finalized.

For more information on the official product portfolio and services, please consult [land.copernicus.eu](https://land.copernicus.eu/en){target='_blank'}.

We appreciate your understanding and patience during this transition period. For the most up-to-date information, please check back regularly or contact our support team.

Thank you for your continued support.

:::


```{python}
#| tags: [parameters]

constellation = "CLMS_LEGACY"

```

{{< include ../_render_collections.qmd >}}

-->