---
aliases: 
  - /Data/Sentinel2.html#sentinel-2-l1c-baselines
format:
  html:
    code-fold: true
execute:
  echo: false
  output: asis
jupyter: python3

---

##### Sentinel-2 L1C Baselines

The Sentinel-1 L1C collection within the Copernicus Data Space Ecosystem originates from the operational Copernicus processing, i.e. data previously accessible on the Copernicus Open Access Hub (formerly known as Sentinels Scientific Data Hub).

These products can be differentiated by the [OData](https://documentation.dataspace.copernicus.eu/APIs/OData.html#query-by-attributes){target="_blank"} and [OpenSearch](https://catalogue.dataspace.copernicus.eu/resto/api/collections/Sentinel2/describe.xml){target="_blank"} **processingBaseline** attribute. Processing Baseline is presented on Copernicus Browser as a "Processor version" attribute.

The current state of the archive of the Sentinel-L1C data is as follows:

<table class="table-roadmap" style="margin: 10px;">
  <thead>
    <tr>
      <th style="background-color: #9ea1a5">Availability of S-2 L1C products based on sensing date</th>
      <th style="background-color: #9ea1a5">Processing Baseline</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>15/12/2015 - 03/05/2016</td>
      <td>Processing Baseline 02.01 <br>(originating from Copernicus Open Access Hub) <br>(Attribute ‘processorVersion’: 2.01)</td>
    </tr>
    <tr>
      <td>03/05/2016 - 15/06/2016</td>
      <td>Processing Baseline 02.02 <br>(originating from Copernicus Open Access Hub) <br>(Attribute ‘processorVersion’: 02.02 or 2.01)</td>
    </tr>
    <tr>
      <td>04/07/2015 - 26/05/2017</td>
      <td>Processing Baseline 02.04 (To replace 02.03) <br>(originating from Copernicus Open Access Hub) <br>(Attribute ‘processorVersion’: 02.04 or 2.04)</td>
    </tr>
    <tr>
      <td>19/03/2017 - 23/10/2017</td>
      <td>Processing Baseline 02.05 <br>(originating from Copernicus Open Access Hub) <br>(Attribute ‘processorVersion’: 02.05 or 2.05)</td>
    </tr>
    <tr>
      <td>10/04/2016 -  06/11/2018</td>
      <td>Processing Baseline 02.06 <br>(originating from Copernicus Open Access Hub) <br>(Attribute ‘processorVersion’: 02.06 or 2.06)</td>
    </tr>
    <tr>
      <td>06/11/2018 - 22/07/2019</td>
      <td>Processing Baseline 02.07 <br>(originating from Copernicus Open Access Hub) <br>(Attribute ‘processorVersion’: 02.07 or 2.07)</td>
    </tr>
    <tr>
      <td>10/04/2016 -  04/02/2020</td>
      <td>Processing Baseline 02.08 <br>(originating from Copernicus Open Access Hub) <br>(Attribute ‘processorVersion’: 2.08)</td>
    </tr>
    <tr>
      <td>29/09/2015 – 30/03/2021</td>
      <td>Processing Baseline 02.09 <br>(originating from Copernicus Open Access Hub) <br>(Attribute ‘processorVersion’: 2.09)</td>
    </tr>
    <tr>
      <td>30/03/2021 - 30/06/2021</td>
      <td>Processing Baseline 03.00 <br>(originating from Copernicus Open Access Hub) <br>(Attribute ‘processorVersion’: 3.0)</td>
    </tr>
    <tr>
      <td>30/06/2021 - 25/01/2022</td>
      <td>Processing Baseline 03.01 <br>(originating from Copernicus Open Access Hub) <br>(Attribute ‘processorVersion’: 03.01 or 3.01)</td>
    </tr>
    <tr>
      <td>25/01/2022 - 06/12/2022</td>
      <td>Processing Baseline 04.00 <br>(originating from Copernicus Open Access Hub) <br>(Attribute ‘processorVersion’: 04.00 or 4.0)</td>
    </tr>
    <tr>
      <td>29/04/2022 – 13/12/2023</td>
      <td>Processing Baseline 05.09 <br>(originating from Copernicus Open Access Hub and Copernicus Data Space Ecosystem) <br>(Attribute ‘processorVersion’: 05.09 or 5.09)</td>
    </tr>
    <tr>
      <td>13/12/2023 - Now</td>
      <td>Processing Baseline 05.10 <br>(originating from  Copernicus Data Space Ecosystem) <br>(Attribute ‘processorVersion’: 05.10 or 5.10)
</td>
    </tr>
  </tbody>
</table>

##### Processing Baseline 5.00 and 5.10 for Sentinel-2 L1C and L2A

The Sentinel-2 Collection 1 (reprocessed data) featuring processing baseline 5.00 and 5.10 is gradually ingested into the Copernicus Data Space Ecosystem. This ingestion will be completed at the end of August 2024.<br>

<table class="table-roadmap" style="margin: 10px;">
  <thead>
    <tr>
      <th style="background-color: #9ea1a5">Updated availability by sensing time period(*)</th>
      <th style="background-color: #9ea1a5">Sentinel-2A</th>
      <th style="background-color: #9ea1a5">Sentinel-2B</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Published (**)(Processing baseline 05.00)</td>
      <td>From 4 July 2015 to 31 December 2021 included</td>
      <td>From 17 March 2017 to 31 December 2021 included</td>
    </tr>
    <tr>
      <td>Next period in list (Processing baseline 05.10)</td>
      <td>From 1 January 2022 then continuing in chronological order sensing time, up to 13 December 2023</td>
      <td>From January 1 2022 then continuing in chronological order of sensing time, up to 13 December 2023</td>
    </tr>
  </tbody>
</table>

(*) Table 1: The products are made available based on the first acquisitions after the commissioning of the satellites.<br>
(**) There is a known product gap between 2018 and 2019 (2.7 million S-2 Collection-1 products). Missing products will be made available successively.

Please refer to the article [Copernicus SENTINEL-2 Collection-1 Availability Status](https://sentinels.copernicus.eu/web/sentinel/technical-guides/sentinel-2-msi/copernicus-sentinel-2-collection-1-availability-status)
that aims at providing up-to-date progress information on the proceedings of the generation of Collection-1 and on the gradual availability of Collection-1 Level-1C and Level-2A products.