---
aliases: 
  - /Data/Sentinel2.html#sentinel-2-l2a-baselines
format:
  html:
    code-fold: true
execute:
  echo: false
  output: asis
jupyter: python3

---

##### Sentinel-2 L2A Baselines

The Sentinel-2 L2A collection within the Copernicus Data Space Ecosystem originates from three sources: 

**(1)** operational Copernicus processing, i.e. data previously accessible on the Copernicus Open Access Hub (formerly known as Sentinels Scientific Data Hub);
 
**(2)** reprocessing of the L2A archive from 2015 until the end of 2021 [(Collection 1)](https://sentinel.esa.int/web/sentinel/sentinel-data-access/sentinel-products/sentinel-2-data-products/collection-1-level-2a){target="_blank"}, and ;

**(3)** data generated by CloudFerro using various versions of the publicly available [Sen2Cor processor](https://step.esa.int/main/snap-supported-plugins/sen2cor/){target="_blank"}. This data will be removed once replaced by the reprocessing of the L2A (point 2 above), which is planned to be completed in April 2024

These products can be differentiated by the [OData](https://documentation.dataspace.copernicus.eu/APIs/OData.html#query-by-attributes){target="_blank"} and [OpenSearch](https://catalogue.dataspace.copernicus.eu/resto/api/collections/Sentinel2/describe.xml){target="_blank"} **(origin)** attribute (ESA or CloudFerro) and by the **'processingBaseline'** attribute. Processing Baseline is presented on Copernicus Browser as a "Processor version" attribute.

The current state of the archive of the Sentinel-L2A data is as follows:

<table class="table-roadmap" style="margin: 10px;">
  <thead>
    <tr>
      <th style="background-color: #9ea1a5">Availability of S-2 L2A products based on sensing date</th>
      <th style="background-color: #9ea1a5">Processing Baseline</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>29/09/2015 - 14/01/2023</td>
      <td>Processing Baseline 99.99 <br>(generated by CloudFerro) <br>(Attribute ‘processorVersion’: 99.99)</td>
    </tr>
    <tr>
      <td>04/07/2015 - 21/05/2021</td>
      <td>Processing Baselines 2.05 -2.13 <br>(originating from Copernicus Open Access Hub and generated by CloudFerro)</td>
    </tr>
    <tr>
      <td>04/02/2020 - 30/03/2021</td>
      <td>Processing Baseline 2.14 <br>(originating from Copernicus Open Access Hub) <br>(Attribute ‘processorVersion’: 02.14)</td>
    </tr>
    <tr>
      <td>25/01/2022 - 06/12/2022</td>
      <td>Processing Baseline 4.00 <br>(originating from Copernicus Open Access Hub) <br>(Attribute ‘processorVersion’: 04.00 or 4.0)</td>
    </tr>
    <tr>
      <td>29/04/2022 - 13/12/2023</td>
      <td>Processing Baseline 5.09 <br>(originating from Copernicus Open Access Hub and Copernicus Data Space Ecosystem) <br>(Attribute ‘processorVersion’: 05.09 or 5.09)</td>
    </tr>
    <tr>
      <td>13/12/2023 - Now</td>
      <td>Processing Baseline 5.10 <br>(originating from Copernicus Data Space Ecosystem) <br>(Attribute ‘processorVersion’: 05.10 or 5.10)</td>
    </tr>
  </tbody>
</table>

##### Processing Baseline 5.00 and 5.10 for Sentinel-2 L1C and L2A

The Sentinel-2 Collection 1 (reprocessed data) featuring processing baseline 5.00 and 5.10 is gradually ingested into the Copernicus Data Space Ecosystem. This ingestion will be completed at the end of August 2024.<br>

<table class="table-roadmap" style="margin: 10px;">
  <thead>
    <tr>
      <th style="background-color: #9ea1a5">Updated availability by sensing time period(*)</th>
      <th style="background-color: #9ea1a5">Sentinel-2A</th>
      <th style="background-color: #9ea1a5">Sentinel-2B</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>Published (**)(Processing baseline 05.00)</td>
      <td>From 4 July 2015 to 31 December 2021 included</td>
      <td>From 17 March 2017 to 31 December 2021 included</td>
    </tr>
    <tr>
      <td>Next period in list (Processing baseline 05.10)</td>
      <td>From 1 January 2022 then continuing in chronological order sensing time, up to 13 December 2023</td>
      <td>From January 1 2022 then continuing in chronological order of sensing time, up to 13 December 2023</td>
    </tr>
  </tbody>
</table>

(*) Table 1: The products are made available based on the first acquisitions after the commissioning of the satellites.<br>
(**) There is a known product gap between 2018 and 2019 (2.7 million S-2 Collection-1 products). Missing products will be made available successively.

Please refer to the article [Copernicus SENTINEL-2 Collection-1 Availability Status](https://sentinels.copernicus.eu/web/sentinel/technical-guides/sentinel-2-msi/copernicus-sentinel-2-collection-1-availability-status)
that aims at providing up-to-date progress information on the proceedings of the generation of Collection-1 and on the gradual availability of Collection-1 Level-1C and Level-2A products.
