---
title: Sentinel-2 CC Europe 20m Daily V1
collection: 64d015da-e225-48d8-9643-30a453657beb
---
## About
[Official documentation](https://land.copernicus.eu/en/products/snow/fractional-snow-cover)

The Cloud Classification (CC) product provides information on the extent of clouds and cloud shadows derived from optical satellite data acquired by the **Sentinel-2** constellation. Cloud detection is performed at a **120m** spatial resolution using the [MAJA software](https://gitlab.orfeo-toolbox.org/maja/maja/).<br><br>It is generated in near real-time at European scale, with a pixel spacing of 20 m x 20 m. It used to produce the CLMS High-Resolution Water, Snow and Ice datasets (HR-WSI), which rely on Sentinel-2 imagery.<br><br>**Data availability**: from 2016 to the present. No product is generated for a Sentinel-2 tile when cloud cover exceeds 90%.<br><br>More information in the products documentation [here](https://land.copernicus.eu/en/products/snow/fractional-snow-cover).

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_WSI_CLOUD-CLASSIFICATION_EUROPE_UTM_20M_DAILY_V1&clmsSelectedPath=Cloud%20Mask&clmsSelectedCollection=COPERNICUS_CLMS_WSI_CLOUD-CLASSIFICATION_EUROPE_UTM_20M_DAILY_V1) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

```default
64d015da-e225-48d8-9643-30a453657beb
```

## Date range

2016 - present

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|CC|Cloud and cloud shadow classification of the Sentinel-2 image|Cloud classification: 0=No Data, 1=Clear, 2=Cloud Shadow, 3=Cloud|UINT8|0.0-3.0|1|0|
|CC_QA|Quality layer for the cloud and cloud shadow classification (CC) layer|Quality assessment for CC layer. Indicators for defects such as missing pixels and cloudy data.|UINT8|0.0-255.0|1|0|
|QAFLAGS|Quality flags|Bitmask with quality flags. Bit 0: cloud detection using single-scene threshold approach.|UINT8|0.0-255.0|1|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/bio-geophysical-parameters/auxiliary-data/cloud-mask/clms_wsi_cloud-classification_europe_utm_20m_daily_v1)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/BatchV2.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
