---
title: Land Cover (raster 100 m), global, yearly – version 3
---
## About
[Official documentation](https://land.copernicus.eu/en/products/global-dynamic-land-cover)

Provides at global level spatial information on different types (classes) of physical coverage of the Earth's surface, e.g. forests, grasslands, croplands, lakes, wetlands.

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_LCC_100M_YEARLY_V3&clmsSelectedPath=Global%20Dynamic%20Land%20Cover&clmsSelectedCollection=COPERNICUS_CLMS_LCC_100M_YEARLY_V3) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

`35fecfec-8a73-4723-bb08-b775f283a535`

## Date range

2015 - 2019

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|Bare_Cover_Fraction|Percentage of 100m pixel that is covered by bare ground|%|UINT8|0.0-100.0|1|0|
|BuiltUp_Cover_Fraction|Percentage of 100m pixel that is covered by urban or built-up areas|%|UINT8|0.0-100.0|1|0|
|Crops_Cover_Fraction|Percentage of 100m pixel that is covered by crops|%|UINT8|0.0-100.0|1|0|
|Shrub_Cover_Fraction|Percentage of 100m pixel that is covered by shrubs|%|UINT8|0.0-100.0|1|0|
|Snow_Cover_Fraction|Percentage of 100m pixel that is covered by snow|%|UINT8|0.0-100.0|1|0|
|Tree_Cover_Fraction|Percentage of 100m pixel that is covered by forests or trees|%|UINT8|0.0-100.0|1|0|
|Grass_Cover_Fraction|Percentage of 100m pixel that is covered by grass|%|UINT8|0.0-100.0|1|0|
|MossLichen_Cover_Fraction|Percentage of 100m pixel that is covered by moss or lichen|%|UINT8|0.0-100.0|1|0|
|PermanentWater_Cover_Fraction|Percentage of 100m pixel that is covered by permanent water|%|UINT8|0.0-100.0|1|0|
|SeasonalWater_Cover_fraction|Percentage of 100m pixel that is covered by seasonal water|%|UINT8|0.0-100.0|1|0|
|Change_Confidence|Reliability of the change in the discrete class and hence implicitly also in the fractional covers|No change, potential change, medium confidence, high confidence|UINT8|0.0-3.0|1|0|
|Data_Density_Indicator|Availability of input PROBA-V UTM data at 100m and 300m resolutions|0 = no data available, 100 = best data availability|UINT8|0.0-100.0|1|0|
|Discrete_Classification|Main discrete land cover classification, according to UN-FAO LCCS|23 classes:
six types closed forest, six types open forest, Shrub, Herbaceous vegetation, Herbaceous wetland, Moss and lichen, Bare / sparse vegetation, Cultivated and managed vegetation (cropland), Urban / Built-up, Snow and Ice, Permanent inland water bodies, Missing data, Open sea|UINT8|0.0-200.0|1|0|
|Discrete_Classification_Probability|Probability (quality indicator) of the discrete classification|%|UINT8|0.0-100.0|1|0|
|Forest_Type|Type of forest for all pixels where forest cover fraction exceeds 1%|Six types:
Evergreen, needle leaf forest (ENF), Evergreen, broad leaf forest (EBF), Deciduous, needle leaf forest (DNF), Deciduous, broad leaf forest (DBF), Mixed, Unknown / Other|UINT8|0.0-5.0|1|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/land-cover-and-land-use-mapping/global-dynamic-land-cover/lc_global_100m_yearly_v3)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/BatchV2.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
