---
title: ICD Europe 20m Yearly V1
collection: 11107497-588f-495b-911e-85a1614ebdb2
---
## About
[Official documentation](https://land.copernicus.eu/en/products/water-bodies/high-resolution-ice-cover-duration)

The **Ice Cover Duration (ICD)** product describes how long inland waters are covered by ice. For each pixel and for a given hydrological year, it provides the number of days with ice cover. The hydrological year starts on 1 September. It is based on ice cover maps derived from **Sentinel-2** optical data (Water/Ice Cover WIC S2) and **Sentinel-1** C-band Synthetic Aperture Radar data (Water/Ice Cover WIC S1).<br><br>The product is generated at the European scale with a spatial resolution of **20 m x 20 m**.<br><br>**Data availability**: from 2016 to the present. The data can be downloaded in multiple projections and pixel spacings.<br><br>More information [here](https://land.copernicus.eu/en/products/water-bodies/high-resolution-ice-cover-duration).

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_WSI_ICE-COVER-DURATION_EUROPE_UTM_20M_YEARLY_V1&clmsSelectedPath=Water%20and%20Ice%20Cover&clmsSelectedCollection=COPERNICUS_CLMS_WSI_ICE-COVER-DURATION_EUROPE_UTM_20M_YEARLY_V1) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

```default
11107497-588f-495b-911e-85a1614ebdb2
```

## Date range

2016 - present

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|ICD|Ice cover duration (in days)|[days]|UINT16|0.0-366.0|1|0|
|ICD_QA|Quality layer for the ice cover duration (ICD) layer|0=high quality; 1=medium quality; 2=low quality; 3=minimal quality|UINT16|0.0-3.0|1|0|
|NOBS1|Number of days with Sentinel-1 based observations during the hydrological year|[days]|UINT16|0.0-366.0|1|0|
|NOBS2|Number of days with Sentinel-2 based observations during the hydrological year|[days]|UINT16|0.0-366.0|1|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/bio-geophysical-parameters/water-bodies/water-and-ice-cover/clms_wsi_ice-cover-duration_europe_utm_20m_yearly_v1)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/BatchV2.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
