---
title: WIC S2 Europe 20m Daily V1
collection: 4c770f75-303d-4b8e-bf6d-9ca148b34cfb
---
## About
[Official documentation](https://land.copernicus.eu/en/products/water-bodies/water-and-ice-cover-raster-20-m-60-m-europe-daily)

The **Water and Ice Cover by Sentinel-2 (WICS2)** product provides the water and ice extent over land. A water mask is used to differentiate between snow on ice-covered water areas and snow on land. Cloud detection in the Sentinel-2 imagery is performed using the [MAJA software](https://gitlab.orfeo-toolbox.org/maja/maja/).<br><br>It is generated in near real-time at European scale based on optical satellite data from the Sentinel-2 constellation, with a spatial resolution of **20 m x 20 m**.<br><br>**Data availability**: from 2016 to the present. No product is generated for a Sentinel-2 tile when cloud cover exceeds 90%.<br><br>More information [here](https://land.copernicus.eu/en/products/water-bodies/water-and-ice-cover-raster-20-m-60-m-europe-daily).

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_WSI_WATER-ICE-COVER-S2_EUROPE_UTM_20M_DAILY_V1&clmsSelectedPath=Water%20and%20Ice%20Cover&clmsSelectedCollection=COPERNICUS_CLMS_WSI_WATER-ICE-COVER-S2_EUROPE_UTM_20M_DAILY_V1) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

```default
4c770f75-303d-4b8e-bf6d-9ca148b34cfb
```

## Date range

2016 - present

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|WIC|Water/Ice Cover|1=open water; 100=snow-covered or snow-free ice; 205=cloud or cloud shadow; 254=other (land/vegetation/sea); 255=no data|UINT8|1.0-254.0|1|0|
|WIC_QA|Quality layer for the Water/Ice Cover (WIC) layer|0=high quality; 1=medium quality; 2=low quality; 3=minimal quality|UINT8|0.0-3.0|1|0|
|QAFLAGS|Quality flags|Bitmask layer with pixel quality flags.|UINT8|---|1|0|
|PRB|Probability of the class indicated by the Water/Ice Cover (WIC) layer|[%]|UINT8|0.0-100.0|1|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/bio-geophysical-parameters/water-bodies/water-and-ice-cover/clms_wsi_water-ice-cover-s2_europe_utm_20m_daily_v1)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/BatchV2.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
