---
title: WIC S1 Europe 60m Daily V1
collection: a4ec97d7-243c-4af3-873e-dc486d4e4a37
---
## About
[Official documentation](https://land.copernicus.eu/en/products/water-bodies/water-and-ice-cover-raster-20-m-60-m-europe-daily)

The **Water and Ice Cover by Sentinel-1 (WICS1)** product provides information about river and lake areas covered by snow-covered or snow-free ice. It is based on synthetic aperture radar data from the **Sentinel-1** constellation.<br><br>It is generated in near real-time at European scale, with a spatial resolution of **60 m x 60 m**.<br><br>**Data availability**: from 2016 to the present.<br><br>More information [here](https://land.copernicus.eu/en/products/water-bodies/water-and-ice-cover-raster-20-m-60-m-europe-daily).

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_WSI_WATER-ICE-COVER-S1_EUROPE_UTM_60M_DAILY_V1&clmsSelectedPath=Water%20and%20Ice%20Cover&clmsSelectedCollection=COPERNICUS_CLMS_WSI_WATER-ICE-COVER-S1_EUROPE_UTM_60M_DAILY_V1) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

```default
a4ec97d7-243c-4af3-873e-dc486d4e4a37
```

## Date range

2016 - present

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|WIC|Water/Ice Cover|1=open water; 100=snow-covered or snow-free ice; 200=radar shadow/layover/foreshortening; 255=no data|UINT8|1.0-200.0|1|0|
|WIC_QA|Quality layer for the Water/Ice Cover (WIC) layer|0=high quality; 1=medium quality; 2=low quality; 3=minimal quality; 200=radar shadow/layover/foreshortening; 255=no data|UINT8|0.0-3.0|1|0|
|QAFLAGS|Quality flags|Bitmask layer with pixel quality flags. Bit 15 activated indicates inland water surfaces over which classification is performed.|UINT16|---|1|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/bio-geophysical-parameters/water-bodies/water-and-ice-cover/clms_wsi_water-ice-cover-s1_europe_utm_60m_daily_v1)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/BatchV2.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
