---
title: Dominant Leaf Type Change 20m 3yearly (2018-2021) V1
collection: 9bdecd15-4101-4859-8d00-b2f49c2c6876
---
## About
[Official documentation](https://land.copernicus.eu/en/products/high-resolution-layer-forests-and-tree-cover)

The High Resolution Layer Dominant Leaf Type Change (DLTC) 2018-2021 raster product provides information on the change between the reference years 2018 and 2021 and consists of 7 thematic classes (unchanged areas with no tree cover / new broadleaved cover / new coniferous cover / loss of broadleaved cover / loss of coniferous cover / unchanged areas with tree cover / potential change among dominant leaf types).

This dataset is provided in 20 meter rasters (fully conformant with the EEA reference grid) in 100 x 100 km tiles covering the EEA38 countries.

The production of the high resolution forest layers was coordinated by the European Environment Agency (EEA) in the frame of the EU Copernicus programme.

This dataset includes data from the French Overseas Territories (DOMs)

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_CLMS_VLCC_DOMINANT-LEAF-TYPE-CHANGE_EUROPE_20M_3YEARLY_V1&clmsSelectedPath=Dominant%20Leaf%20Type%20Change&clmsSelectedCollection=COPERNICUS_CLMS_CLMS_VLCC_DOMINANT-LEAF-TYPE-CHANGE_EUROPE_20M_3YEARLY_V1) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

`9bdecd15-4101-4859-8d00-b2f49c2c6876`

## Date range

2018 - 2021

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|DLTC|Tree cover change classification|0 = unchanged areas with no tree cover, 1 = new broadleaved cover, 2 = new coniferous cover, 3 = loss of broadleaved cover, 4 = loss of coniferous cover, 10 = unchanged areas with tree cover, 255 = outside area|UINT8|0.0-255.0|1|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/land-cover-and-land-use-mapping/tree-cover-and-forests/dominant-leaf-type/dominant-leaf-type-change/clms_vlcc_dominant-leaf-type-change_europe_20m_3yearly_v1)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/Batch.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
