---
title: WCD Europe 10m Yearly V1
collection: 6cbd4f0b-834d-4e91-aa56-8c347b9cf971
---
## About
[Official documentation](https://land.copernicus.eu/en/products/water-bodies/high-resolution-water-cover-duration)

The Water Cover Duration (WCD) product estimates the number of days land is covered by water. For each pixel and for a given hydrological year,  it indicates how frequently water is present. The hydrological year starts on 1 September. The product is generated at the European scale with a spatial resolution of 10 m × 10 m. It is based on water masks derived from Sentinel-1 radar and Sentinel-2 optical data, combined with Water/Ice Cover data from Sentinel-2 (WIC S2). It is available for the period from 2016 to the present and can be downloaded in multiple projections and pixel spacings. More information here.

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_WSI_WATER-COVER-DURATION_EUROPE_UTM_10M_YEARLY_V1&clmsSelectedPath=Water%20Extent&clmsSelectedCollection=COPERNICUS_CLMS_WSI_WATER-COVER-DURATION_EUROPE_UTM_10M_YEARLY_V1) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

`6cbd4f0b-834d-4e91-aa56-8c347b9cf971`

## Date range

2016 - present

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|WCD|Water presence frequency in a hydrological year (in days)|[days]|UINT16|0.0-366.0|1|0|
|WCD_QA|Quality layer for the water cover duration (WCD) layer|0=high quality; 1=medium quality; 2=low quality; 3=minimal quality; 205=cloud or cloud shadow; 253=sea water|UINT8|0.0-3.0|1|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/bio-geophysical-parameters/water-bodies/water-extent/clms_wsi_water-cover-duration_europe_utm_10m_yearly_v1)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/Batch.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
