---
title: SWE 2024-present (raster 5 km), Northern Hemisphere, daily – version 2
collection: f38bc9f2-5a14-448f-8265-b8070fe288bb
---
## About
[Official documentation](https://land.copernicus.eu/en/products/snow/snow-water-equivalent-v2-0-5km)

Provides for the Northern Hemisphere daily updates of the equivalent amount of liquid water stored in the snow pack.

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_SWE_5KM_DAILY_V2&clmsSelectedPath=Snow%20Water%20Equivalent&clmsSelectedCollection=COPERNICUS_CLMS_SWE_5KM_DAILY_V2) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

```default
f38bc9f2-5a14-448f-8265-b8070fe288bb
```

## Date range

2024 - present

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|SWE|Snow Water Equivalent|mm|FLOAT32|0.0-500.0|1|0|
|VAR|Variance on SWE|mm²|FLOAT32|0.0-5000.0|1|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/bio-geophysical-parameters/snow/snow-water-equivalent/swe_northernhemisphere_5km_daily_v2)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/BatchV2.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
