---
title: GRAME 10m Yearly (2017-present)
collection: 480a24cb-713c-4e72-bcf9-a4edba3f4341
---
## About
[Official documentation](https://land.copernicus.eu/en/products/high-resolution-layer-grasslands)

The High Resolution Layer Grassland Mowing Events (GRAME) raster product provides a basic land cover classification containing respectively the number of grassland mowing events within the detected Herbaceous cover layer (temporal and permanent grassland)) with a Minimum Mapping Unit (MMU) of 0.25 ha. The GRAME product will flag and map the number of mowing events (1, 2, 3, or 4+) on temporary or permanent grassland detected per year.

This dataset is provided annually starting in 2017 with 10 meter rasters (fully conformant with the EEA reference grid) in 100 x 100 km tiles covering the EEA38 countries.

High Resolution Layer Grasslands product is part of the European Union’s Copernicus Land Monitoring Service. Confidence layer available for the dataset.

This dataset includes data from the French Overseas Territories (DOMs)

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_VLCC_GRASSLAND-MOWING-EVENTS_EUROPE_10M_YEARLY_V1&clmsSelectedPath=Grassland%20Mowing%20Events&clmsSelectedCollection=COPERNICUS_CLMS_VLCC_GRASSLAND-MOWING-EVENTS_EUROPE_10M_YEARLY_V1) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

Grassland Mowing Events:

```default
480a24cb-713c-4e72-bcf9-a4edba3f4341
```

Grassland Mowing Events Confidence Layer:

```default
0967983d-9a66-4e4d-93f9-fb91a1a1215e
```

## Date range

2017 - present

## Bands

Grassland Mowing Events

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|GRAME|Count of grassland mowing events |Number of mowing events (1, 2, 3, or 4+). Flag for non-herbaceous area: 253.|UINT8|1.0-253.0|1|0|
Grassland Mowing Events Confidence Layer

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|GRAMECL|Confidence of grassland mowing events|Confidence percentage (0-100%)|UINT8|0.0-100.0|1|0|


## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/land-cover-and-land-use-mapping/grasslands/grassland-mowing-events/grassland-mowing-events/clms_vlcc_grassland-mowing-events_europe_10m_yearly_v1)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/BatchV2.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.

