---
title: CPBSA 10m Yearly (2017-present)
collection: 163c6d26-0b32-44b9-8552-7b38af71cff1
---
## About
[Official documentation](https://land.copernicus.eu/en/products/high-resolution-layer-croplands)

The High Resolution Layer Cropping Patterns - Bare Soil After (CPBSA) raster product provides bare soil period (in days) after the harvest of the main annual crop. Note that the bare soil period cannot transcend the calendar year for which the product is generated.

This dataset is provided annually starting in 2017 with 10 meter rasters (fully conformant with the EEA reference grid) in 100 x 100 km tiles covering the EEA38 countries.

High Resolution Layer Croplands product is part of the European Union’s Copernicus Land Monitoring Service. Confidence layer available for the dataset.

This dataset includes data from the French Overseas Territories (DOMs)

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_VLCC_BARE-SOIL-AFTER_EUROPE_10M_YEARLY_V1&clmsSelectedPath=Bare%20Soil%20After&clmsSelectedCollection=COPERNICUS_CLMS_VLCC_BARE-SOIL-AFTER_EUROPE_10M_YEARLY_V1) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

Bare Soil After:

```default
163c6d26-0b32-44b9-8552-7b38af71cff1
```

Bare Soil After Confidence Layer:

```default
19c33b10-544e-4caa-9c7b-99f4fd1dc9d1
```

## Date range

2017 - present

## Bands

Bare Soil After

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|CPBSA|Bare soil duration after main season|days / quality flags|UINT16|0.0-65534.0|1|0|
Bare Soil After Confidence Layer

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|CPBSACL|Confidence of bare soil after season|days / quality flags|UINT16|0.0-65534.0|1|0|


## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/land-cover-and-land-use-mapping/croplands/cropping-patterns/bare-soil-after/clms_vlcc_bare-soil-after_europe_10m_yearly_v1)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/BatchV2.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.

