---
title: "About openEO Algorithm plaza"
---

<div style="text-align: justify">

The openEO algorithm plaza allows you to share an algorithm or workflow that you developed with our user community.It takes away the IT aspects of publishing a service, so that you can entirely focus on the algorithm's development.Publishing your algorithm as a service will give it greater visibility and expose it to a larger audience that can give feedback.

The openEO algorithm plaza relies on standardized web interfaces, so our users can access your service in an easy manner.A visual description of your service is published, to give an attractive overview of the capabilities.

## Concepts

### What is a service?

Within the context of Earth Observation, a service can do anything, from computing a simple Normalized Difference Vegetation Index (NDVI) for a bounding box, to exposing a complex peer-reviewed algorithm with numerous parameters.Of course, you want to keep your target audience in mind, so you may want to hold back on hard to interpret options when you are trying to reach a non-scientific audience.

Once your algorithm is exposed as a service, users will be able to 'invoke' it with a given set of parameters. 
Within EO, an area of interest and/or time period are very common parameter sets to filter on.

### Service maturity levels

Each of the advertised services in the Terrascope openEO algorithm plaza will be assigned a maturity level. This level indicates what end users can expect from the services with regards to:
* Validation of the results
* Stability
* Scalability
* Documentation

The table below provides an overview of the different maturity levels that are applied within the openEO algorithm plaza.

| Level | Description |
| --- | --- |
| _**Prototype**_ | Service is provided ‘as-is’, with a short description and possibly a reference to what it tries to implement. |
| _**Incubating**_ | Quality of the service is documented with example requests (sets of parameters) and the corresponding output, as well as the resources required to generate that output. Allowing interested users to self-assess whether this service is suitable for usage. |
| _**Verified**_ | The service is labelled verified based on its software readiness and irrelevance to the scientific validation report. |
| _**Validated**_ | The service is validated, and validation reports are available in addition to being verified.
| _**Operational**_ | The service has been shown to be fit for larger scale production and integration in operational systems. Rules for estimating resource usage are available, or a unit cost is established. (€ per hectare, € per request, etc.) |

> Detailed descriptions of the criteria for each maturity level are explained [here](ServiceMaturity.qmd).

## Guides
* [openEO algorithm plaza User](UserGuide.qmd)
* [Third Party Service Provider](ServiceProviderGuide.qmd)

## Quicklinks

* [openEO algorithm plaza overview](Overview.qmd)
* [Signing in](SignIn.qmd)
* [Manage your services](ManageService.qmd)
* [Manage your billing information](ManageBilling.qmd)
* [Execute a service](ExecuteService.qmd)


## Issues?
If you are experiencing any issue with publishing your service onto the openEO algorithm plaza, feel free to contact our support team using the contact form on the [TerraScope website](), create a post on the [TerraScope Forum](), or send a mail to [openEO algorithm plaza@terrascope.be]. 

</div>  
