---
title: "Manage your organization"
---

<div style="text-align: justify">

## Provide your organisation details

Organisations are core elements of the openEO algorithm plaza Portal, as they are the entities that relate users, accesses, services, data, etc. 
One can think of an organisation as a company in most cases, although users can be a one-man organisation.
By default, when a registration is made through the Portal, an organisation is always created with the user that made the registration as the sole user, even if unnamed and with no data.
In a user’s Profile page, they can click on the Organisation option in sub-navigation and arrive at the Organisation page, where they can view and edit the organisation's details, such as:

* Organisation name (mandatory)
* Organisation Identity registration (optional)
* Organisation Avatar / logo URL (optional)
* Organisation description (optional)
* Organisation website (optional)
* Terms of use URL (optional) and other “useful links” e.g., Terms of Service, Privacy, YouTube, and Support URLs
* Update button, disabled by default

## Invite Team members

You have arrived here after triggering the ```Invite User``` flow through the team screen. You can see a content block to add a new user that contains:

* Email address (Mandatory)
* Name (Optional)
* Role dropdown (Admin, Developer, etc.), defaulting as Developer
* Submit button

You can fill out the fields accordingly and submit the form to invite the new User to your Team and expect a success / error feedback message upon sending it. 
The form should also disappear after successful submission.
You can see the newly invited user in the user list, however, without a Role dropdown and clearly flagged with an “Invitation Pending” message.

</div>