---
title: "Definitions"
format: html
---

## Definition for key terms

This table provides a definition for the key terms used throughout this documentation.

| Term     | Definition                             |
|----------|----------------------------------------|
| Governance  | Governance is the process of making and enforcing decisions within an organization or ecosystem. It encompasses decision-making, rule-setting, and enforcement mechanisms to guide the functioning of an organization or ecosystem. Effective governance is essential for maintaining order, achieving objectives, and addressing the needs of the community or members within the ecosystem.<br>The CDSE Governance is currently managed under the authority of the European Space Agency and European Commission. The CDSE Governance indicates the conditions for the CDSE to federate with other platforms and to accept that a 3rd party service is referenced as Ecosystem Service |
| Federation  | Federation in information technology is a group of service providers agreeing upon standards of ICT operations in a collective fashion. The term may be used when describing the inter-operation of two distinct, formally disconnected, clouds or ICT systems that may have different internal structures or two service platforms operating on different cloud service providers. |
| Copernicus Data  | Copernicus data means data provided by the Copernicus Sentinels, including their metadata[^1]  |
| Copernicus Data Space Ecosystem (CDSE)  | Framework providing a set of core services with a configured free-to-the users capacity complemented with extended commercial offer, including cloud resources enabling 3rd party users to deploy and operate their own services and featuring additional interfaces allowing federation with other trusted platforms and frameworks. |
| Copernicus Data Space Ecosystem core services (Core Services)  | Free-to-the-user services available as part of the ecosystem allowing access and processing of any Sentinel data generated by ESA as well as additional Copernicus or EO data available as part of the public service.<br>The Copernicus Data Space Ecosystem core services are part of the Copernicus Space Component operations entrusted to the European Space Agency by the European Commission in the frame of the EU Copernicus Programme. |
| Copernicus Data Space Ecosystem Core Service Operator (“CDSE Service Operator” or “Service Operator”)  | The industrial consortium responsible for the operations of the Copernicus Data Space Ecosystem public core services, referred to as “Service Operator”.<br>The Service Operator offers in addition 3rd party services as part of the Ecosystem, including cloud resources, an extended core services capacity and additional commercial services. |
| Copernicus Data Space Ecosystem User  | Any user accessing the Copernicus Data Space Ecosystem. See table below for additional details.  |
| Copernicus Information  | Copernicus information means information generated by the Copernicus Thematic Services following processing or modelling, including their metadata.  |
| Data Holder (also being referred to as data provider)   | Data Holder means a legal entity or natural person executing control over data. This enables the Data Holder to define Data Usage Policies and provide access to its data. Data Holdership includes at least two major concepts:<br>- having the (technical) means and the responsibility to define Usage Contracts and Usage Policies, and to provide access to data; and<br>- having the (technical) means and the responsibility to define the Payment Model, including the model for reuse of data by 3rd parties.<br>In the frame of the CDSE, Data Holder is typically the Data Provider and uses the CDSE services managed by the Service Provider to make the data available under agreed and well-defined data access management and licensing conditions while retaining full rights on the data.  |
| Data User   | Data user means a natural or legal person who has lawful access to certain personal or non-personal data and has the right, including under Regulation (EU) 2016/679 in the case of personal data, to use that data for commercial or non-commercial purposes.<br>In the frame of the CDSE, Data User means in particular a natural or legal person accessing the open and free data available through the CDSE or any other data according to the associated specific licensing or commercial conditions.  |
| Ecosystem  | In this document the Ecosystem is made of the Ecosystem Services (including the CDSE e.g., Core Services, and Registered 3rd Party Services), the Ecosystem Federated Services (including e.g., federated Collaborative Services), the Ecosystem Federated Platforms and the Ecosystem users (accessing to any of the above). |
| Ecosystem Adopters Registry  | Services announced on the CDSE Portal as making use of the CDSE services and data to operate their services with different possible federation levels (no end-user services available). |
| Ecosystem Data  | Refers to all data available through the Ecosystem services.<br>It includes notably the Sentinel data available through the CDSE and Federated Copernicus Platforms and the Copernicus Services information available through the CDSE and Federated Copernicus Platforms/Services.<br>It includes data managed by 3rd party “Data Holders/Providers”, federated with the CDSE and available to registered CDSE users through all or some of the CDSE data access interfaces.   |
| Ecosystem Data Registry  | List of Ecosystem Data discoverable through the CDSE Portal and accessible to registered CDSE users. |
| Ecosystem Federated Platforms  | Federated Platforms/Services are partner Platforms/Services sharing common European values with the CDSE and offering data and/or services accessible to CDSE users through different federation functions and vice-versa.<br>Platforms/Services may offer a user registration service federated with the CDSE (or planned). Users registered and authenticated by these Platforms/Services are recognised as CDSE registered users when accessing the CDSE services.<br>Different types of federation are possible, including e.g.  openEO federation via the openEO Aggregator solution.<br>Federated Platforms typically offer services to each other’s user communities.<br>The federation of the CDSE with other Platform/Service shall be recognized and approved by ESA and the European Commission.  |
| Ecosystem Services  | Services accessible through the CDSE Portal or though the Ecosystem Federated Platforms. The Ecosystem Services include notably: CDSE Core Services, Federated Copernicus Services, Registered 3rd Party Services, and other Federated Platforms e.g., EU Services/Projects. |
| Ecosystem Services Registry   | List of Ecosystem Services accessible through the CDSE Portal. The Ecosystem Services Registry includes notably: CDSE Core Services, Federated EU Copernicus Services, Registered 3rd party services, and other Federated Platforms e.g., EU Services/Projects,” |
| Extended CDSE resources/capacity  | The free-to-the-user capacity available for CDSE Core services and for relevant 3rd Party Services, may be increased to answer specific user needs, either at no cost for the user for eligible users (e.g. Copernicus Services, Copernicus Collaborative entities, etc.) or on a commercial basis, providing extended services capacity or CDSE resources. |
| Free-to-the-user CDSE resources/capacity   | Public free-to-the-user services are those Ecosystem Services freely accessible and consumable by CDSE users.<br>The free-to-the-user capacity is associated to a configured user quota ensuring a fair access to the CDSE resources, which may be tailored according to the user typology under CDSE ESA & European Commission governance. |
| Onboarding  | In the frame of the CDSE, the Onboarding refers to the process by which interested parties deploy/operate their services/applications making use of the CDSE data and services. The Onboarding encompasses also the process to make 3rd party data available through the Ecosystem.<br>The Onboarding may involve different levels of integration or federation with the CDSE (e.g. the implementation of single-sign-on, identity management federation and data interfaces / APIs, etc.) in accordance with the needs of the 3rd party, ranging from registered 3rd parties, to federated services and ecosystem adopters.  |
| Participant to the Ecosystem / Ecosystem member  | User having accepted the Ecosystem Code of Conduct and having been acknowledged. |


[^1]: Space Regulation Regulation (EU) 2021/696 [https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex%3A32021R0696](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex%3A32021R0696) 


## Definition for key actors

This table provides a definition for the key actors in the Copernicus Data Space.

A user may simultaneously act as different Actor categories. 

| Ecosystem group      |  Ecosystem actor     |   Access Policy        |
|--------------------|--------------------|--------------------|
|   General User       |  Unregistered Users  |   Any user accessing the ecosystem services without previous registration (e.g., visualisation service, discovery service). |
|                      |  Registered Users    |   Any user accessing the ecosystem services after self-registering in the Copernicus Data Space Ecosystem.  |
|   Public User Eligible for access to extended CDSE resources          |   Registered Copernicus Services             |  Users self-registered in the Copernicus Data Space Ecosystem acting on behalf of a Copernicus Service.<br>A registration confirmation as Copernicus Service is provided by the European Commission.                 |
|                   |  Registered Collaborative Entities          | Users self-registered in the Copernicus Data Space Ecosystem acting on behalf of a Copernicus Collaborative Entity having signed a Collaborative Agreement with ESA.<br>A registration confirmation as Collaborative Entity is provided by ESA.                 |
|                   |  Registered International Partners              |  Users self-registered in the Copernicus Data Space Ecosystem acting on behalf of an International Entity having signed an International Agreement with the European Commission.<br>A registration confirmation as International Partner is provided by the European Commission.    |
|                   |  Registered European Union/Commission Bodies/ Authorities/Entities       |  Users self-registered in the Copernicus Data Space Ecosystem acting on behalf of an entitled European Union/Commission Body/Authority/Entity.<br>A registration confirmation is provided by the European Commission.             |
|  Data Processing User     |  General Data Processing User (Private Tenant User)   | General Registered Users consuming IaaS/PaaS services available through the CDSE federated services providers and making use of the existing services and functionalities to access the Ecosystem data.   |
|                   |  Public Data Processing User   |  “Public User eligible for access to extended CDSE resources” and granted by the European Commission to freely consume a predefined maximum amount of IaaS/PaaS resources, or of other Ecosystem Services resources, and benefiting from the existing services and functionalities to access the Ecosystem data and operate its own end-user services.                |
|  3rd Party Service     |  Registered 3rd Party Service        |   Users operating their services in a private tenant as part of the Ecosystem Services or in a platform federated with the CDSE, that have accepted the Ecosystem Code of Conduct and Terms & Conditions and are authorised by ESA and the European Commission to be included in the Ecosystem Services Registry of 3rd Party Services available to CDSE users.<br>Registered 3rd Party Service provide additional end-user services accessible through the “Ecosystem Services Registry” of the CDSE Portal visible to all CDSE users.<br>N.B. *The CDSE Service Operator acts as a Registered 3rd party service for the services it provides on a commercial basis.*         |
|                   |  Ecosystem Adopters              |   User agreeing to be included in the publicly visible CDSE list of Users/Services making use of the CDSE resources and services for their own operations.<br>Ecosystem Adopters do not offer services to CDSE registered users.             |
|                   |  Undisclosed 3rd Party Service              |   User operating their services in a private tenant using Ecosystem Services, while not registering themselves as users of the CDSE and therefore not publicly visible on the CDSE portal for other users, neither in the Ecosystem Services Registry.        |
|                   |  3rd Party Services retain full control of their services/applications deployed/operated in the ecosystem and relationship with their users wherever desired.                                
|  Federated Copernicus Services and other entitled EU Services/Projects                 |                |   Public Services or Collaborative Ground Segments which are part of the Copernicus family offering free-to-the-user services, onboarded on the CDSE with different levels of federation possible.<br>The Service information (products), always curated by the federated Copernicus Service itself, is available through the CDSE, and possibly available as well through a dedicated Portal of the Service.               |
|                   | Federated Copernicus Services and other entitled EU Services/Projects retain full control of their services/applications deployed/operated in the Ecosystem and relationship with their users wherever desired.               |                  |
| Federated Platform/Service           |  Federated Data Holder              |  Data Holder, possibly with its own user registration and authentication, that enables CDSE users to access its data through federated identity management or other federation mechanisms.                |
|                   | Integrated Data Holder               |  Data Holder, possibly with its own user registration and authentication, that enables CDSE users integrated access to its data through the CDSE e.g., using the CDSE catalogue, browser, and APIs.                 |
| Federated Copernicus Services and Other entitled EU Services/Projects             |                |  Public Services or Collaborative Ground Segments which are part of the Copernicus family offering free-to-the-user services, onboarded on the CDSE with different levels of federation possible.<br>The Service information (products), always curated by the federated Copernicus Service itself, is available through the CDSE, and possibly available as well through a dedicated Portal of the Service                |





