---
title: "Regulations and Policies"
format: html
---

## Applicable Regulations and Policies

| Theme            | Title                    | Reference       |
|------------------|--------------------------|-----------------|
| Data Privacy     | Regulation (EU) 2016/679 on the protection of natural persons with regard to the processing of personal data and on the free movement of such data (GDPR).               | [https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A02016R0679-20160504&qid=1532348683434](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A02016R0679-20160504&qid=1532348683434){target="_blank"} |
| Data Governance Act  | Regulation (EU) 2022/868 of the European Parliament and of the Council of 30 May 2022 on European data governance and amending Regulation (EU) 2018/1724 (Data Governance Act)               | [https://eur-lex.europa.eu/legal-content/en/TXT/?uri=CELEX%3A32022R0868](https://eur-lex.europa.eu/legal-content/en/TXT/?uri=CELEX%3A32022R0868){target="_blank"} |
| Data Act | Regulation (EU) 2023/2854 of the European Parliament and of the Council of 13 December 2023 on harmonised rules on fair access to and use of data and amending Regulation (EU) 2017/2394 and Directive (EU) 2020/1828 (Data Act)              | [http://data.europa.eu/eli/reg/2023/2854](http://data.europa.eu/eli/reg/2023/2854){target="_blank"} |
| Cloud Computing Policy  | The European Commission aims to provide European businesses and public authorities with access to secure, sustainable and interoperable cloud infrastructures and services.              | [https://digital-strategy.ec.europa.eu/en/policies/cloud-computing](https://digital-strategy.ec.europa.eu/en/policies/cloud-computing){target="_blank"} |
| Digital Market Act | Regulation 2022/1925, commonly referred to as the Digital Markets Act, is an EU regulation that aims to make the digital economy fairer and more contestable.               | [https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32022R1925&qid=1700125375248](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32022R1925&qid=1700125375248){target="_blank"} |
| Digital Services Act  | Regulation (EU) 2022/2065 sets clear and proportionate rules to protects consumers and their fundamental rights online, whilst fostering innovation, growth and competitiveness, and facilitating the scaling up of smaller platforms, SMEs and start-ups. The responsibilities of users, platforms, and public authorities are rebalanced according to European values, placing citizens at the centre.               | [https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32022R2065&qid=1700125375248](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX%3A32022R2065&qid=1700125375248){target="_blank"}  |

:  {tbl-colwidths="[20,50,30]"} 