---
title: "Ecosystem Services Categories"
format: html
---

The Ecosystem Services Registry is the user front-end to all services accessible through the CDSE. Registered Services are free to request the removal from the Ecosystem Services Registry at any time.<br> 
The Registry includes the following categories of services: 

## Core Services

Meaning CDSE Services operated by the CDSE Service Operator on behalf of ESA as entrusted by the European Commission.<br> 
Core Services are available open and free to users with a configured access capacity to ensure a fair access to the CDSE resources.<br> 
Core Services include notably: Access to the Sentinel-1/2/3/5P user level data, streamline data access interfaces, data discovery, data download, data visualisation as well as access to CCM coverage data sets in line with the applicable licence conditions.<br> 
For some of these services, the free-to-the-user capacity may be increased to answer specific user needs, either at no cost for the user for eligible users (e.g. Copernicus Services, Copernicus Collaborative entities, etc. within extended capacities) or on a commercial basis.

## Registered 3rd Party Services

Meaning Additional services, accessible to CDSE users under the 3rd Party governance, with different levels and types of integration/federation with the CDSE and fulfilling the conditions for being included in the Ecosystem Service Registry.<br> 
3rd party Services include any 3rd party service provided by the CDSE Service Operator (e.g., Creodias, Open Telekom Cloud) as well as any additional service operated by other parties accessible through the Ecosystem Services Registry.<br> 
The Ecosystem Services Registry provides access to the Registered 3rd Party Service own portal and information.<br>
As part of the CDSE governance, ESA and the European Commission may support Registered 3rd Party Services to offer a well-defined free-to-the-user capacity to CDSE users.<br> 
The following conditions are defined as part of the CDSE Governance for 3rd Party Services to be included in the Ecosystem Services Registry:

*	have adhered to the Ecosystem Code of Conduct and to the CDSE Terms & Conditions with the CDSE Service Provider 
*	use the cloud services available through the CDSE or through a federated platform
*	provide a minimum of free-to-the-user service capacity, or a service demonstration capability
*	have a public service price (unless the service is fully free-to-the-user).

## Federated Copernicus Services and Federated EU Services/Projects

Meaning Copernicus Services or EU Services/Projects onboarded or federated with the CDSE, with different possible federation levels, providing free Service information (products) to users.<br>
Depending on the desired level of federation, the CDSE provides registered CDSE users with direct access to the Service/Project information (products) through the standard CDSE services and interfaces, and the Ecosystem Services Registry provides access to the Service own portal and information.<br> 
The Service/project information (products) available through the CDSE are curated by the Copernicus Service/EU project information generator itself.<br> 
The federation of Copernicus Services and EU Services/Projects shall be recognized and approved by the European Commission.<br>

## Federated Collaborative Services

Meaning services managed by Copernicus Collaborative Ground Segment partners, onboarded or federated with the CDSE, with different possible federation levels, providing free Services to registered CDSE users.<br>
Depending on the desired level of federation, the CDSE provides registered CDSE users with direct access to the Service information through the standard CDSE services and interfaces, and the Ecosystem Services Registry provides access to the Service own portal and information.<br>
The Service information (products) available through the CDSE are curated by the Service information generator itself.<br>
The federation of Copernicus Collaborative Services shall be recognized and approved by ESA and the European Commission.

## Ecosystem Federated Platforms 

Partner Platforms/Services sharing common European values with the CDSE, and offering data and/or services accessible to CDSE users through different federation possibilities and vice-versa.<br>
Platforms/Services may offer a user registration service federated with the CDSE (or planned). Users registered and authenticated by these Platforms/Services are recognised as CDSE registered users when accessing the CDSE services.<br> 
Different types of federation are possible, including e.g.  openEO federation via the openEO Aggregator solution.<br>
Federated Platforms typically offer services to each other user communities.<br>
The federation of the CDSE with other Platform/Service shall be recognized and approved by ESA and the European Commission.

