---
title: "Ecosystem Services Onboarding"
format: html
---

## Ecosystem Services Onboarding principles

The Ecosystem Services Onboarding refers to the process by which registered users deploy and operate their applications or services making use of the Ecosystem resources and services, benefiting from an efficient access to the Ecosystem data, leading to e.g. registered 3rd Party Services, Federated Copernicus Services, Public or Commercial Adopters or Federated Collaborative Services.<br> 
3rd parties and other ecosystem users can use an autonomous or supported onboarding process and be integrated at any time.

The Service Operator team ensures that all information is openly available for 3rd parties to perform an autonomous onboarding.

The Service Operator team is also available to provide an “Onboarding Service” to accompany interested users on the journey from the first expression of interest to active service and data exchange in the Ecosystem with business partners. An accompanied onboarding can be initiated by raising a request in the CDSE help centre[^1].

The Onboarding service support is provided, e.g., in the form of consulting or coaching of the principles, interfaces and materials provided. The information, services, and documentation offered will be continuously enhanced.

The following key principles apply to the Ecosystem Services Onboarding process:

*	Services onboarded or federated with the CDSE retain full control, rights and governance of their data and services. 
*	The CDSE Service Operator will not claim any rights on any 3rd party onboarded data or services. 
*	Onboarded or federated services are welcome to participate to the development of open-source software made available in the Ecosystem.
*	Services onboarded shall adhere to the Ecosystem Code of Conduct and CDSE Terms & Conditions 

In the next section, we outline several steps that provide orientation for a comfortable entry into the Ecosystem.

[^1]: [https://helpcenter.dataspace.copernicus.eu/hc/en-gb/requests/new](https://helpcenter.dataspace.copernicus.eu/hc/en-gb/requests/new)

## Ecosystem Services Onboarding process

Interested entities may opt for different processes to onboard their applications / services / operations in the Ecosystem, with different levels of autonomy, from an autonomous self-onboarding process to a fully supported process.<br>
In addition, eligible public entities benefit from a dedicated onboarding to streamline the integration of CDSE services and to facilitate the end-user access to Copernicus data and information.<br> 
An important governance aspect is that 3rd parties always retain control, whether it follows an autonomous or a supported onboarding.

## Onboarding support for eligible public services

Public services eligible for a dedicated onboarding support are identified by the European Commission. 
The level of integration / federation with the Ecosystem and CDSE is defined by the service to be onboarded and the onboarding implementation plan jointly agreed between the public service, the Service Operator and ESA.<br> 
The onboarding support covers typically, but not limited to: 

*	Ingestion of service information/products in the CDSE Catalogue and Copernicus Browser, allowing CDSE registered users to discover and access the service offer.
*	Extended access to CDSE services, beyond the general user capacity, including access to the CDSE cloud services.
*	Optimisation of service workflows regarding access and processing of data available through the CDSE.
*	User identity management, allowing e.g. CDSE registered users to be recognised by the service.

**Optional Supported Onboarding Service**<br>
refer to the user support

