---
title: Evapotranspiration 2025-present (raster 300 m), global, 10-daily – version 1
---
## About
[Official documentation](https://land.copernicus.eu/en/products/evapotranspiration/evapotranspiration-2025-present-raster-300m-global-10-daily-version-1)

The Evapotranspiration product group provides global actual evapotranspiration (ETA) estimates at 300 m spatial resolution with a frequency of 10-daily for ET, E and T and at a daily frequency for H and LE, combining outputs from two modelling frameworks and an Ensemble model.

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_ETA_GLOBAL_300M_10DAILY_V1&clmsSelectedPath=Evapotranspiration&clmsSelectedCollection=COPERNICUS_CLMS_ETA_GLOBAL_300M_10DAILY_V1) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

`24fd5fde-b9db-44f1-a32b-e5dc3a0c5b9b`

## Date range

2025 - present

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|GFD|Per pixel average gap-filling distance (in days) for cloudy pixels in a given dekad. Unit in days|days|UINT8|0.0-60.0|1|0|
|FLAG|Per pixel annotation flag indicating quality or other limitations|-|UINT8|---|-|-|
|NOBS|Per pixel number of cloud free observations in a given dekad.|-|UINT8|0.0-11.0|1|0|
|E_STD|Per pixel standard deviation between TSEB-PT and ETLook model E. Unit: mm/day|mm/day|UINT8|0.0-20.0|1/10|0|
|T_STD|Per pixel standard deviation between TSEB-PT and ETLook model T. Unit: mm/day|mm/day|UINT8|0.0-20.0|1/10|0|
|ET_STD|Per pixel standard deviation between TSEB-PT and ETLook model ET. Unit: mm/day|mm/day|UINT8|0.0-20.0|1/10|0|
|E_ETLOOK|Soil evaporation calculated by the ETLook model. Unit: mm/day|mm/day|UINT8|0.0-20.0|1/10|0|
|E_TSEBPT|Soil evaporation calculated by the TSEB-PT model. Unit: mm/day|mm/day|UINT8|0.0-20.0|1/10|0|
|T_ETLOOK|Canopy transpiration calculated by the ETLook model. Unit: mm/day|mm/day|UINT8|0.0-20.0|1/10|0|
|T_TSEBPT|Canopy transpiration calculated by the TSEB-PT model. Unit: mm/day|mm/day|UINT8|0.0-20.0|1/10|0|
|ET_ETLOOK|Actual evapotranspiration calculated by the ETLook model. Unit: mm/day|mm/day|UINT8|0.0-20.0|1/10|0|
|ET_TSEBPT|Actual evapotranspiration calculated by the TSEB-PT model. Unit: mm/day|mm/day|UINT8|0.0-20.0|1/10|0|
|E_ENSEMBLE|Soil evaporation calculated by the Ensemble model. Unit: mm/day|mm/day|UINT8|0.0-20.0|1/10|0|
|T_ENSEMBLE|Canopy transpiration calculated by the Ensemble model. Unit: mm/day|mm/day|UINT8|0.0-20.0|1/10|0|
|ET_ENSEMBLE|Actual evapotranspiration calculated by the Ensemble model. Unit: mm/day|mm/day|UINT8|0.0-20.0|1/10|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/bio-geophysical-parameters/evapotranspiration/eta_global_300m_10daily_v1)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/Batch.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
