---
title: Burnt Area 2018 - present (raster 300 m), global, monthly - version 4
---
## About
[Official documentation](https://land.copernicus.eu/en/products/vegetation/burnt-area-v4-monthly-300m)

Maps burn scars, surfaces which have been sufficiently affected by fire to display significant changes in the vegetation cover (destruction of dry material, reduction or loss of green material) and in the ground surface (temporarily darker because of ash).

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_BURNT_AREA_MONTHLY_V4&clmsSelectedPath=Burnt%20Area&clmsSelectedCollection=COPERNICUS_CLMS_BURNT_AREA_MONTHLY_V4) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

`b8b617c6-182f-427e-a86c-23fc36ac6098`

## Date range

2018-present

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|BF|Fraction of pixel surface affected by fire at the day of the burn detection|-|INT16|0.0-1.0|1/1000|0|
|CP|Probability that the burn detection corresponds to an actual burn|-|INT16|0.0-1.0|1/1000|0|
|DOB|Day of burn in year (1-366), no burn (0) or flag (<0)|day|INT16|0.0-366.0|1|0|
|LFP|Probability that the fractional burned area is above 0.1|-|INT16|0.0-1.0|1/1000|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/bio-geophysical-parameters/vegetation/burnt-area/ba_global_300m_monthly_v4)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/Batch.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
