---
title: "Copernicus Marine Environment Monitoring Service (CMEMS)"
format:
  html:
    code-fold: true
execute:
  echo: false
  output: asis
jupyter: python3
---

```{python}
#| tags: [parameters]

constellation = "CMEMS"

```

The Copernicus Marine Environment Monitoring Service (CMEMS) provides open, free, regular and systematic reference data on the blue (physical), white (sea ice), and green (biogeochemical) state of the marine environment, as well as data on variability and dynamics across the global ocean and European seas.

Copernicus Data Space Ecosystem data catalogue provides resources for water analysis in all dimensions, from local to global and from visible to radar techniques.  The CMEMS products available via Copernicus Data Space Ecosystem platform are particularly dedicated to water application. 

Two main kinds of products are offered by Copernius Data Space Ecosystem: Near Real Time (NRT) and Reprocessed including climate analysis (REP).

:::{.callout-note}

Please be advised that access to this collection is exclusively available through S3 access. For further guidance on how to obtain this data, kindly refer to the [S3 access](../APIs/S3.html) page.

:::

{{< include _render_collections.qmd >}}