---
title: "Landsat-7"
format:
  html:
    code-fold: true
execute:
  echo: false
jupyter: python3
---

```{python}
#| tags: [parameters]

constellation = "Landsat-7"

```
The Landsat programme is a joint USGS and NASA-led enterprise for Earth observation that represents the world's longest running system of satellites for moderate-resolution optical remote sensing for land, coastal areas and shallow waters.

Landsat-7 has continued the goal of the Landsat programme to repeatedly image Earth's land and coastal areas in order to monitor changes to these areas over time. The satellite has continued to provide data continuity for the Thematic Mapper aboard Landsat-4 and 5, utilising an enhanced version of the instrument. 

The Enhanced Thematic Mapper Plus (ETM+) is the main instrument on board Landsat-7 and has been operational since 1999. It provides 30 m resolution for visible (VIS), near-infrared (NIR) and shortwave infrared (SWIR) as well as 60 m resolution for thermal infrared. Moreover, it adds a 15 m resolution panchromatic band (PAN).


{{< include _render_collections.qmd >}}