---
title: "Sentinel-1"
format:
  html:
    code-fold: true
execute:
  echo: false
jupyter: python3
---
<!-- ```{python}
#| tags: [parameters]

mission = "SENTINEL1"

``` -->


The [Sentinel-1 radar imaging mission](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-1){target="_blank"} is composed of a constellation of two polar-orbiting satellites providing continous all-weather, day and night imagery for Land and Maritime Monitoring. C-band synthentic aperture radar imaging has the advantage of operating at wavelenghts that are not obstructed by clouds or lack of illumination and therefore can acquire data during day or night under all weather conditions. With 6 days repeat cycle on the entire world and daily acquistions of sea ice zones and Europe's major shipping routes, Sentinel-1 ensures reliable data availability to support emergency services and applications requiring time series observations.

**The end of mission of the Sentinel-1B satellite has been declared in July 2022**
<br>On 23 December 2021, Copernicus Sentinel-1B experienced an anomaly related to the instrument electronics power supply provided by the satellite platform, leaving it unable to deliver radar data. Despite all investigations and recovery attempts, ESA and the European Commission had to announce that it is the end of the mission for Sentinel-1B. Copernicus Sentinel-1A remains fully operational. More information about the end of the mission for the Sentinel-1B satellite can be found on the webpage [Mission ends for Copernicus Sentinel-1B satellite](https://www.esa.int/Applications/Observing_the_Earth/Copernicus/Sentinel-1/Mission_ends_for_Copernicus_Sentinel-1B_satellite){target="_blank"}.
<br>In response to the loss of Sentinel-1B, **the mission observation scenario of Sentinel-1A was adjusted**, affecting the nominal global coverage frequency. An up-to-date overview of the observation scenario in place can be consulted on the webpage [Sentinel-1 Observation Scenario](https://sentinel.esa.int/web/sentinel/missions/sentinel-1/observation-scenario){target="_blank"}. Some regions are currently not observed by Sentinel-1. All regions that are still observed now have a repeat cycle of 12 under a one-satellite constellation scenario, which affects possible interferometric analyses.


Sentinel data products are made available systematically and free of charge to all data users including the general public, scientific and commercial users. 

[Data products](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-1/data-products){target="_blank"} are available in single polarisation for Wave mode and dual polarisation or single polarisation for SM, IW and EW modes.

{{< include _render_collections.qmd >}}

The table below indicates for each type of user level product, the format in which the data will be available, the access type (IAD or DAD), the spatial and temporal extent of the offer and from when the data will be available in the Copernicus Data Space Ecosystem. 
The data offer will gradually extend starting from January 2023 (an “*” indicates a temporary offer that will change when the target service offer becomes available within July 2023).

## Data Offer
### Already available (from January 2023)

|Product Type| Data access Description (\***\*) | Data Access Type | Spatial Extent | Temporal Extent | More Information | Available from |
|------------ | ---------------------- | ---------------------- | ------------ | ------------ | ------------| -----------|
|GRD | packed or unpacked | IAD (Immediately available data) | World | Oct-14 - Present| [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-1){target="_blank"}| Jan-23(*)|
|OCN | packed or unpacked | IAD | World | Dec-14 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-2){target="_blank"}| Jan-23(*)|
|SLC | packed or unpacked | IAD | Europe | Oct-14 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-1){target="_blank"}| Jan-23(*)|
|SLC | packed or unpacked | IAD | RoW (World with exception of Europe) | Feb-21 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-1){target="_blank"}| Jan-23(*)|
|L0 (RAW) | packed or unpacked | IAD | World | Jan-21 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-0){target="_blank"}| Jan-23(*)|
|L0 (RAW) | packed | DAD | World | Oct-14 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-0){target="_blank"}| Jan-23(*)|

(*) temporary offer available until the target service offer becomes available in July 2023.

### Available from July 2023

|Product Type| Data access Description| Data Access Type | Spatial Extent | Temporal Extent | More Information | Available from |
|------------ | ---------------------- | ---------------------- | ------------ | ------------ | ------------| -----------|
|GRD | SAFE with Cloud Optimized GeoTIFF (COG_SAFE) (packed or unpacked) | IAD (Immediately available data) | World | Oct-14 - Present| [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-1){target="_blank"}| Jul-23 (\* ** \*)|
|GRD | original SAFE (packed) | IAD | World | Last 1 year| [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-1){target="_blank"}| Jul-23 (\* *** \*)|
|GRD | original SAFE (packed) | DAD (Deferred available data) | World | Oct-14 - Present-1 year| [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-1){target="_blank"}| Jul-23|
|OCN | packed or unpacked | IAD | World | Dec-14 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-2){target="_blank"}| Jan-23|
|SLC | packed or unpacked | IAD | World | Oct-14 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-1){target="_blank"}| Jul-23|
|L0 (RAW) | packed or unpacked | IAD | Europe | Oct-14 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-0){target="_blank"}| Jul-23|
|L0 (RAW) | packed or unpacked | IAD | RoW | Last 1 year | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-0){target="_blank"}| Jul-23|
|L0 (RAW) | packed | DAD | World | Oct-14 - Present-1 year | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-0){target="_blank"}| Jan-23(*)|

(\***\*) Conversion of Sentinel-1 GRD products to the SAFE with Cloud Optimized GeoTIFF (COG_SAFE) format will begin in May 2023. The newest products will be converted and available first, and older products will be added gradually until the entire archive is converted. More details about how the original Sentinel-1-GRD products were converted to COG_SAFE format are [available below](@convert-cogsafe) .

(\****\*) Original Sentinel-1 GRD products older than one year will be accessible with deferred availability (DAD), while the entire archive of COG_SAFE products will be available immediately (IAD). In case original Sentinel-1 GRD products would be needed with immediate access, users can convert COG_SAFE products to the original SAFE products using [this tool](https://github.com/eu-cdse/utilities/blob/main/COG2GRD.sh).  

## [How to search for COG_SAFE products with OData API?]{#search-cogsafe-odata}
The Sentinel-1 GRD COG_SAFE products can be filtered by the Odata API query using three methods:

### 1.	Filtering ‘COG.SAFE’ substring in the product name:

Example of query:

[https://catalogue.dataspace.copernicus.eu/odata/v1/Products?$filter=contains(name,%27COG%27)%20and%20ContentDate/Start%20gt%202022-05-03T00:00:00.000Z%20and%20ContentDate/Start%20lt%202022-05-21T00:00:00.000Z](https://catalogue.dataspace.copernicus.eu/odata/v1/Products?$filter=contains(name,%27COG%27)%20and%20ContentDate/Start%20gt%202022-05-03T00:00:00.000Z%20and%20ContentDate/Start%20lt%202022-05-21T00:00:00.000Z)

### 2.	Using proper data type with “-COG” suffix. One of: S1_GRDF_1S-COG,S2_GRDF_1S-COG,S3_GRDF_1S-COG,S4_GRDF_1S-COG,S5_GRDF_1S-COG,S6_GRDF_1S-COG,S1_GRDH_1S-COG,S2_GRDH_1S-COG,S3_GRDH_1S-COG,S4_GRDH_1S-COG,S5_GRDH_1S-COG,S6_GRDH_1S-COG,S1_GRDM_1S-COG,S2_GRDM_1S-COG,S3_GRDM_1S-COG,S4_GRDM_1S-COG,S5_GRDM_1S-COG,S6_GRDM_1S-COG,IW_GRDH_1S-COG,IW_GRDM_1S-COG,EW_GRDH_1S-COG,EW_GRDM_1S-COG,WV_GRDM_1S-COG

Example of query:

[https://catalogue.dataspace.copernicus.eu/odata/v1/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name%20eq%20%27productType%27%20and%20att/OData.CSC.StringAttribute/Value%20eq%20%27IW_GRDH_1S-COG%27)%20and%20ContentDate/Start%20gt%202022-05-03T00:00:00.000Z%20and%20ContentDate/Start%20lt%202022-05-21T04:00:00.000Z&$top=10](https://catalogue.dataspace.copernicus.eu/odata/v1/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name%20eq%20%27productType%27%20and%20att/OData.CSC.StringAttribute/Value%20eq%20%27IW_GRDH_1S-COG%27)%20and%20ContentDate/Start%20gt%202022-05-03T00:00:00.000Z%20and%20ContentDate/Start%20lt%202022-05-21T04:00:00.000Z&$top=10)

### 3.	Filtering 'GRD' substring in product name and "origin" attribute equal "CLOUDFERRO".

Example of query:

[https://catalogue.dataspace.copernicus.eu/odata/v1/Products?$filter=contains(name,%27GRD%27)%20and%20Attributes/OData.CSC.StringAttribute/any(att:att/Name%20eq%20%27origin%27%20and%20att/OData.CSC.StringAttribute/Value%20eq%20%27CLOUDFERRO%27)%20and%20ContentDate/Start%20gt%202022-05-03T00:00:00.000Z%20and%20ContentDate/Start%20lt%202022-05-03T04:00:00.000Z&$top=10](https://catalogue.dataspace.copernicus.eu/odata/v1/Products?$filter=Attributes/OData.CSC.StringAttribute/any(att:att/Name%20eq%20%27productType%27%20and%20att/OData.CSC.StringAttribute/Value%20eq%20%27IW_GRDH_1S-COG%27)%20and%20ContentDate/Start%20gt%202022-05-03T00:00:00.000Z%20and%20ContentDate/Start%20lt%202022-05-21T04:00:00.000Z&$top=10)

## [How to search for COG_SAFE products in the Browser?]{#search-cogsafe-browser} 

There are two separate options available for Sentinel-1 GRD products. Selecting the “ Level-1 GRD COG” option under Sentinel-1 will return COG_SAFE products while option “Level-1 GRD” will return original GRD products. If you would like to search for both type of products, select both options.

## [How were original Sentinel-1 GRD products converted to COG_SAFE products?]{#convert-cogsafe}

The following changes were made during the conversion of original Sentinel-1 GRD products to COG_SAFE products:

1. All GeoTiff files available in the measurements folder were converted to cloud optimized GeoTIFF format with the gdal command:

```{bash}
gdal_translate -of COG -a_nodata 0 -co OVERVIEW_COUNT=6 -co BLOCKSIZE=1024 -co BIGTIFF=NO -co OVERVIEW_RESAMPLING=RMS -co COMPRESS=ZSTD -co NUM_THREADS=ALL_CPUS -mo GRD_ORIGINAL_HEADER_SIZE=<original_header_size> -mo GRD_ORIGINAL_FOOTER_SIZE=<original_footer_size> <input_tiff>.tiff <input_tiff>-cog.tiff
```

More information about what these options mean can be found in the [GDAL official documentation](https://gdal.org/programs/gdal_translate.html). Note that the output filename has a suffix “-cog”, which indicates that the files were converted to COGs.

2. A suffix “_COG” was added to the name of the product and a new CRC code was calculated. For example, the original product

S1A_IW_GRDH_1SDV_20230206T165050_20230206T165115_047118_05A716**_53C5**.safe became S1A_IW_GRDH_1SDV_20230206T165050_20230206T165115_047118_05A716**_74F9_COG**.safe.

3. Manifest file was adjusted so that it reflects these changes:

  a. `safe:processing` element with a name="COG Conversion" was added. It contains metadata about the conversion and includes the name of the original product under `safe:resource` child element.

  b. `dataObject` elements, which describe the measurements files, have updated values for “size”, “href”, “checksum”.

<!--|Product Type| File Description| Data Access Type | Spatial Extent | Temporal Extent | More Information | Available from |
|------------ | ---------------------- | ---------------------- | ------------ | ------------ | ------------| -----------|
|GRD | packed, original SAFE | IAD (Immediately available data) | World | Last 1 month | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-1){target="_blank"}| Jan-23|
|GRD | unpacked, original SAFE | IAD | World | Jun-14 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-1){target="_blank"}| Jan-23(*)|
|GRD | unpacked, SAFE with Cloud Optimized GeoTIFF | IAD | World | Jun-14 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-1){target="_blank"}| Jul-23|
|GRD | packed, original SAFE | IAD | World | Last 1 year | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-1){target="_blank"}| Jul-23|
|GRD | packed, original SAFE | DAD (Deferred available data) | World | Jun-14 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-1){target="_blank"}| Jul-23|
|OCN | packed | IAD | World | Last 1 month | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-2){target="_blank"}| Jan-23|
|OCN | unpacked | IAD | World | Dec-14 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-2){target="_blank"}| Jan-23|
|SLC | packed | IAD | Europe | Last 1 month | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-1){target="_blank"}| Jan-23|
|SLC | unpacked | IAD | Europe | Oct-14 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-1){target="_blank"}| Jan-23(*)|
|SLC | unpacked | IAD | RoW (World with exception of Europe) | Feb-21 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-1){target="_blank"}| Jan-23(*)|
|SLC | unpacked | IAD | World | Oct-14 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-1){target="_blank"}| Jul-23|
|SLC | packed | DAD | World | Oct-14 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-1){target="_blank"}| Jul-23|
|L0 (RAW) | packed | IAD | World | Last 1 month | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-0){target="_blank"}| Jan-23|
|L0 (RAW) | unpacked | IAD | World | Jan-21 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-0){target="_blank"}| Jan-23(*)|
|L0 (RAW) | packed or unpacked | IAD | Europe | Oct-14 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-0){target="_blank"}| Jul-23|
|L0 (RAW) | packed or unpacked | IAD | RoW | Last 1 year| [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-0){target="_blank"}| Jul-23|
|L0 (RAW) | packed | DAD | World | Oct-14 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-0){target="_blank"}| Jan-23(*)|
|L0 (RAW) | packed | DAD | World | Oct-14 - Present - 1 year | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-0){target="_blank"}| Jul-23|
|L0 (RFC) | packed | IAD | World | Last 2 weeks | [Details](https://sentinels.copernicus.eu/web/sentinel/user-guides/sentinel-1-sar/product-types-processing-levels/level-0){target="_blank"}| Oct-23|

(*) temporary offer available until the target service offer becomes available in July 2023.-->

