---
title: "Sentinel-3"
format:
  html:
    code-fold: true
execute:
  echo: false
jupyter: python3
---
```{python}
#| tags: [parameters]

mission = "Sentinel-3"

```

The main objective of the[Copernicus Sentinel-3 mission](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3){target="_blank"} is to measure sea surface topography, sea and land surface temperature, and ocean and land surface colour with high accuracy and reliability to support ocean forecasting systems, environmental monitoring and climate monitoring. The mission definition is driven by the need for continuity in provision of ERS, ENVISAT and SPOT vegetation data, with improvements in instrument performance and coverage.

{{< include _render_collections.qmd >}}


## Collections

## Data Offer

### Full Archive - immediate access

### Full Archive - Deferred access


|Product Type| File Description| Data Access Type | Spatial Extent | Temporal Extent | More Information | Available from |
|------------ | ---------------------- | ---------------------- | ------------ | ------------ | ------------| -----------|
|OLCI Level-1 NTC (Non Time Critical) | packed or unpacked | IAD (Immediately available data) | World | Mar-16 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/olci){target="_blank"}| Jan-23|
|OLCI Level-1 NRT (Near Real Time) | packed or unpacked | IAD | World |Last 1 year | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/olci){target="_blank"}| Jan-23|
|OLCI Level-2 NTC | packed or unpacked | IAD | World | Mar-16 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/olci){target="_blank"}| Jan-23|
|OLCI Level-2 NRT | packed or unpacked | IAD | World | Last 1 year | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/olci){target="_blank"}| Jan-23|
|OLCI Level-0(*) | packed | DAD (Deferred available data) | World | Feb-16 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/olci){target="_blank"}| Jul-23|
|SLSTR Level-1 NTC | packed or unpacked | IAD | World | Mar-16 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/slstr){target="_blank"}| Jan-23|
|SLSTR Level-1 NRT  | packed or unpacked | IAD | World | Last 1 year | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/slstr){target="_blank"}| Jan-23|
|SLSTR Level-2 NTC | packed or unpacked | IAD | World | Mar-16 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/slstr){target="_blank"}| Jan-23|
|SLSTR Level-2 NRT | packed or unpacked | IAD | World | Last 1 year | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/slstr){target="_blank"}| Jan-23|
|SLSTR Level-0(*) | packed | DAD | World | Feb-16 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/slstr){target="_blank"}| Jul-23|
|SRAL Level-1 NTC | packed or unpacked | IAD | World | Mar-16 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/altimetry){target="_blank"}| Jan-23|
|SRAL Level-1 STC (Short Time Critical) | packed or unpacked | IAD | World | Last 1 month | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/altimetry){target="_blank"}| Jan-23|
|SRAL Level-1 NRT | packed or unpacked | IAD | World | Last 1 year | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/altimetry){target="_blank"}| Jan-23|
|SRAL Level-2 NTC | packed or unpacked | IAD | World | Mar-16 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/altimetry){target="_blank"}| Jan-23|
|SRAL Level-2 STC | packed or unpacked | IAD | World | Last 1 month | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/altimetry){target="_blank"}| Jan-23|
|SRAL Level-2 NRT | packed or unpacked | IAD | World | Last 1 year | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/altimetry){target="_blank"}| Jan-23|
|SRAL Level-0(*) | packed | DAD | World | Feb-16 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/altimetry){target="_blank"}| Jul-23|
|SYN Level-2 NTC | packed or unpacked | IAD | World | Mar-16 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/synergy){target="_blank"}| Jan-23|
|SYN Level-2 STC | packed or unpacked | IAD | World | Last 1 month | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/synergy){target="_blank"}| Jan-23|

(*) Access restrictions may apply

<!--
|Product Type| File Description| Data Access Type | Spatial Extent | Temporal Extent | More Information | Available from |
|------------ | ---------------------- | ---------------------- | ------------ | ------------ | ------------| -----------|
|OLCI Level-1 NRT & NTC (Near Real Time & Non Time Critical) | packed | IAD (Immediately available data) | World | Last 1 month | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/olci){target="_blank"}| Jan-23|
|OLCI Level-1 NTC | unpacked or packed | IAD (Immediately available data) | World | Mar-16 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/olci){target="_blank"}| Jan-23|
|OLCI Level-1 NRT | unpacked | IAD | World |Last 1 month | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/olci){target="_blank"}| Jan-23|
|OLCI Level-2 NRT & NTC | packed | IAD | World | Last 1 month | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/olci){target="_blank"}| Jan-23|
|OLCI Level-2 NTC | unpacked | IAD | World | Mar-16 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/olci){target="_blank"}| Jan-23|
|OLCI Level-2 NRT | unpacked | IAD | World | Last 1 month | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/olci){target="_blank"}| Jan-23|
|OLCI Level-0(*) | packed | DAD | World | Feb-16 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/olci){target="_blank"}| Jul-23|
|SLSTR Level-1 NRT & NTC | packed | IAD | World | Last 1 month | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/slstr){target="_blank"}| Jan-23|
|SLSTR Level-1 NTC | unpacked | IAD | World | Mar-16 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/slstr){target="_blank"}| Jan-23|
|SLSTR Level-1 NRT  | unpacked | IAD | World | Last 1 month | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/slstr){target="_blank"}| Jan-23|
|SLSTR Level-2 NRT & NTC | packed | IAD | World | Last 1 month | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/slstr){target="_blank"}| Jan-23|
|SLSTR Level-2 NTC | unpacked | IAD | World | Mar-16 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/slstr){target="_blank"}| Jan-23|
|SLSTR Level-2 NRT | unpacked | IAD | World | Last 1 month | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/slstr){target="_blank"}| Jan-23|
|SLSTR Level-0(*) | packed | DAD | World | Feb-16 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/slstr){target="_blank"}| Jul-23|
|SRAL Level-1 NRT & NTC | packed | IAD | World | Last 1 month | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/altimetry){target="_blank"}| Jan-23|
|SRAL Level-1 NTC | unpacked | IAD | World | Mar-16 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/altimetry){target="_blank"}| Jan-23|
|SRAL Level-1 STC (Short Time Critical) | unpacked | IAD | World | Last 1 month | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/altimetry){target="_blank"}| Jan-23|
|SRAL Level-1 NRT | unpacked | IAD | World | Feb-22 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/altimetry){target="_blank"}| Jan-23|
|SRAL Level-2 NRT & STC & NTC | packed | IAD | World | Last 1 month | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/altimetry){target="_blank"}| Jan-23|
|SRAL Level-2 NTC | unpacked | IAD | World | Mar-16 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/altimetry){target="_blank"}| Jan-23|
|SRAL Level-2 STC | unpacked | IAD | World | Last 1 month | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/altimetry){target="_blank"}| Jan-23|
|SRAL Level-2 NRT | unpacked | IAD | World | Last 1 month | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/altimetry){target="_blank"}| Jan-23|
|SRAL Level-0(*) | packed | DAD | World | Feb-16 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/altimetry){target="_blank"}| Jul-23|
|SYN Level-2 NTC | unpacked | IAD | World | Mar-16 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/synergy){target="_blank"}| Jan-23|
|SYN Level-2 STC | unpacked | IAD | World | Last 1 month | [Details](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-3/data-products/synergy){target="_blank"}| Jan-23|

(*) Access restrictions may apply-->
