---
title: "Sentinel-5P"
format:
  html:
    code-fold: true
execute:
  echo: false
jupyter: python3
---
```{python}
#| tags: [parameters]

mission = "SENTINEL5P"


```
{{< include _render_collections.qmd >}}

## Description
The [Copernicus Sentinel-5 Precursor](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-5p){target="_blank"} mission is the first Copernicus mission dedicated to monitoring our atmosphere. 

The main objective of the Copernicus Sentinel-5P mission is to perform atmospheric measurements with high spatio-temporal resolution, to be used for air quality, ozone & UV radiation, and climate monitoring & forecasting.

There are [different data products](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-5p/data-products){target="_blank"} associated with the three levels of TROPOMI processing: Level-0, Level-1B and Level-2.
<br>
<br>
The table below indicates for each type of user level product, the access type (IAD or DAD), the spatial and temporal extent of the offer and from when the data will be available in the Copernicus Data Space Ecosystem.<br> 
The table includes as well an overview of the planned Sentinel engineering data availability.



## Data Offer
|Product Type| File Description| Data Access Type | Spatial Extent | Temporal Extent | More Information | Available from |
|------------ | ---------------------- | ---------------------- | ------------ | ------------ | ------------| -----------|
|Level-1B NTC (Non Time Critical) | packed or unpacked | IAD (Immediately available data) | World | Apr-18 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/technical-guides/sentinel-5p/products-algorithms){target="_blank"}| Jan-23|
|Level-2 NTC | packed or unpacked | IAD | World | Apr-18 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/technical-guides/sentinel-5p/products-algorithms){target="_blank"}| Jan-23|
|Level-2 NRT(Near real Time) | packed or unpacked | IAD | World | Last 1 month | [Details](https://sentinels.copernicus.eu/web/sentinel/technical-guides/sentinel-5p/products-algorithms){target="_blank"}| Jan-23|
|Level-0(*) | packed | DAD | World | Apr-18 - Present | [Details](https://sentinels.copernicus.eu/web/sentinel/technical-guides/sentinel-5p/products-algorithms){target="_blank"}| Jul-23|

(*) Access restrictions may apply. 
