---
title: "Derived products & Processing options "
format:
  html:
    code-fold: true
jupyter: python3
---

Sentinel-1 data can be accessed and processed in different ways within Copernicus Data Space Ecosystem. Below we have compiled an overview of all the options to help you decide which one to use.

## [Sentinel-1 RTC](https://documentation.dataspace.copernicus.eu/Data/Additional.html#sentinel-1-rtc){target="_blank"} 
[Sentinel-1 RTC](https://documentation.dataspace.copernicus.eu/Data/Additional.html#sentinel-1-rtc){target="_blank"} (Radiometric Terrain Correction) SAR Backscatter is a product processed from Sentinel-1 GRD data and compliant with [CEOS Analysis Ready Data for Land (CARD4L) specifications](https://ceos-dev.ceos.org/ard/){target="_blank"} for Normalised Radar Backscatter (NRB) products. Orthorectification is based on Copernicus DEM and no speckle filtering is applied. ([Additional product information](https://sentinels.copernicus.eu/web/sentinel/sentinel-1-ard-normalised-radar-backscatter-nrb-product){target="_blank"})

## Copernicus Sentinel-1 Mosaics

Sentinel-1 GRD monthly and yearly mosaics (available soon).

It is planned that mosaics will be processed with the following Sentinel Hub processing options:

- Orthorectification with Copernicus 10m/30m DEM
- Radiometric Terrain Correction
- No speckle filtering applied 

## [Sentinel Hub processing options](https://documentation.dataspace.copernicus.eu/APIs/SentinelHub/Data/S1GRD.html#processing-options){target="_blank"} 

Sentinel Hub offers the following processing options in the [Sentinel-1 GRD processing chain](https://documentation.dataspace.copernicus.eu/APIs/SentinelHub/Data/S1GRD.html#processing-chain){target="_blank"}:

- [Backscatter coefficients](https://documentation.dataspace.copernicus.eu/APIs/SentinelHub/Data/S1GRD.html#processing-options){target="_blank"}:

    - beta0
    - sigma0
    - gamma0 (ellipsoid)
    - gamma0 (terrain) &rarr; **gamma0 RTC can only be performed if orthorectification is enabled**

- [Lee Speckle Filtering](https://documentation.dataspace.copernicus.eu/APIs/SentinelHub/Data/S1GRD.html#processing-options){target="_blank"} applied on source data after calibration and noise removal
- [Orthorectification](https://documentation.dataspace.copernicus.eu/APIs/SentinelHub/Data/S1GRD.html#processing-options){target="_blank"} with Range-Doppler terrain correction using one of the following DEMs:

    - Copernicus 10m/30m DEM (10m resolution inside [39 European states](https://spacedata.copernicus.eu/collections/copernicus-digital-elevation-model){target="_blank"} including islands and 30m elsewhere.)
    - Copernicus 30m DEM
    - Copernicus 90m DEM 

## [CloudFerro processing options](https://documentation.dataspace.copernicus.eu/APIs/On-Demand%20Production%20API.html){target="_blank"} 

CloudFerro offers CARD-BS and COH6/COH12 products as a [service on demand](https://documentation.dataspace.copernicus.eu/APIs/On-Demand%20Production%20API.html){target="_blank"}: 

- [Sentinel-1 (CARD-BS) BackScatter](https://documentation.dataspace.copernicus.eu/Data/Additional.html#sentinel-1-card-bs){target="_blank"}

    - This processing option contains gamma0 geometric terrain correction (orthorectification), which is identical to the gamma0 (ellipsoid) backscatter coefficient with orthorectification option in Sentinel Hub processing options. No Radiometric Terrain Correction (RTC) is applied to this product. 
    - [Additional information](https://creodias.eu/eodata/sentinel-1/sentinel-1-l2-backscatter-bs/){target="_blank"}.

- [Sentinel-1 (CARD-COH) Coherence](https://documentation.dataspace.copernicus.eu/APIs/On-Demand%20Production%20API.html){target="_blank"}

    - The Sentinel-1 CARD COH (Copernicus Analysis Ready Data Coherence) processor generates a Sentinel-1 Level 2 product describing the coherence of a pair of images - 12 days apart. Concurrently, a terrain-correction (using DEM) is performed. 
    - [Additional information](https://creodias.eu/eodata/sentinel-1/sentinel-1-l3-bs-monthly-com/){target="_blank"}.

## openEO processing options 

openEO provides the **[sar_backscatter()](https://processes.openeo.org/draft/#sar_backscatter){target="_blank"}** method to process, calibrate and normalise Sentinel-1 radar backscatter products with the following processing options:

- **sigma0-ellipsoid**: ground area computed with ellipsoid earth model
- **sigma0-terrain**: ground area computed with terrain earth model &rarr; **sigma0 RTC**

For orthorectification processes, the method utilises the Copernicus 30m DEM.
