---
title: "Sentinel-2"
format:
  html:
    code-fold: true
execute:
  echo: false
  output: asis
jupyter: python3

---
```{python}
#| tags: [parameters]

constellation = "Sentinel-2"

```
The [Copernicus Sentinel-2 mission](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-2){target="_blank"} comprises a land monitoring constellation of two polar-orbiting satellites placed in the same sun-synchronous orbit, phased at 180° to each other. It aims at monitoring variability in land surface conditions, and its wide swath width (290 km) and high revisit time (10 days at the equator with one satellite, and 5 days with 2 satellites which results in 2-3 days at mid-latitudes) will support monitoring of Earth's surface changes.

Each [Sentinel-2 products](https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-2/data-products){target="_blank"} is composed of approximately 110x110 km tiles in cartographic geometry (UTM/WGS84 projection). Earth is subdivided on a predefined set of tiles, defined in UTM/WGS84 projection and using a 100 km step. However, each tile has a surface of 110x110 km² in order to provide large overlap with the neighbouring.

The Sentinel-2 L2A collection within the Copernicus Data Space Ecosystem originates from three sources: 

**(1)** operational Copernicus processing, i.e. data previously accessible on the Copernicus Open Access Hub (formerly known as Sentinels Scientific Data Hub);
 
**(2)** reprocessing of the L2A archive from 2015 until the end of 2021 [(Collection 1)](https://sentinel.esa.int/web/sentinel/sentinel-data-access/sentinel-products/sentinel-2-data-products/collection-1-level-2a){target="_blank"}, and ;

**(3)** data generated by CloudFerro using various versions of the publicly available [Sen2Cor processor](https://step.esa.int/main/snap-supported-plugins/sen2cor/){target="_blank"}. 

These products can be differentiated by the [OData](https://documentation.dataspace.copernicus.eu/APIs/OData.html#query-by-attributes){target="_blank"} and [OpenSearch](https://catalogue.dataspace.copernicus.eu/resto/api/collections/Sentinel2/describe.xml){target="_blank"} **(origin)** attribute (ESA or CloudFerro) and by the **'processingBaseline'** attribute.

The current state of the archive of the Sentinel-L2A data is as follows:

+-------------------------------+-----------------------------------------------------------------------------------------------------+
| Date                          | Baseline Availability                                                                               |
+===============================+=====================================================================================================+
| 29/04/2022 - now              | - Baseline 509 (originating from Copernicus Open Access Hub)                                        |
|                               | - Baseline 99.99 (generated by CloudFerro)                                                          |
+-------------------------------+-----------------------------------------------------------------------------------------------------+
| 25/01/2022 - 06/12/2022       | - Baseline 4.00 (originating from Copernicus Open Access Hub)                                       |
|                               | - Baseline 99.99 (generated by CloudFerro)                                                          |
+-------------------------------+-----------------------------------------------------------------------------------------------------+
| 30/03/2021 - 25/01/2022       | - Baselines 3.00 3.01 (originating from Copernicus Open Access Hub)                                 |
|                               | - Baseline 99.99 (generated by CloudFerro)                                                          |
|                               | - Baseline 5.00 (originating from the Sentinel-2 Collection 1)                                      |
+-------------------------------+-----------------------------------------------------------------------------------------------------+
| 04/07/2015 - 30/06/2021       | - Baselines (2.01-2.13) originating from Copernicus Open Access Hub and generated by CloudFerro     |
|                               | - Baseline 2.14 originating from Copernicus Open Access Hub                                         |
|                               | - Baseline 5.00 (originating from the Sentinel-2 Collection 1)                                      |
+-------------------------------+-----------------------------------------------------------------------------------------------------+


The Sentinel-2 Collection 1 (reprocessed data) featuring processing baseline 5.00 is gradually ingested into the Copernicus Data Space Ecosystem. This ingestion should be completed in the Q1 2024. **The products with older processing baselines** will be available together with **the products with baseline 5.00**, for a duration of at least 6 more months (until Q3 2024).

{{< include _render_collections.qmd >}}

<!-- Ideas to further include (step by step):

* links to openEO
* link to 'parent collection'? For instance, L2A links to L1C??
* how to separate usable collections from engineering products?? -->