---
title: Lake Ice Extent global 500m version 2
---
## About
[Official documentation](https://land.copernicus.eu/en/products/water-bodies/lake-ice-extent-global-500m_v2)

On a daily basis classifies pixels in Global freshwater bodies into 1) Snow-covered ice, 2) Partially snow-covered or snow-free ice, 3) Open water, and 4) Cloud. The data is updated in near-real time with the spatial resolution of 500 m and with a temporal extent from July 2025 to present

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_LIE_500M_DAILY_V2&clmsSelectedPath=River%20and%20Lake%20Ice%20Extent&clmsSelectedCollection=COPERNICUS_CLMS_LIE_500M_DAILY_V2) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

`1a9d1719-03f8-47d6-911b-bc683d1268bd`

## Date range

2025-present

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|LIE|A classification of lake ice state, with the following classes: Snow-covered ice, Partially snow-covered or snow-free ice, Open water, Cloud.|-|UINT8|10-70|1|0|
|P|GMM predicted posterior probability of the most likely class|%|UINT8|0-100|1|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/bio-geophysical-parameters/water-bodies/river-and-lake-ice-extent/lie_global_500m_daily_v2)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or “custom script”) is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/Batch.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Utilities.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
