---
title: LIE 2021-present (raster 500 m), Northern Hemisphere, daily – version 1
collection: ee9f160b-03f8-437b-812f-ad386d85f2af
---
## About
[Official documentation](https://land.copernicus.eu/en/products/water-bodies/lake-ice-extent-northern-hemisphere-500m)

Classifies, in pixels, inland/freshwater bodies

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_LIE_500M_DAILY_V1&clmsSelectedPath=River%20and%20Lake%20Ice%20Extent&clmsSelectedCollection=COPERNICUS_CLMS_LIE_500M_DAILY_V1) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

```default
ee9f160b-03f8-437b-812f-ad386d85f2af
```

## Date range

2021 - present

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|LIE|Classification of lake ice extent|-|INT16|10.0-70.0|1|0|
|P|Predicted Gaussian Mixture Model|%|INT16|0.0-100.0|1|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/bio-geophysical-parameters/water-bodies/river-and-lake-ice-extent/lie_northernhemisphere_500m_daily_v1)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/BatchV2.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
