---
title: "OpenSearch"
format:
  html:
    code-fold: true
jupyter: python3

---

The OpenSearch catalogue allows you to search through Copernicus data using a standardized web service. The [OpenSearch specification](https://github.com/dewitt/opensearch/blob/master/opensearch-1-1-draft-6.md){target="_blank"} can be consulted for technical details of the standard. This web service returns results as GeoJSON feature collections. Each feature in the collection represents an earth observation 'product', with references to where the actual data can be found.

We remark that this version does not implement the OGC Opensearch standard, and a migration from other API's named OpenSearch may require significant modifications. It mainly offers compatibility for existing users of a similar API on the CreoDIAS and Wekeo platforms, and with client side tools and workflows that have implemented support for this API. For new users looking for a more standardized API, a [STAC](https://stacspec.org){target="_blank"} alternative is being developed.

## Using OpenSearch interface to query Data Catalogue

Due to the fact that offset is not a recommended form of searching repository pages, we had to implement limit to a maximum of 200k.
The requests over the limit will be rejected with the code 400.
We encourage you to limit your inquiries by geographic or temporal area.

All queries may be executed as simple HTTP-Get calls, by typing the query in web browser address line, by using any HTTP client, e.g. curl or wget, or from inside of users' program. The database is accessible free and anonymously (open for anonymous access for everyone, no authorization is used) It may be accessed both from the internal network (virtual machines in Creodias) and from outside, e.g. your home computer. Note, that the actual EO data themselves are restricted to authorized users, only the Data Catalogue is open.

### General Rules

The queries produce results in JSON format. Base url:

[http://catalogue.dataspace.copernicus.eu/resto/api/collections/search.json?](http://catalogue.dataspace.copernicus.eu/resto/api/collections/search.json?)

Most queries are case-sensitive.
