---
title: Upcoming changes
---

This is the list of upcoming changes to Catalog APIs.

## OpenSearch API error handling update date

Please be informed that the OpenSearch API error handling update is planned on **17th of October 2023**. The details of the change are explained [here](https://documentation.dataspace.copernicus.eu/APIs/UpcomingChanges.html#opensearch-api-error-handling-update). 

## OpenSearch API error handling update

Please be informed that the **OpenSearch API** error handling will be updated soon. 

Please also note that new responses with errors will provide the `RequestId` which is intended to help identify the requests with errors. It is strongly recommended to include the `RequestId` in your issues submitted to the support team in case of Catalog API problems.

The new error handling is described below.

#### Incorrect collection name

::: {.panel-tabset}

# Current response
```{json}
{
    "detail": {
        "ErrorMessage": "loadFromStore - Not Found",
        "ErrorCode": 404
    }
}
```
# New response
```{json}
{
    "detail": {
        "ErrorMessage": "Unknown collection.",
        "ErrorCode": 404,
        "ErrorDetail": [
            {
                "loc": [
                    "collection"
                ],
                "msg": "Collection '<collection name presented in query>' does not exist.",
            },
        ],
        "RequestId": <request_id>,
    }
}
```
:::

**Example**

::: {.panel-tabset}

# HTTP Request

[`https://datahub.creodias.eu/resto/api/collections/Sentinl2/search.json`](<https://datahub.creodias.eu/resto/api/collections/Sentinl2/search.json>){target="_blank"}

# New response example
```{json}
{
    "detail": {
        "ErrorMessage": "Unknown collection.",
        "ErrorCode": 404,
        "ErrorDetail": [
            {
                "loc": [
                    "collection"
                ],
                "msg": "Collection 'Sentinl2' does not exist."
            },
        ],
        "RequestID": "70970f42-e374-4e26-8778-41a1463e700d"
    }
}

```

:::

#### Incorrect name of the query parameter 
(when the collection is not specified)

::: {.panel-tabset}

# Current response

No error is returned. The incorrect query parameter is ignored and not reflected in `appliedFilters`. 

# New response

```{json}
{
    "detail": {
        "ErrorMessage": "Unknown query parameter(s).",
        "ErrorCode": 400,
        "ErrorDetail": [
            {
                "loc": [<list of unexisting parameters>],
                "msg": "Query parameters do not exist.",
            },
        ],
        "RequestId": <request_id>,
    }
}

```

:::

**Example**

::: {.panel-tabset}

# HTTP Request

[`https://datahub.creodias.eu/resto/api/collections/search.json?productsType=S2MSI1C`](<https://datahub.creodias.eu/resto/api/collections/search.json?productsType=S2MSI1C>){target="_blank"}

# New response example
```{json}
{
    "detail": {
        "ErrorMessage": "Unknown query parameter(s).",
        "ErrorCode": 400,
        "ErrorDetail": {
            "loc": [
                "productsType"
            ],
            "msg": "Query parameters do not exist."
        },
        "RequestID": "d9f22173-4d56-44fd-ab18-35d6018c49d7"
    }
}
```

:::

#### Incorrect name of the query parameter 
(when the collection is specified)

::: {.panel-tabset}

# Current response

No error is returned. The incorrect query parameter is ignored and not reflected in `appliedFilters`. 

# New response
```{json}
{
    "detail": {
        "ErrorMessage": "Unknown query parameter(s).",
        "ErrorCode": 400,
        "ErrorDetail": [
            {
                "loc": [<list of unexisting parameters>],
                "msg": "Query parameters do not exist or are not available for specified collection.",
            },
        ],
        "RequestId": <request_id>,
  }
}
```

:::

**Example**

::: {.panel-tabset}

# HTTP Request

[`https://datahub.creodias.eu/resto/api/collections/Sentinel2/search.json?productType=S2MSI1C&startDat=2023-06-11&completionDte=2023-06-22`](<https://datahub.creodias.eu/resto/api/collections/Sentinel2/search.json?productType=S2MSI1C&startDat=2023-06-11&completionDte=2023-06-22>){target="_blank"}

# New response example
```{json}
{
    "detail": {
        "ErrorMessage": "Unknown query parameter(s).",
        "ErrorCode": 400,
        "ErrorDetail": {
            "loc": [
                "startDat",
                "completionDte",
                        ],
            "msg": "Query parameters do not exist or are not available for specified collection."
        },
        "RequestID": "25d522af-ba4e-4152-a368-9635d560e649"
    }
}
```

:::

::: {.callout-note}


Please note that `dataset` parameter will **not** be supported anymore. Any query with the `dataset` parameter will result in an error. 


:::

#### Incorrect value of the query parameter 
*(maxRecords, index, page, sortParam, sortOrder, exactCount, geometry, box, lon, lat, radius, startDate, completionDate, updated, published, publishedAfter, publishedBefore, status)*

::: {.panel-tabset}

# Current response

```{json}
{
    "detail": {
        "ErrorMessage": <error message>,
        "ErrorCode": 400
    }
}
```

# New response

```{json}
{
    "detail": {
        "ErrorMessage": "Validation error.",
        "ErrorCode": 400,
        "ErrorDetail": [
            {
                "loc": [<list of parameters that error "msg" field relate to>],
                "msg”: <error message>}>,
         	},
        ]
        "RequestId": <request_id>,
  }
}
```

:::

**Example**

::: {.panel-tabset}

# HTTP Request

[`https://datahub.creodias.eu/resto/api/collections/search.json?startDate=2021-07-01T00:00:00Z&completionDate=2021-07-31T23:59:59Z&maxRecords=2001`](<https://datahub.creodias.eu/resto/api/collections/search.json?startDate=2021-07-01T00:00:00Z&completionDate=2021-07-31T23:59:59Z&maxRecords=2001>){target="_blank"}

# New response example

```{json}
{
    "detail": {
        "ErrorMessage": "Validation error.",
        "ErrorCode": 400,
        "ErrorDetail": [
            {
                "loc": [
                    "maxRecords"
                ],
                "msg": "Input should be less than or equal to 2000."
            }
        ],
        "RequestID": "b3b4c0bb-9697-4ff8-b90c-4eb1b97a9914"
    }
}
```

:::

::: {.callout-note}

We kindly remind you that for `status` parameter the **only** acceptable values will be:

- ONLINE 
- OFFLINE 
- ALL

Any other value will result in an error. 

:::


#### Incorrect value type of the query parameter

::: {.panel-tabset}

# Current response

```{json}
{
    "detail": {
        "ErrorMessage": <error message>,
        "ErrorCode": 400
    }
}
```

# New response
```{json}
{
    "detail": {
        "ErrorMessage": "Validation error.",
        "ErrorCode": 400,
        "ErrorDetail": [
            {
                "loc": [<list of parameters that error "msg" field relate to>],
                "msg”: <error message>}>,
         	},
        ]
        "RequestId": <request_id>,
  }
}
```

:::

**Example**

::: {.panel-tabset}

# HTTP Request

[`https://datahub.creodias.eu/resto/api/collections/search.json?orbitNumber=ascending`](<https://datahub.creodias.eu/resto/api/collections/search.json?orbitNumber=ascending>){target="_blank"}

# New response example
```{json}
{
    "detail": {
        "ErrorMessage": "Validation error.",
        "ErrorCode": 400,
        "ErrorDetail": [
            {
                "loc": [
                    "orbitNumber"
                ],
                "msg": "Proper value types for specified attribute query parameters are: 'orbitNumber'-integer"
            }
        ],
        "RequestID": "33e3ebb0-7d44-4dcd-8cb2-f60216c11cef"
    }
}
```

:::

Please also note about the following change:

* update of the `last` link

The `last` link will be provided *only* when `exactCount` is used in the request. 

::: {.panel-tabset}

# Link `last` example

```{json}
{
    "rel": "last",
    "type": "application/json",
    "title": "last",
    "href": "https://catalogue.dataspace.copernicus.eu/resto/api/collections/Sentinel2/search.json?page=19168&processingLevel=S2MSI1C&startDate=2023-07-01&completionDate=2023-07-31&sortParam=startDate&exactCount=1"
}

```
:::

We recommend reviewing the upcoming changes to **Catalog OpenSearch API** described above to avoid disruption to your current scripts or apps.

## STAC API interface update

Please be informed that the **STAC API** items interface will be updated on the **5th of October 2023**. The update will be announced in a separate release note within [release notes document](ReleaseNotes.qmd). 

The update will cover the removal of `beginningDateTime` and `endingDateTime`.
Eventually, to be compliant with the STAC item specification `beginningDateTime` and `endingDateTime` will be replaced by `start_datetime` and `end_datetime`.


::: {.panel-tabset}

# STAC Request Example

[`https://datahub.creodias.eu/stac/collections/SENTINEL-3/items?`](<https://datahub.creodias.eu/stac/collections/SENTINEL-3/items?>){target="_blank"}

:::

#### STAC API response change

::: {.panel-tabset}

# Current response
```{json}
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "stac_version": "1.0.0",
            "stac_extensions": [],
            "id": "S3B_SY_2_VG1____20230901T000000_20230901T235959_20230902T123317_WEST_ASIA_________PS2_O_ST_002.SEN3",
            "collection": "SENTINEL-3",
            "geometry": {...},
            "properties": {
                "landCover": 42.043158,
                "cloudCover": 4.955728,
                "timeliness": "ST",
                "cycleNumber": 83,
                "orbitNumber": 27607,
                "processorName": "PUG",
                "orbitDirection": "ascending",
                "processingDate": "2023-09-02T12:41:10+00:00",
                "snowOrIceCover": 0.135336,
                "operationalMode": "Earth Observation",
                "processingLevel": "2",
                "processorVersion": "03.49",
                "platformShortName": "SENTINEL-3",
                "baselineCollection": "002",
                "instrumentShortName": "SYNERGY",
                "relativeOrbitNumber": 0,
                "platformSerialIdentifier": "B",
                "datetime": null,
                "end_datetime": "2023-09-01T23:59:59.000Z",
                "start_datetime": "2023-09-01T00:00:00.000Z",
                "endingDateTime": "2023-09-01T23:59:59.000Z",
                "beginningDateTime": "2023-09-01T00:00:00.000Z",
                "productType": "SY_2_VG1___"
            },
            "bbox": [...],
            "links": [...],
            "assets": {...}
        }
    ]
}
```
# New response
```{json}
{
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "stac_version": "1.0.0",
            "stac_extensions": [],
            "id": "S3B_SY_2_VG1____20230901T000000_20230901T235959_20230902T123317_WEST_ASIA_________PS2_O_ST_002.SEN3",
            "collection": "SENTINEL-3",
            "geometry": {...},
            "properties": {
                "landCover": 42.043158,
                "cloudCover": 4.955728,
                "timeliness": "ST",
                "cycleNumber": 83,
                "orbitNumber": 27607,
                "processorName": "PUG",
                "orbitDirection": "ascending",
                "processingDate": "2023-09-02T12:41:10+00:00",
                "snowOrIceCover": 0.135336,
                "operationalMode": "Earth Observation",
                "processingLevel": "2",
                "processorVersion": "03.49",
                "platformShortName": "SENTINEL-3",
                "baselineCollection": "002",
                "instrumentShortName": "SYNERGY",
                "relativeOrbitNumber": 0,
                "platformSerialIdentifier": "B",
                "datetime": null,
                "end_datetime": "2023-09-01T23:59:59.000Z",
                "start_datetime": "2023-09-01T00:00:00.000Z",
                "productType": "SY_2_VG1___"
            },
            "bbox": [...],
            "links": [...],
            "assets": {...}
        }
    ]
}
```
:::

We recommend reviewing the upcoming changes to **Catalog STAC API** described above to avoid disruption to your current scripts or apps.
