---
title: CTY 10m Yearly (2017-present)
---
## About
[Official documentation](https://land.copernicus.eu/en/products/high-resolution-layer-croplands)

The High Resolution Layer Crop Types (CTY) raster product provides high resolution crop type classification for 17 classes of both arable and permanent crops accross the EEA38 extent. Using both Sentinel-1 and Sentiel-2, the model is finetuned to first map the crop field boundaries, and then determine the main crop for each field.

This dataset is provided annually starting in 2017 with 10 meter rasters (fully conformant with the EEA reference grid) in 100 x 100 km tiles covering the EEA38 countries.

High Resolution Layer Croplands product is part of the European Union's Copernicus Land Monitoring Service. Confidence layer available for the dataset.

This dataset includes data from the French Overseas Territories (DOMs)

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_VLCC_CROP-TYPES_EUROPE_10M_YEARLY_V1&clmsSelectedPath=Crop%20Types&clmsSelectedCollection=COPERNICUS_CLMS_VLCC_CROP-TYPES_EUROPE_10M_YEARLY_V1) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

| Collection | ID |
|:---------:|----|
|Crop Types Europe 10m Yearly V1|`4fa71893-371f-4440-97c4-917f569f67b2`|
|Crop Types Confidence Layer Europe 10m Yearly V1|`82c292b4-1041-46c6-836a-4f7afe025d99`|

## Date range

2017 - present

## Bands

Crop Types Europe 10m Yearly V1

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|CTY|Cropland crop type classification (19 types)|Categorical label on crop type
|UINT16|0.0-3200.0|1|0|
Crop Types Confidence Layer Europe 10m Yearly V1

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|CTYCL|Confidence of crop type classification|Probability as obtained from the confidence of the selected crop type class
|UINT8|0.0-100.0|1|0|


## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/land-cover-and-land-use-mapping/croplands/crop-types/crop-types/clms_vlcc_crop-types_europe_10m_yearly_v1)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/Batch.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.

