---
title: WDS Europe 60m Daily V2
collection: e52773f2-d35d-492d-8144-371a9e741212
---
## About
[Official documentation](https://land.copernicus.eu/en/products/snow/high-resolution-wet-dry-snow)

The **Wet / Dry Snow (WDS)** product provides information on the snow state (wet or dry) by combining **Sentinel-1** radar-based wet snow maps within the snow cover extent derived from **Sentinel-2** optical data. Cloud detection in the Sentinel-2 imagery is performed using the [MAJA software](https://gitlab.orfeo-toolbox.org/maja/maja/).<br><br>It is generated in near real-time at European scale, with a spatial resolution of **60 m x 60 m** in areas where Sentinel-1 and Sentinel-2 observation tracks overlap.<br><br>**Data availability**: from 2016 to the present. No product is generated for a Sentinel-2 tile when cloud cover exceeds 90%.<br><br>More information [here](https://land.copernicus.eu/en/products/snow/high-resolution-wet-dry-snow).

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_WSI_WET-DRY-SNOW_EUROPE_UTM_60M_DAILY_V2&clmsSelectedPath=Snow%20State&clmsSelectedCollection=COPERNICUS_CLMS_WSI_WET-DRY-SNOW_EUROPE_UTM_60M_DAILY_V2) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

```default
e52773f2-d35d-492d-8144-371a9e741212
```

## Date range

2016 - present

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|SSC|Snow State Classification|wet snow / dry snow / snow free / patchy snow cover / radar shadow / layover / foreshortening / cloud / cloud shadow / water / forest / urban area|UINT8|110.0-230.0|1|0|
|SSC_QA|Quality layer for the snow state classification (SSC) layer|high quality / medium quality / low quality / minimal quality / masked|UINT8|0.0-250.0|1|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/bio-geophysical-parameters/snow/snow-state/clms_wsi_wet-dry-snow_europe_utm_60m_daily_v2)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/BatchV2.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
