---
title: SWS Europe (high mountains) 60m Daily V2
collection: 41fc21f0-b657-4346-a4ab-aafc8cc636f2
---
## About
[Official documentation](https://land.copernicus.eu/en/products/snow/high-resolution-sar-wet-snow)

The SAR Wet Snow (SWS) product provides the wet snow extent for high mountain areas with a spatial resolution of 60 m x 60 m. It is generated in near real-time for selected high mountain areas at European scale based on C-band Synthetic Aperture Radar satellite data from the Sentinel-1 constellation. It is available for the period from 2016 to the present. More information here.

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_WSI_SAR-WET-SNOW_EUROPE_UTM_60M_DAILY_V2&clmsSelectedPath=Snow%20State&clmsSelectedCollection=COPERNICUS_CLMS_WSI_SAR-WET-SNOW_EUROPE_UTM_60M_DAILY_V2) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

`41fc21f0-b657-4346-a4ab-aafc8cc636f2`

## Date range

2016 - present

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|WSM|Wet Snow classification in high Mountains areas|110: wet snow, 125: dry snow or no snow or patchy snow, 200: radar shadow or layover or foreshortening, 210: water, 220: forest, 230: urban areas, 240: non-mountain areas|UINT8|110.0-240.0|1|0|
|WSM_QA|Quality layer for the wet snow classification (WSM) layer|0: high quality, 1: medium quality, 2: low quality, 3: minimal quality, 250: masked|UINT8|0.0-250.0|1|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/bio-geophysical-parameters/snow/snow-state/clms_wsi_sar-wet-snow_europe_utm_60m_daily_v2)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/BatchV2.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
