---
title: Catalog API examples
format:
  html:
    code-fold: true
jupyter: python3
---

The requests below are written in python. To execute them you need to
create an OAuth client as is explained
[here](/APIs/SentinelHub/Overview/Authentication.qmd#python). It is
named `oauth` in these examples.

### Catalog API Entry page

Catalog API Entry page with link to other catalog API endpoints and
available collections.

```{python}
#| echo: false
#import packages
import requests
import pandas as pd
```

::: {.panel-tabset}

# HTTP Request

[`https://sh.dataspace.copernicus.eu/api/v1/catalog/1.0.0/`](https://sh.dataspace.copernicus.eu/api/v1/catalog/1.0.0/){target="_blank"}

# Python
```{python}
url = "https://sh.dataspace.copernicus.eu/api/v1/catalog/1.0.0/"

response = requests.get(url)
data = response.json()
pd.DataFrame.from_dict(data['links']).tail(3)
```

:::

### List collections

List all available collections. The list will include deployment
specific collections and collections available to users through BYOC,
Batch or Third Party Data Import functionalities.

::: {.panel-tabset}

# HTTP Request

[`https://sh.dataspace.copernicus.eu/api/v1/catalog/1.0.0/collections`](https://sh.dataspace.copernicus.eu/api/v1/catalog/1.0.0/collections){target="_blank"}

# Python
```{python}
response = requests.get("https://sh.dataspace.copernicus.eu/api/v1/catalog/1.0.0/collections").json()
df = pd.DataFrame.from_dict(response['collections']).head(3)
df[['stac_version','type','id','title','description']]
```

:::

### Sentinel 2 L1C collection

List single collection, in this case Sentinel 2 L1C collection.

::: {.panel-tabset}

# HTTP Request

[`https://sh.dataspace.copernicus.eu/api/v1/catalog/1.0.0/collections/sentinel-2-l1c/`](https://sh.dataspace.copernicus.eu/api/v1/catalog/1.0.0/collections/sentinel-2-l1c/){target="_blank"}

# Python
```{python}
response = requests.get("https://sh.dataspace.copernicus.eu/api/v1/catalog/1.0.0/collections/sentinel-2-l1c/").json()
pd.DataFrame.from_dict(response['links'])
```

:::

### Simple GET search

Simple version of search available via GET request is also available.
The only query parameters that can be specified in this simpler version
are: `bbox`, `datetime`, `collections`, `limit` and `next`.

``` python
query = {
    "bbox": "13,45,14,46",
    "datetime": "2019-12-10T00:00:00Z/2019-12-11T00:00:00Z",
    "collections": "sentinel-1-grd",
    "limit": 5,
}

url = "https://sh.dataspace.copernicus.eu/api/v1/catalog/1.0.0/search"
response = oauth.get(url, params=query)
```

### Simple POST search

The same parameters can also be specified a POST request, query
parameters need to be specified as `json` formatted body and sent to
server like:

``` python
data = {
    "bbox": [13, 45, 14, 46],
    "datetime": "2019-12-10T00:00:00Z/2019-12-10T23:59:59Z",
    "collections": ["sentinel-1-grd"],
    "limit": 5,
}

url = "https://sh.dataspace.copernicus.eu/api/v1/catalog/1.0.0/search"
response = oauth.post(url, json=data)
```

### Simple POST search with pagination

`next` token can be specified in the request to get back the next page
of results.

``` python
data = {
    "bbox": [13, 45, 14, 46],
    "datetime": "2019-12-10T00:00:00Z/2019-12-10T23:59:59Z",
    "collections": ["sentinel-1-grd"],
    "limit": 5,
    "next": 5,
}

url = "https://sh.dataspace.copernicus.eu/api/v1/catalog/1.0.0/search"
response = oauth.post(url, json=data)
```

### Search with GeoJSON

Instead of `bbox` it is possible to add `intersects` attribute, which
can be any type of GeoJSON object (Point, LineString, Polygon,
MultiPoint, MultiPolygon).

``` python
data = {
    "datetime": "2019-12-10T00:00:00Z/2019-12-11T00:00:00Z",
    "collections": ["sentinel-1-grd"],
    "limit": 5,
    "intersects": {
        "type": "Point",
        "coordinates": [
            13,
            45,
        ],
    },
}

url = "https://sh.dataspace.copernicus.eu/api/v1/catalog/1.0.0/search"
response = oauth.post(url, json=data)
```

### Search with Filter

`filter` object can be used to instruct server to only return a specific
subset of data.

``` python
data = {
    "bbox": [13, 45, 14, 46],
    "datetime": "2019-12-10T00:00:00Z/2019-12-11T00:00:00Z",
    "collections": ["sentinel-1-grd"],
    "limit": 5,
    "filter": "sat:orbit_state='ascending'",
}

url = "https://sh.dataspace.copernicus.eu/api/v1/catalog/1.0.0/search"
response = oauth.post(url, json=data)
```

### Get Filter parameters for collection

List all available filter parameters represented as JSON Schema.

``` python
url = "https://sh.dataspace.copernicus.eu/api/v1/catalog/1.0.0/collections/sentinel-1-grd/queryables"
response = oauth.get(url)
```

### Search with Fields: No fields

Default outputs from the server can be quite verbose for some
collections. By default, all available item properties are included in
the response.

``` python
data = {
    "bbox": [13, 45, 14, 46],
    "datetime": "2019-12-10T00:00:00Z/2019-12-11T00:00:00Z",
    "collections": ["sentinel-2-l1c"],
    "limit": 1,
}

url = "https://sh.dataspace.copernicus.eu/api/v1/catalog/1.0.0/search"
response = oauth.post(url, json=data)
```

### Search with Fields: Empty fields

`fields` attribute can be specific to return less information. When
`fields` object is empty only a default set of properties is included:
`id`, `type`, `geometry`, `bbox`, `links`, `assets`.

``` python
data = {
    "bbox": [13, 45, 14, 46],
    "datetime": "2019-12-10T00:00:00Z/2019-12-11T00:00:00Z",
    "collections": ["sentinel-2-l1c"],
    "limit": 1,
    "fields": {},
}

url = "https://sh.dataspace.copernicus.eu/api/v1/catalog/1.0.0/search"
response = oauth.post(url, json=data)
```

### Search with Fields: Include

By specifying additional attributes in the `include` list, those
attributes are added to the output along with the default ones.

``` python
data = {
    "bbox": [13, 45, 14, 46],
    "datetime": "2019-12-10T00:00:00Z/2019-12-11T00:00:00Z",
    "collections": ["sentinel-2-l1c"],
    "limit": 1,
    "fields": {"include": ["properties.gsd"]},
}

url = "https://sh.dataspace.copernicus.eu/api/v1/catalog/1.0.0/search"
response = oauth.post(url, json=data)
```

### Search with Fields: Exclude

`exlude` list can be used to exclude even the default ones from the
output.

``` python
data = {
    "bbox": [13, 45, 14, 46],
    "datetime": "2019-12-10T00:00:00Z/2019-12-11T00:00:00Z",
    "collections": ["sentinel-2-l1c"],
    "limit": 1,
    "fields": {"exclude": ["properties.datetime"]},
}

url = "https://sh.dataspace.copernicus.eu/api/v1/catalog/1.0.0/search"
response = oauth.post(url, json=data)
```

### Search with distinct

Using `distinct` it is possible to get some overview of the data
available inside the specified query. For example specifying `date` as
an option will return a list of dates where data is available.

``` python
data = {
    "bbox": [13, 45, 14, 46],
    "datetime": "2019-12-01T00:00:00Z/2020-01-01T00:00:00Z",
    "collections": ["sentinel-1-grd"],
    "limit": 100,
    "distinct": "date",
}

url = "https://sh.dataspace.copernicus.eu/api/v1/catalog/1.0.0/search"
response = oauth.post(url, json=data)
```

Or see different Sentinel 1 instrument modes used.

``` python
data = {
    "bbox": [13, 45, 14, 46],
    "datetime": "2019-12-01T00:00:00Z/2020-01-01T00:00:00Z",
    "collections": ["sentinel-1-grd"],
    "limit": 100,
    "distinct": "sar:instrument_mode",
}

url = "https://sh.dataspace.copernicus.eu/api/v1/catalog/1.0.0/search"
response = oauth.post(url, json=data)
```

### Search on BYOC/BATCH collections

You can search for features on your own BYOC or Batch collections. The
functionality described above regarding GET and POST search is the same.
The only difference is that you have to specify the collection id with
the appropriate prefix on `collections` parameter (e.g:
`byoc-<your-collection-id>` for byoc or `batch-<your-collection-id>` for
batch). Remember that you will have to use the appropriate deployment
endpoint depending on where your collection is hosted.

``` python
data = {
    "bbox": [13, 45, 14, 46],
    "datetime": "2019-12-10T00:00:00Z/2019-12-10T23:59:59Z",
    "collections": ["byoc-<byoc-collection-id>"],
    "limit": 5,
}

url = "https://sh.dataspace.copernicus.eu/api/v1/catalog/1.0.0/search"
response = oauth.post(url, json=data)
```

Or using GET simple search endpoint:

``` python
query = {
    "bbox": "13,45,14,46",
    "datetime": "2019-12-10T00:00:00Z/2019-12-11T00:00:00Z",
    "collections": "batch-<batch-collection-id>",
    "limit": 5,
}

url = "https://sh.dataspace.copernicus.eu/api/v1/catalog/1.0.0/search"
response = oauth.get(url, params=query)
```

```{python}
#| echo: false

import os

def get_auth():
    # token generation
    from oauthlib.oauth2 import BackendApplicationClient
    from requests_oauthlib import OAuth2Session

    # Your client credentials
    # client_id = 'adea6192-2672-4296-94aa-1bcb9e5d2df7'
    client_id = os.environ['CLIENT_ID']
    client_secret = os.environ['CLIENT_SECRET']
    # client_secret = '~BRX82#Ii(-0N<,iVI@.d<lw~<sd~Ti?GU.N!6Y)'

    # Create a session
    client = BackendApplicationClient(client_id=client_id)
    oauth = OAuth2Session(client=client)

    # Get token for the session
    gen_token = oauth.fetch_token(token_url='https://services.sentinel-hub.com/oauth/token',
                              client_secret=client_secret)
    return gen_token['access_token'] 

token = get_auth()
```

::: {.panel-tabset}

# Sample test rendering with token 
```{python}

url = "https://services.sentinel-hub.com/api/v1/catalog/1.0.0/search"
query = {
    "bbox": "13,45,14,46",
    "datetime": "2019-12-10T00:00:00Z/2019-12-11T00:00:00Z",
    "collections": "sentinel-1-grd",
    "limit": 5,
}
headers = {
  "Content-Type": "application/json",
  "Authorization": f"Bearer {token}"}

response = requests.get(url, params=query,headers=headers).json()
pd.DataFrame.from_dict(response['features']).head(3)

```

:::