---
title: NDVI 1999-2020 (raster 1 km), global, 10-daily – version 3
collection: 61caacdf-8a23-471c-b3d3-e5a8a537c44d
---
## About
[Official documentation](https://land.copernicus.eu/en/products/vegetation/normalised-difference-vegetation-index-v3-0-1km)

NDVI is an indicator of the greenness of the biomes. Every 10-days estimates are available at global scale in the spatial resolution of about 1 km from 1999 to 2013 based upon SPOT/VEGETATION data and from 2014 to June 2020 based upon PROBA-V data.

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_VEGETATION_INDICES_NDVI_GLOBAL&clmsSelectedPath=Vegetation%20Indices&clmsSelectedCollection=COPERNICUS_CLMS_VEGETATION_INDICES_NDVI_GLOBAL) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

`61caacdf-8a23-471c-b3d3-e5a8a537c44d`

## Date range

1999 - 2020

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|NDVI|Normalized Difference Vegetation Index|-|UINT8|-0.08-0.92|1/250|-0.08|
|UNC|Uncertainty associated to NDVI|-|INT16|0.0-1.0|1/1000|0|
|NOBS|Number of observations used in the BRDF inversion|-|UINT8|0.0-32.0|1|0|
|QFLAG|Quality flag|-|UINT8|---|1|0|
|TIMEGRID|Time between the median date of observations used to compute NDVI and the reference time given in the file name.|Minutes|INT16|-8640.0-15840.0|1|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/bio-geophysical-parameters/vegetation/vegetation-indices/ndvi_global_1km_10daily_v3)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/Batch.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
