---
title: Lake Surface Water Temperature 2016-present (raster 1 km), global, 10-daily, Near Real Time – version 1
---
## About
[Official documentation](https://land.copernicus.eu/en/products/temperature-and-reflectance/lake-surface-water-temperature-near-real-time-v1-0-1km)

Provides the temperature of the water at the lake surface. The near real time observations (every 10 days) are available at global scale at spatial resolution of ~1 km and with the temporal extent from 2016 to present.

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_LSWT_NRT_GLOBAL_1KM_10DAILY_V1&clmsSelectedPath=Lake%20Surface%20Water%20Temperature&clmsSelectedCollection=COPERNICUS_CLMS_LSWT_NRT_GLOBAL_1KM_10DAILY_V1) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

`401ca642-a169-4783-b1cf-cbd33e98eccb`

## Date range

2016 - present

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|LSWT|Lake surface skin temperature, weighted average over the aggregation period.|Kelvin|INT16|-200.0-5000.0|0.01|273.15|
|UNC|Uncertainties on LSWT|Kelvin|INT16|0.0-10000.0|0.001|0|
|STDEV|Standard deviation of the LSWT observations within the aggregation time period|Kelvin|INT16|---|0.001|0|
|NOBS|Number of LSWT observations contributing to the average|-|INT8|0.0-21.0|1|0|
|QLEVEL|Quality level|Quality flags: 0=no_data, 1=bad_data, 2=worst_quality, 3=low_quality, 4=acceptable_quality, 5=best_quality|INT8|---|1|0|
|TOBS|Bitwise observation time|Bit flags for days 1-11 within dekad|INT16|---|1|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/bio-geophysical-parameters/temperature-and-reflectance/lake-surface-water-temperature/lswt-nrt_global_1km_10daily_v1)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/BatchV2.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
