---
title: CPSCT 10m Yearly (2017-present)
collection: 63d3bcc2-413c-43c1-bde4-d6252860b666
---
## About
[Official documentation](https://land.copernicus.eu/en/products/high-resolution-layer-croplands)

The High Resolution Layer Cropping Patterns - Secondary Crop Type (CPSCT) raster product indicates if a cover crop was present within the respective calendar year and further segregates the types of cover crop into: short summer, long summer, short winter and long winter cover crop.

This dataset is provided annually starting in 2017 with 10 meter rasters (fully conformant with the EEA reference grid) in 100 x 100 km tiles covering the EEA38 countries.

High Resolution Layer Croplands product is part of the European Union’s Copernicus Land Monitoring Service. Confidence layer available for the dataset.

This dataset includes data from the French Overseas Territories (DOMs)

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_VLCC_SECONDARY-CROP-TYPES_EUROPE_10M_YEARLY_V1&clmsSelectedPath=Secondary%20Crop%20Types&clmsSelectedCollection=COPERNICUS_CLMS_VLCC_SECONDARY-CROP-TYPES_EUROPE_10M_YEARLY_V1) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

`63d3bcc2-413c-43c1-bde4-d6252860b666`

## Date range

2017 - present

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|CPSCT|Classification of secondary crop type|0 = No annual cropland, 1 = Short summer CC, 2 = Long summer CC, 3 = Short winter CC, 4 = Long winter CC, 65526 = 65526, 65527 = 65527, 65530 = 65530, 65531 = 65531, 65532 = 65532, 65533 = 65533, 65534 = 65534, 65535 = Outside area|UINT16|0.0-65535.0|1|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/land-cover-and-land-use-mapping/croplands/cropping-patterns/secondary-crop-types/clms_vlcc_secondary-crop-types_europe_10m_yearly_v1)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/Batch.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
