---
title: LWQ 2019-2024 (raster 100 m), global, 10-daily – version 2
---
## About
[Official documentation](https://land.copernicus.eu/en/products/water-bodies/lake-water-quality-v2-0-100m)

Provides semi-continuous observations for a large number of medium and large-sized lakes, according to the Global Lakes and Wetlands Database (GLWD) or otherwise of specific environmental monitoring interest. 10-daily observations are available in near real time at 100 m spatial resolution from September 2024 to present.

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_LWQ_NRT_GLOBAL_100M_10DAILY_V2&clmsSelectedPath=Lake%20Water%20Quality&clmsSelectedCollection=COPERNICUS_CLMS_LWQ_NRT_GLOBAL_100M_10DAILY_V2) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

`0a19176d-1c7b-420a-9dd4-2b8ef4acb153`

## Date range

2024 - present

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|CHLAMEAN|Mean concentration of chlorophyll-a (in the observation period)|mg/m3|FLOAT32|0.0-0.0|1|0|
|FCBPROB|Probability of floating cyanobacteria (with a range of values from 0 to 1 indicating probability of cyanobacteria presence – the closer the value is to 1, the higher the probability)|Average probability of presence in the observed period|FLOAT32|0.0-1.0|1|0|
|FOBS|Age in days after the start of the observation period of the first observation included in the pixel area|Days since the start of the observation period|FLOAT32|0.0-10.0|1|0|
|LOBS|Age in days after the start of the observation period of the last observation included in the pixel area|Days since the start of the observation period|FLOAT32|0.0-10.0|1|0|
|NOBS|Number of observations of the pixel area (including masked and invalid observations)|-|INT16|0.0-0.0|1|0|
|QFLAG|Flag band showing why input observations to a pixel have been included. Flags are L1_invalid, bright_pixels, cloud, snow_ice, land, turbidity_invalid, chla_invalid, tsm_invalid, atmospheric_correction_failure, floating_cyanobacteria, floating_macrophytes_or_mixed_pixel||UINT16|0.0-0.0|1|0|
|R1375|Representative spectrum of fully normalised water-leaving reflectance at Rw1375|-|FLOAT32|0.0-1.0|1|0|
|R1610|Representative spectrum of fully normalised water-leaving reflectance at Rw1610|-|FLOAT32|0.0-1.0|1|0|
|R2190|Representative spectrum of fully normalised water-leaving reflectance at Rw2190|-|FLOAT32|0.0-1.0|1|0|
|R443|Representative spectrum of fully normalised water-leaving reflectance at Rw443|-|FLOAT32|0.0-1.0|1|0|
|R490|Representative spectrum of fully normalised water-leaving reflectance at Rw490|-|FLOAT32|0.0-1.0|1|0|
|R560|Representative spectrum of fully normalised water-leaving reflectance at Rw560|-|FLOAT32|0.0-1.0|1|0|
|R665|Representative spectrum of fully normalised water-leaving reflectance at Rw665|-|FLOAT32|0.0-1.0|1|0|
|R705|Representative spectrum of fully normalised water-leaving reflectance at Rw705|-|FLOAT32|0.0-1.0|1|0|
|R740|Representative spectrum of fully normalised water-leaving reflectance at Rw740|-|FLOAT32|0.0-1.0|1|0|
|R783|Representative spectrum of fully normalised water-leaving reflectance at Rw783|-|FLOAT32|0.0-1.0|1|0|
|R842|Representative spectrum of fully normalised water-leaving reflectance at Rw842|-|FLOAT32|0.0-1.0|1|0|
|R865|Representative spectrum of fully normalised water-leaving reflectance at Rw865|-|FLOAT32|0.0-1.0|1|0|
|R945|Representative spectrum of fully normalised water-leaving reflectance at Rw945|-|FLOAT32|0.0-1.0|1|0|
|TMEAN|Mean of turbidity in Nephelometric Turbidity Units (NTU) (in the observation period)|NTU|FLOAT32|0.0-0.0|1|0|
|TOBS|||FLOAT32|0.0-0.0|1|0|
|TSI|Trophic state index (TSI) obtained from chlorophyll-a observations, averaged over the observation period. The TSI has a value of 0, 10, 20, 30, 40, 50, 60, 70, 80, 90, or 100 corresponding to the classes given in Carlson (1977), where 0-40 are oligotrophic, 40-60 mesotrophic, 60-80 eutrophic, and 80-100 hypereutrophic|-|FLOAT32|0.0-100.0|1|0|
|TSMMEAN|Mean of concentration of total suspended matter (in the observation period)|g/m³|FLOAT32|0.0-0.0|1|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/bio-geophysical-parameters/water-bodies/lake-water-quality/lwq-nrt_global_100m_10daily_v2)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or "custom script") is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/BatchV2.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
