---
title: LWQ 2024-present (raster 300 m), global, 10-daily – version 2
---
## About
[Official documentation](https://land.copernicus.eu/en/products/water-bodies/lake-water-quality-near-real-time-v2-0-300m)

Provides semi-continuous observations for a large number of medium and large-sized lakes.

[View this dataset in Copernicus Browser](https://browser.dataspace.copernicus.eu/?zoom=10&lat=41.82019&lng=12.57866&themeId=DEFAULT-THEME&datasetId=COPERNICUS_CLMS_LWQ_300M_10DAILY_NRT_V2&clmsSelectedPath=Lake%20Water%20Quality&clmsSelectedCollection=COPERNICUS_CLMS_LWQ_300M_10DAILY_NRT_V2) (Click on 'Show latest date' after the page loads.)

{{< include /APIs/SentinelHub/Data/clms/_include.qmd >}}

### Collection ID

`5c2c9b2c-2893-41d9-b2bc-fbd6e5b8b31d`

## Date range

2024-present

## Bands

| Name          | Description  |   Units |  Source format | Range | Scaling | Offset |
|---------------|--------------|---------|----------------|-------|---------|--------|
|CHLAMEAN|Mean of chlorophyll a concentration|mg/m³|FLOAT32|0.0--|1|0|
|CHLAUNC|Mean of relative uncertainty of chlorophyll a concentration|%|FLOAT32|0.0-1000.0|1|0|
|FCBPROB|Probability of floating cyanobacteria|Average probability of presence in the observed period|FLOAT32|0.0-1.0|1|0|
|FOBS|Number of days from the start of the sensing period until the first cloud-free observation|Days since the start of the observation period|INT16|0.0-10.0|1|0|
|LOBS|Number of days from the start of the sensing period until the last cloud-free observation|Days since the start of the observation period|INT16|0.0-10.0|1|0|
|NOBS|Number of observations|-|INT16|0.0--|1|0|
|QFLAG|Flag band showing why input observations to a pixel have been included.|-|UINT16|---|1|0|
|RW1020|Fully normalised water-leaving reflectance|-|FLOAT32|0.0-1.0|1|0|
|RW400|Fully normalised water-leaving reflectance|-|FLOAT32|0.0-1.0|1|0|
|RW412|Fully normalised water-leaving reflectance|-|FLOAT32|0.0-1.0|1|0|
|RW443|Fully normalised water-leaving reflectance|-|FLOAT32|0.0-1.0|1|0|
|RW490|Fully normalised water-leaving reflectance|-|FLOAT32|0.0-1.0|1|0|
|RW510|Fully normalised water-leaving reflectance|-|FLOAT32|0.0-1.0|1|0|
|RW560|Fully normalised water-leaving reflectance|-|FLOAT32|0.0-1.0|1|0|
|RW620|Fully normalised water-leaving reflectance|-|FLOAT32|0.0-1.0|1|0|
|RW665|Fully normalised water-leaving reflectance|-|FLOAT32|0.0-1.0|1|0|
|RW674|Fully normalised water-leaving reflectance|-|FLOAT32|0.0-1.0|1|0|
|RW681|Fully normalised water-leaving reflectance|-|FLOAT32|0.0-1.0|1|0|
|RW709|Fully normalised water-leaving reflectance|-|FLOAT32|0.0-1.0|1|0|
|RW754|Fully normalised water-leaving reflectance|-|FLOAT32|0.0-1.0|1|0|
|RW779|Fully normalised water-leaving reflectance|-|FLOAT32|0.0-1.0|1|0|
|RW885|Fully normalised water-leaving reflectance|-|FLOAT32|0.0-1.0|1|0|
|RW900|Fully normalised water-leaving reflectance|-|FLOAT32|0.0-1.0|1|0|
|TMEAN|Mean turbidity|NTU|FLOAT32|0.0-500.0|1|0|
|TOBS|Age in days after the start of the observation period|-|FLOAT32|1.0-11.0|1|0|
|TSI|Trophic State Index|-|FLOAT32|0.0-100.0|1|0|
|TSMMEAN|Mean of total suspended matter|g/m³|FLOAT32|0.0-500.0|1|0|
|TSMUNC|	
Mean of relative uncertainty of total suspended matter|%|FLOAT32|0.0-200.0|1|0|
|UNCUB|Relative unbiased uncertainty|%|FLOAT32|-10000.0-10000.0|1|0|
|UNC|Relative uncertainty|%|FLOAT32|-10000.0-10000.0|1|0|

## Evalscript

**[Example scripts for this product.](https://github.com/eu-cdse/sentinel-hub-custom-scripts/tree/main/clms/bio-geophysical-parameters/water-bodies/lake-water-quality/lwq-nrt_global_300m_10daily_v2)**

Use the link above to access dedicated Evalscript examples for this product in the Copernicus Data Space Ecosystem Sentinel Hub Custom Scripts repository.

An Evalscript (or “custom script”) is a piece of Javascript code which defines how the data shall be processed by Sentinel Hub and what values the service shall return. It is a required part of any [process](/APIs/SentinelHub/Process.qmd), [batch processing](/APIs/SentinelHub/Batch.qmd) or [OGC request](/APIs/SentinelHub/OGC.qmd).

Evalscripts can use any JavaScript function or language structures, along with certain [utility functions](/APIs/SentinelHub/Evalscript/Functions.qmd) we provide for your convenience. For running evalscripts we use the [Chrome V8](https://v8.dev/){target="_blank"} JavaScript engine.
